"""The stellarator package's study-local route on stock teax.

Everything here is study knowledge, not tool knowledge: how this package is loaded
(the stock strict loader, nothing else), how a proposal is spelled (the axis
expansions and the one declared tie), the two proof-of-life studies' windows and
validity mask, the exported column names, and the baseline-point executor that
deposits the two documents the generic preflight gates read. A generic tool in
`scripts/study/` holds none of it, which is why this module is package-owned.

No glue. The package is sealed at runtime contract 2.0.0 and stock teax accepts it
with ``strict=True``; the identity a study runs under is the sealed executable
fingerprint itself (`scripts/study/identity.build_sealed`). The five values the
retired era adapter used to inject — the BOP repoint, the CAS28 constant, the
replacement ``n_mod``, the per-point CAS27, three dead fillers — are authored in the
model and generated by codegen (`tests/study/test_stock_route.py` asserts each).

Teax is imported from ``STOP_PARSER_TEAX_ROOT`` by the caller (the sealed-runner
contract); this module only imports ``simkit`` lazily, inside the functions that need it.

Entry-key shape (after the stellarator model migration, 2026-08-21): the swept axes
are plant-level design attributes, one key each — ``stellarator_09__stellaris__R``,
``__a``, ``__availability`` — because the library formals are now bound by the
``_in`` convention and codegen projects one entry point per authored attribute. The
magnet major radius ``magnet__R0`` is still separately authored, so it is still a
declared physical-identity tie (`ANNEX.md § Declared ties`), never fan-out.
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
E2E = HERE.parent
REPO_ROOT = E2E.parent.parent
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from scripts.study import common, identity  # noqa: E402

PACKAGE_NAME = "stellarator_tea"
PACKAGE_DIR = E2E / "generated"
MANIFEST_PATH = HERE / "manifest.json"
P = "stellarator_09__stellaris__"
BASELINE_RESULT_SCHEMA_VERSION = "study-baseline-result/v1"
EXPECTED_CONSTRAINT_COUNT = 7  # WI-035: wp_stress_ok joins the WI-030 six

# --- Axis declarations: SysML attribute -> complete entry-key expansion ------
AXES: dict[str, list[str]] = {
    "R": [f"{P}R"],
    "a": [f"{P}a"],
    "availability": [f"{P}availability"],
}
#: Declared physical-identity tie: the magnet-cost Ampere's-law current runs on the
#: major radius, so this is the same physical quantity under a separately authored
#: attribute — a tie, not mechanical fan-out. The tie *data* is in the manifest.
R_TIE = f"{P}magnet__R0"

BASELINE = {"R": 12.7, "a": 1.3, "availability": 0.85}
#: The plasma plus the held-fixed radial-build stack must fit inside the major radius
#: or the torus self-intersects. A derived geometric bound from held-fixed inputs, not
#: a design screen. Itemized in ANNEX.md § Validity masks.
BUILD_STACK_M = 2.25
R_VALUES = [round(4.0 + 0.5 * i, 2) for i in range(33)]
A_VALUES = [round(0.80 + 0.05 * i, 2) for i in range(29)]
AVAIL_VALUES = [round(0.50 + 0.025 * i, 3) for i in range(19)]

#: Exported columns: the proof-of-life's own column names, so the after-migration
#: CSVs join the before-migration ones by coordinate and column.
CHANNELS = {
    "lcoe": f"{P}lcoe_calc__lcoe",
    "wall_load": f"{P}wall_load_calc__wall_load",
    "p_fus": f"{P}fusion__p_fus",
    "plasma_volume": f"{P}geom__V",
    "total_capital": f"{P}total_capital__total_capital",
    "magnet_capital": f"{P}magnet_cost__capital_cost",
    "overnight_capital": f"{P}overnight_capital__overnight_capital",
    "lcoe_1cfe": f"{P}lcoe_1cfe_calc__lcoe",
}


class RouteError(Exception):
    """The route could not do what it was asked. Never a silent skip."""


def proposal_for(R: float, a: float, availability: float) -> dict[str, float]:
    """One proposal: the axis expansions plus the declared tie. Nothing else."""
    point: dict[str, float] = {}
    for key in AXES["R"]:
        point[key] = R
    point[R_TIE] = R
    for key in AXES["a"]:
        point[key] = a
    for key in AXES["availability"]:
        point[key] = availability
    return point


def validate_proposal(raw):
    out = {}
    for key, value in raw.items():
        if not isinstance(value, (int, float)) or isinstance(value, bool):
            return None
        out[key] = float(value)
    return out


# ------------------------------------------------------------------ the route


def spec_path(package_dir: Path) -> Path:
    """The package's one pipeline spec, found rather than named."""
    specs = sorted((Path(package_dir) / "pipelines").glob("*.yaml"))
    if len(specs) != 1:
        raise RouteError(f"expected exactly one pipeline spec under {package_dir}, found {specs}")
    return specs[0]


def package_loader(package_dir: Path, link_root: Path):
    """The stock strict loader. The verifier forbids a symlink as the package root, so
    both paths are resolved; ``link_root`` is the caller's because the loader writes an
    import symlink into it, and a default under the package would dirty the tree the
    cleanliness gate watches."""
    from simkit.evaluation.package_load import ProvisionalPackageLoader

    return ProvisionalPackageLoader(
        package_dir=Path(package_dir).resolve(),
        package_name=PACKAGE_NAME,
        link_root=Path(link_root).resolve(),
        strict=True,
    )


def prepare(package_dir: Path, work_dir: Path):
    """Load through the stock loader and prepare the evaluator once.

    ``expects_constraint_report`` is read from the embedded model contract through
    teax's own consumer-side authority, never guessed from the pipeline spec.
    """
    from simkit.evaluation.evaluator import PreparedEvaluator
    from simkit.study.model_contract import load_model_contract, ships_constraint_report

    contract = load_model_contract(Path(package_dir).resolve())
    return PreparedEvaluator(
        package_loader(package_dir, Path(work_dir) / "pkg_link"),
        spec_path(package_dir),
        expects_constraint_report=ships_constraint_report(contract),
    )


def definition(study_id: str, prepared, proposals, package_dir: Path):
    from simkit.study.definition import StudyDefinition
    from simkit.study.identity import digest_of
    from simkit.study.model_contract import load_model_contract
    from simkit.study.policy import ObjectivePolicy
    from simkit.study.strategy import PreparedListStrategy

    return StudyDefinition(
        study_id=study_id,
        entry_models=prepared.entry_models,
        strategy=PreparedListStrategy(proposals),
        validate_proposal=validate_proposal,
        policy=ObjectivePolicy(objectives=(), response_roles={}),
        executable_fingerprint=prepared.fingerprint,
        # The contract's published semantic fingerprint, as teax's own builder binds it:
        # a store never silently rebinds across a model-meaning change.
        model_contract_fingerprint=load_model_contract(
            Path(package_dir).resolve()
        ).semantic_fingerprint,
        input_schema_version="input-v1",
        evidence_schema_version=prepared.EVIDENCE_SCHEMA_VERSION,
        study_definition_fingerprint=digest_of(
            {"proposals": [sorted(p.items()) for p in proposals]}
        ),
    )


def run_points(study_id: str, proposals, work_dir: Path, package_dir: Path = PACKAGE_DIR):
    """Execute proposals through `StudyRunner`. Returns (cases, db path).

    The store is left on disk: a definition that unlinked would leave nothing for a
    lineage refusal to refuse.
    """
    from simkit.study.query import StudyQuery
    from simkit.study.runner import StudyRunner
    from simkit.study.store import StudyStore

    work_dir = Path(work_dir)
    work_dir.mkdir(parents=True, exist_ok=True)
    prepared = prepare(package_dir, work_dir)
    study = definition(study_id, prepared, proposals, package_dir)
    db = work_dir / f"{study_id}.db"
    store = StudyStore.create_or_open(db, study.compatibility())
    store.acquire_lease()
    StudyRunner(store, study, prepared).run()
    store.release_lease()
    store.close()
    return StudyQuery(StudyStore(db), Path(package_dir).resolve()).cases(), db


def write_identity_document(package_dir: Path, out_path: Path) -> Path:
    """The sealed identity: the route bypassed nothing, so the digest *is* the fingerprint."""
    return common.write_document(
        identity.build_sealed(package_name=PACKAGE_NAME, package_root=Path(package_dir)),
        out_path,
    )


# ------------------------------------------------------------------ the studies


def _export_catalog(package_dir: Path) -> dict[str, dict]:
    catalog = _catalog_by_constraint_id(package_dir)
    if len(catalog) != EXPECTED_CONSTRAINT_COUNT:
        raise RouteError(
            f"expected exactly {EXPECTED_CONSTRAINT_COUNT} catalogued checks, "
            f"found {len(catalog)}"
        )
    identities = [entry.get("source_local_identity") for entry in catalog.values()]
    if any(not isinstance(identity, str) or not identity for identity in identities):
        raise RouteError("every catalogued check must have a source_local_identity")
    if len(set(identities)) != len(identities):
        raise RouteError(f"catalogued source_local_identity values are not unique: {identities}")
    return catalog


def _short_verdicts(case, catalog: dict[str, dict]) -> dict[str, str]:
    expected = set(catalog)
    actual = set(case.verdicts)
    if actual != expected:
        missing = sorted(expected - actual)
        unexpected = sorted(actual - expected)
        raise RouteError(
            "case verdicts do not match the emitted constraint catalog: "
            f"missing={missing}, unexpected={unexpected}"
        )
    by_identity = {
        catalog[constraint_id]["source_local_identity"]: status
        for constraint_id, status in case.verdicts.items()
    }
    return {identity: by_identity[identity] for identity in sorted(by_identity)}


def short_verdicts(case, package_dir: Path = PACKAGE_DIR) -> dict[str, str]:
    """Resolve verdict names through the emitted contract, never identifier text."""
    return _short_verdicts(case, _export_catalog(package_dir))


def csv_rows(cases, axes: list[str], package_dir: Path = PACKAGE_DIR) -> list[dict]:
    """Validate every case and build rows without publishing any bytes."""
    cases = list(cases)
    if not cases:
        raise RouteError("cannot export a CSV with no cases")
    catalog = _export_catalog(package_dir)
    rows = []
    for case in cases:
        missing_inputs = [axis for axis in axes if AXES[axis][0] not in case.inputs]
        if missing_inputs:
            raise RouteError(f"case is missing required axes: {missing_inputs}")
        missing_outputs = [
            name
            for name, channel in CHANNELS.items()
            if channel not in case.outputs or case.outputs[channel] is None
        ]
        if missing_outputs:
            raise RouteError(f"case is missing required result channels: {missing_outputs}")
        row = {axis: case.inputs[AXES[axis][0]] for axis in axes}
        for name, channel in CHANNELS.items():
            row[name] = case.outputs[channel]
        verdicts = _short_verdicts(case, catalog)
        row.update(verdicts)
        row["feasible"] = all(status == "satisfied" for status in verdicts.values())
        rows.append(row)
    rows.sort(key=lambda r: tuple(r[axis] for axis in axes))
    return rows


def write_csv(rows: list[dict], path: Path) -> Path:
    """Publish rows that have already passed the complete export contract."""
    if not rows:
        raise RouteError("cannot write a CSV with no validated rows")
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    return path


def export_csv(
    cases, axes: list[str], path: Path, package_dir: Path = PACKAGE_DIR
) -> Path:
    return write_csv(csv_rows(cases, axes, package_dir), path)


def design_search_proposals() -> list[dict[str, float]]:
    grid = [
        proposal_for(R, a, BASELINE["availability"])
        for R in R_VALUES
        for a in A_VALUES
        if R > a + BUILD_STACK_M
    ]
    grid.append(proposal_for(**BASELINE))
    return grid


def availability_sweep_proposals() -> list[dict[str, float]]:
    return [proposal_for(BASELINE["R"], BASELINE["a"], av) for av in AVAIL_VALUES]


def _completed(cases, what: str):
    completed = [c for c in cases if c.state == "completed"]
    if len(completed) != len(cases):
        raise RouteError(
            f"{what}: {len(cases) - len(completed)} of {len(cases)} cases did not complete"
        )
    return completed


def run_design_search(out_dir: Path, package_dir: Path = PACKAGE_DIR) -> Path:
    out_dir = Path(out_dir)
    cases, _ = run_points(
        "stellarator-design-search-ra-v1", design_search_proposals(), out_dir / "_work",
        package_dir,
    )
    return export_csv(
        _completed(cases, "design search"), ["R", "a"], out_dir / "design_search_R_a.csv"
    )


def run_availability_sweep(out_dir: Path, package_dir: Path = PACKAGE_DIR) -> Path:
    out_dir = Path(out_dir)
    cases, _ = run_points(
        "stellarator-availability-sweep-v1", availability_sweep_proposals(), out_dir / "_work",
        package_dir,
    )
    return export_csv(
        _completed(cases, "availability sweep"), ["availability"],
        out_dir / "availability_sweep.csv",
    )


# -------------------------------------------------- the route's baseline path


def _catalog_by_constraint_id(package_dir: Path) -> dict[str, dict]:
    contract = json.loads((Path(package_dir) / "contracts" / "model_contract.json").read_text())
    return {e["constraint_id"]: e for e in contract["constraint_catalog"]["concrete_entries"]}


def _baseline_point(manifest_path: Path) -> dict[str, float]:
    return dict(json.loads(Path(manifest_path).read_text())["baseline"]["point"])


def execute_baseline(
    out_dir: Path,
    *,
    package_dir: Path = PACKAGE_DIR,
    manifest_path: Path = MANIFEST_PATH,
) -> dict[str, Path]:
    """Load the route and execute the manifest's pinned baseline point.

    Deposits `package_identity.json` and `baseline_result.json` into ``out_dir``: the
    runbook's route-preparation step (step 5), and the only producer of the two
    documents preflight's identity and baseline gates consume.
    """
    out_dir = Path(out_dir)
    point = _baseline_point(manifest_path)
    cases, db = run_points("stellarator-baseline-point-v1", [point], out_dir / "_work", package_dir)
    case = _completed(cases, "baseline point")[0]
    catalog = _catalog_by_constraint_id(package_dir)

    identity_path = write_identity_document(package_dir, out_dir / "package_identity.json")
    result = {
        "schema_version": BASELINE_RESULT_SCHEMA_VERSION,
        "executed_under": {
            "identity_digest": case.executable_fingerprint,
            "store_id": common.manifest_mod.repo_relative_posix(db)
            if str(db).startswith(str(REPO_ROOT)) else db.name,
            "case_id": case.candidate_id,
        },
        "point": {key: float(value) for key, value in sorted(point.items())},
        "channels": {key: float(value) for key, value in sorted(case.outputs.items())},
        "verdicts": [
            {
                "constraint_id": constraint_id,
                "definition_qualified_name": catalog[constraint_id]["definition_qualified_name"],
                "source_local_identity": catalog[constraint_id]["source_local_identity"],
                "status": status,
            }
            for constraint_id, status in sorted(case.verdicts.items())
        ],
    }
    result_path = common.write_document(result, out_dir / "baseline_result.json")
    return {"identity": identity_path, "baseline_result": result_path}
