"""Fill the record's result sections (3, 4, 5 judged, 6, 12, 13, 14, 15, 17) from results/interactions.json, results/cases.json, the constraint catalog and the verification summary; append the discovery-log rows. Section 16 is written after the freeze."""
import json, re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[5]
R = ROOT / 'exploration/aries_integrated/studies/20260926-aries-design-choice-interactions'
SID = R.name
P = 'aries_integrated_plant__'
I = json.loads((R / 'results/interactions.json').read_text())
cases = {c['case']: c for c in json.loads((R / 'results/cases.json').read_text())['cases']}
cat = json.loads((R / 'results/constraint_catalog.json').read_text())
ver = json.loads((R / 'results/verification_summary.json').read_text())
rec = (R / 'record.md').read_text()
def section(n):
    m = re.search(rf'^## {n}\. .*?$', rec, re.M); nxt = re.search(rf'^## {n+1}\. .*?$', rec, re.M)
    return m.start(), (nxt.start() if nxt else len(rec))
def replace(n, body):
    global rec
    a, b = section(n); head = rec[a:].split('\n', 1)[0]
    rec = rec[:a] + head + '\n\n' + body.rstrip('\n') + '\n\n' + rec[b:]
lc = {n: c['outputs'][P+'lifecycle_price__evaluate__lcoe'] for n, c in cases.items()}
lo, hi = min(lc, key=lc.get), max(lc, key=lc.get)
replace(3, f"- **LCOE objective channel(s):** `{P}lifecycle_price__evaluate__lcoe` (the manifest headline; equal to `{P}lifecycle_accounts__evaluate__lcoe_sum`), no-breeding-credit convention on every point.\n- **LCOE result:** {lc[lo]:.3f} USD2004/MWh at `{lo}` to {lc[hi]:.3f} at `{hi}`; the two controls reproduce their sealed values (N 1119.408, A 685.695).\n\nThe LCOE is read, not optimized: on this package it is dominated by purchased tritium (prior goal L-001), so the study's readings are on net electricity, unmet heat and the check verdicts, with the LCOE reported as the consequence. Over the 52 points the LCOE moves with net electricity (denominator) and with fusion power (tritium purchases); no case is tuned.")
# § 4
rows = []
for cid, meta in sorted(cat.items()):
    viol = sorted(n for n, c in cases.items() if 'violated' in str(c['verdicts'].get(cid, '')).lower())
    status = 'violated at ' + str(len(viol)) + ' of 52' if viol else 'satisfied at all 52'
    note = ('; '.join(viol) if viol else 'never violated in the swept space')[:400]
    rows.append(f"| `{cid}` | `{meta.get('source_local_identity', cid.split('__')[2])}` | {status} | {note} |")
replace(4, "Every executing constraint by qualified identity; statuses aggregated over the 52 stored points (per-point verdicts in `results/cases.json` and `cases.csv`).\n\n| `constraint_id` | `source_local_identity` | Status | Note |\n|---|---|---|---|\n" + '\n'.join(rows))
axes = ['recuperation', 'he_limit', 'divertor_limit', 'pbli_limit', 'he_flow', 'he_pump_mode', 'density_amplitude', 'hollowness', 'network_mode', 'turbine_efficiency']
why = {'recuperation': 'response observed on both bases; the binding at 0.95/−60 K on A is a located violation, not a boundary claim',
       'he_limit': 'inert on N and on A below 0.95 (all heat removed); acts only through the bound helium stage', 'divertor_limit': 'inert at every point (the divertor stage never binds)', 'pbli_limit': 'inert at every point (the PbLi stage never binds)',
       'he_flow': 'response sign depends on the pump law; violations located (pump screen at 3,900 and 4,000–4,700; helium rating at 4,700 cubic)', 'he_pump_mode': 'the law changes the sign of the flow response',
       'density_amplitude': 'monotone rise of fusion power, net and tritium over the window; heat-removal violation located at 5.75e20 (series) and 5.5e20 (network) at hollowness 0.66', 'hollowness': '0.60 lowers fusion power ≈ 11 % and moves the binding out of the window',
       'network_mode': 'inert where all heat is removed; changes the binding point and the net ranking at the top of the density window', 'turbine_efficiency': '0.90 moves the N corner (0.95, −60 K) into a bound state (36 MW unmet)'}
a, b = section(5); body = rec[a:b]
judged = "**As judged after the run.**\n\n| Axis | Framing judged | Changed? | Why |\n|---|---|---|---|\n" + '\n'.join(f"| `{x}` | sensitivity | no | {why[x]} |" for x in axes)
body = body[:body.index('**As judged after the run.**')] + judged + '\n\n'
rec = rec[:a] + body + rec[b:]
B1, B2, B3 = I['B1'], I['B2'], I['B3']
def acct(axis, resp):
    return f"#### `{axis}` — feasible structure (search framing)\n**Applies:** not applicable — this axis is sensitivity-framed\n\n#### `{axis}` — observed response (sensitivity framing)\n**Applies:** yes\n\n{resp} No boundary claim is made.\n"
gN = {(r['case'].split('-rec')[1].split('-lvl')[0], r['case'].split('-lvl')[1]): r for r in B1['N']['rows']}
gA = {(r['case'].split('-rec')[1].split('-lvl')[0], r['case'].split('-lvl')[1]): r for r in B1['A']['rows']}
acc = [acct('recuperation', f"On N (1,400 kg/s, series): net 269.631 / 423.107 / 557.114 MW at 0.5 / 0.8 / 0.95 at every level, all heat removed, no violation. On A (1,700 kg/s, network): 463.066 / 691.524 / 891.002 at levels 0 and +60 K; at −60 K the 0.95 point falls to 745.301 with 162.118 MW unmet (helium stage 152.431) and `heat_removal_ok` violated, the only violation of the B1 grid. Heater inlet rises with recuperation (A: 431.023 / 505.183 / 569.936 K) toward the lowered helium limit 669.15 K, which is the mechanism. The difference of differences on net, (0.95 − 0.5) at +60 K minus the same at −60 K, is {B1['N']['net_difference_of_differences_MW']:.3f} MW on N and {B1['A']['net_difference_of_differences_MW']:.3f} MW on A; the ranking 0.95 > 0.8 > 0.5 holds at every level on both bases. With turbine efficiency 0.90 the N corner (0.95, −60 K) binds too (36.102 MW unmet, net 515.682) and the N difference of differences becomes {B1['eta0.90']['net_difference_of_differences_MW']:.3f} MW."),
       acct('he_limit', "Acts only where the helium stage is capacity-limited: inert on N at every recuperation and on A at 0.5 and 0.8; at A/0.95 the −60 K shift binds the stage (see `recuperation`). The −60 K shift at N/0.95 binds only under the 0.90 turbine-efficiency assumption. Violations located: `b1-A-rec0.95-lvl-60`, `b1-N-rec0.95-lvl-60-eta0.90` (`heat_removal_ok`)."),
       acct('divertor_limit', "Inert at every point: the divertor stage never binds within ±60 K on either base (its capability exceeds its 375 MW duty throughout)."),
       acct('pbli_limit', "Inert at every point within ±60 K: the PbLi stage never binds on either base in this window (the prior goal's series-order PbLi limit appears at the source-conditioned inputs, not at these bases)."),
       acct('he_flow', f"On N nothing more is removed at any flow (all heat is already removed); under the cubic pump law net falls {B2['net_gain_per_flow_step']['rec0.8-pump0']['2600→3261']:+.3f} then {B2['net_gain_per_flow_step']['rec0.8-pump0']['3261→3900']:+.3f} MW per step at 0.8 (LCOE {B2['lcoe_change_per_flow_step']['rec0.8-pump0']['2600→3261']:+.3f} then {B2['lcoe_change_per_flow_step']['rec0.8-pump0']['3261→3900']:+.3f}), under the fixed law nothing changes; at 3,900 kg/s the helium pump capacity screen (3,261) is violated under both laws. On A where the helium stage binds (0.95, −60 K): fixed law {B2['A_binding']['net_gain_per_flow_step']['pump1']['3359→4000']:+.3f} then {B2['A_binding']['net_gain_per_flow_step']['pump1']['4000→4700']:+.3f} MW net per step with unmet heat {B2['A_binding']['unmet_change_per_flow_step']['pump1']['3359→4000']:+.3f} then {B2['A_binding']['unmet_change_per_flow_step']['pump1']['4000→4700']:+.3f} MW (the stage is limited by the cycle-side inlet temperature, not by primary flow); cubic law {B2['A_binding']['net_gain_per_flow_step']['pump0']['3359→4000']:+.3f} then {B2['A_binding']['net_gain_per_flow_step']['pump0']['4000→4700']:+.3f} MW net with unmet heat {B2['A_binding']['unmet_change_per_flow_step']['pump0']['3359→4000']:+.3f} then {B2['A_binding']['unmet_change_per_flow_step']['pump0']['4000→4700']:+.3f} MW, because 90 % of the pump power is recovered as friction heat into the very stage that cannot remove it; at 4,700 kg/s cubic the helium duty rating (1,500 MW) is also violated (margin −17.057). Violations located: pump screen at N/3,900 (all four cells) and A/4,000–4,700 (all four); `heat_removal_ok` on every A cell; `he_capacity` at A/4,700 cubic."),
       acct('he_pump_mode', "Changes the sign of the flow response: under the cubic proxy more flow costs net (N) or costs net and adds unmet heat (A); under the fixed law flow is free of power cost and the only response is the capacity screen. The two laws bracket a missing pump map."),
       acct('density_amplitude', "Fusion power 1,477–2,427 MW over 4.75–5.75e20 (with hollowness), net 132.275–820.519 MW, external tritium 84.331–138.242 kg/year; no violation up to 5.5e20 in series and 5.0e20 in network at hollowness 0.66; `heat_removal_ok` violated at 5.75e20 (series 149.872 MW unmet; network 114.954) and at 5.5e20 network (45.224) and 5.75e20/0.60 network (26.086). The fuel-processing rating (3e22 atoms/s) keeps a margin of at least 1.363e22 throughout; the compressor margin is constant (227.149, set by cycle flow); the helium duty rating margin falls 751.046 → 359.792 but stays positive."),
       acct('hollowness', "0.60 lowers fusion power by ≈ 10.8 % at 5.0e20 (1,835.451 → 1,636.463 MW) and net by 161 MW; it moves the helium-stage binding beyond the window in series and to 5.75e20 in the network."),
       acct('network_mode', "Inert where all heat is removed (identical channels at every unbound point, prior goal L-006). At 5.5e20/0.66 the network binds first (45.224 MW unmet, net 703.212 against series 735.759); at 5.75e20/0.66 the network removes more (114.954 against 149.872 unmet) and yields more net (820.519 against 795.389): the arrangement ranking reverses between the two amplitudes."),
       acct('turbine_efficiency', "0.90 at the four N corners: net −44.318 MW at 0.5 (both levels) and −9.124 / −41.432 at 0.95 (+60 / −60 K); the (0.95, −60 K) corner becomes bound (36.102 MW unmet) because the hotter exhaust raises the heater inlet.")]
replace(6, '\n'.join(acc))
replace(12, "Single arm, single store, single package identity: executable `f739dbce67699b7adfae7c1adf5599ab7c30e85987caad53e0f8affd9b880ce4`, semantic `78dd23bf4c4a2d431ce8223d973db08e955e6f378175623ced8b976db4231f93`, indicator-input fingerprint equal to the live manifest pin `06e0627c…` (preflight `manifest_currency` pass). No cross-arm correlation is needed: nil, single fingerprint. The two sealed bases carry the same executable fingerprint (checked by `interactions_support.canonical_inputs`).")
st = ver['stores'][0]
replace(13, f"**Outcome: {ver['outcome']}.** `verify.py` sampled all 52 completed cases of the one store (`--sample-size 52`, stratified by verdict combination then filled), compared 364 scalar channels against the package-owned oracle at relative deviation below 1e-9 or the manifest's ten declared absolute classes, and re-derived all 14 verdicts from the oracle's own operands with no mismatch (`results/verification_summary.json`). Worst case named by the summary: `{st['worst_at']['channel'].split('__', 1)[1]}` at `{st['worst_at']['case_id']}`, {st['worst_at']['value']:.3e} MW, inside its 1e-7 MW class. The package tree was git-clean after execution and after verification.\n\n**Not covered.** Values fed identically to both sides (every swept and held input) are not independently verified; the oracle checks the implementation of the model's assumptions, not their scientific qualification; the glue ledger is empty so nothing is harness-supplied; per-point operand values of multi-field outputs are recorded as channels here (this package exports single-field channels), so the B2 pump-electric and B1 heater-inlet readings are stored channels, not oracle-derived columns.")
replace(14, "| Lens | Verdict | Disposition |\n|---|---|---|\n| Compatibility map and choice inventory the axes rest on (fresh reviewer, goal T-001) | FINDINGS, no misclassified row; line cites and one mechanism cite corrected | `work/orchestration/goals/design-space-combinations/evidence/map-review.md` |\n| Control replay of the N base on this identity (coordinator, goal T-002) | bit-identical to the sealed `nominal-calculated` (net 423.107, 14 of 14 satisfied) | `…/evidence/scratch-screens.json` |\n| Pre-execution checkpoint (coordinator, goal C-001.r1) | PASS as a coordinator check; no review trigger met; reused coverage cited; window revision recorded | goal trail |\n| All-point verification against the oracle (executor) | pass, 52 of 52, 364 channels, 14 verdicts | § 13 |\n| Round-1 review of this reading | pending at the round result | goal trail |")
F = [
 (1, 'model', "The heat-source temperature level (all three branch outlet limits shifted ±60 K at unchanged duty and flow) has no effect on any plant-ledger channel where every stage removes all its heat: identical channels at every N point and at every A point below recuperation 0.95. It acts only through a bound stage: at A/0.95/−60 K the helium stage leaves 162.118 MW unremoved and net falls 891.002 → 745.301.", "Result to the goal answer (B1); extends prior L-006 from arrangement to source temperature.", "work/orchestration/goals/design-space-combinations/answer.md"),
 (2, 'model', "The recuperation × source-temperature interaction is a limiting-check change, not a ranking reversal, within ±60 K: `heat_removal_ok` flips only at (0.95, −60 K); the difference of differences on net is 145.701 MW on A and 0.000 on N; 0.95 stays preferred at every level on both bases. The mechanism (heater inlet rising with recuperation toward the lowered helium limit) also predicts the 0.90-turbine-efficiency result, where the N corner binds (36.102 MW); the interaction's presence at the N operating point depends on that assumption, its presence at A does not.", "Result to the goal answer (B1) with the assumption dependence stated.", "work/orchestration/goals/design-space-combinations/answer.md"),
 (3, 'model', "The sign of the helium-flow effect on net depends on the pump-power law: under the cubic proxy more flow costs net on N (−26.888 / −38.742 MW per step at 0.8) and, on the bound A case, adds unmet heat (+104.555 / +160.975 MW) and costs net (−116.004 / −178.296 MW) because 90 % of the pump power is recovered into the stage that cannot remove it, failing the helium duty rating at 4,700 kg/s; under the fixed law flow changes nothing but the pump capacity screen, which fails at +20 % under both laws. More flow never removed more of the bound stage's heat (fixed law: −1.570 / −0.945 MW), because that stage is limited by the cycle-side inlet temperature.", "Result to the goal answer (B2); model-development note: no hydraulic or pump-map model, the friction-recovery path of the proxy is the only mechanism.", "work/orchestration/goals/design-space-combinations/answer.md"),
 (4, 'model', "Over the density window the first check to bind as core output rises is heat removal at the helium stage, never the fuel-processing rating (margin ≥ 1.363e22 atoms/s) nor the compressor (constant margin set by cycle flow); the exchanger arrangement changes where it binds and the net ranking reverses between 5.5e20 (series 735.759 > network 703.212) and 5.75e20 (network 820.519 > series 795.389) at hollowness 0.66; hollowness 0.60 lowers fusion power ≈ 10.8 % and moves the binding out of the window in series.", "Result to the goal answer (B3).", "work/orchestration/goals/design-space-combinations/answer.md"),
 (5, 'process', "The helium, PbLi and divertor pump capacity screens sit at margin 0 at every base by the WI-090 demand-matched convention (capacities selected equal to the flows), so a smallest-normalized-margin reading of the limiting equipment lists them first; the reporting excludes nothing and the reading uses the violated set and the next positive margins.", "Disclosed here and in the reporting module's output.", "exploration/aries_integrated/studies/interactions_reporting.py"),
 (6, 'process', "The r1 oracle scan refused eight B3 points (nonpositive net at 4.0e20 for every hollowness and at hollowness 0.30 for every amplitude) and showed the temperature level inert on N; the windows were fixed by an oracle-only probe and the r1 preparation retained under `preparation-r1/`.", "Recorded in § 11; no native point was spent on a refused window.", "this record § 11"),
 (7, 'model', "The temperature-level scenario holds each branch's duty and primary flow fixed while shifting its outlet limit; no blanket thermal-hydraulic model links the three, so the level is a consistent scenario only as a question about the exchanger stages, not about a redesigned blanket. A blanket model that couples outlet temperature, flow and duty is the missing relationship.", "Declared seam under the brief's no-new-definitions rule; offered to the owner in the goal answer, not opened.", "work/orchestration/goals/design-space-combinations/answer.md"),
]
replace(15, "| Id | Kind | Finding | Disposition | Home |\n|---|---|---|---|---|\n" + '\n'.join(f"| `{SID}#{n}` | {k} | {f} | {d} | {h} |" for n, k, f, d, h in F))
replace(17, "- **Oracle-derived operand columns.** None beyond the stored channels; every reading is a stored channel or a difference of two.\n- **A hydraulic or pump-map model.** The cubic proxy and the fixed law are declared assumptions; the B2 sign result is a property of those two laws.\n- **A blanket thermal-hydraulic model.** The temperature level is a scenario at fixed duty and flow (finding #7).\n- **Confinement or transport qualification.** Density amplitude and hollowness are fixed-hardware source-demand changes (WI-083 limits).\n- **A cost ranking.** The LCOE is tritium-dominated on this package; no case is ranked by LCOE.\n- **A boundary claim.** All axes are sensitivity-framed; violations are located, not bounded.\n- **The B1 interaction at the N operating point independent of the turbine-efficiency assumption.** At 0.93 it is absent, at 0.90 present (finding #2).\n- **Runs of the refused r1 windows.** Eight points were removed after the oracle scan; none executed natively.")
(R / 'record.md').write_text(rec)
# discovery log rows (first sightings)
log = ROOT / 'exploration/aries_integrated/studies/DISCOVERY_LOG.md'
txt = log.read_text()
rows = '\n'.join(f"| 2026-09-26 | `{k}` | `{SID}#{n}` | {f[:220].replace('|','/')}… | {d.replace('|','/')} | {h} |" for n, k, f, d, h in F)
log.write_text(txt.rstrip('\n') + '\n' + rows + '\n')
print('filled; placeholders left:', re.findall(r'<[^>`\n]+>', rec)[:6])
