"""Fill the native study record from retained evidence before the write-once snapshot."""
import json
from pathlib import Path
H=Path(__file__).resolve().parents[1];R=H/'results';read=lambda p:json.loads(p.read_text())
rows=read(R/'interpreted-cases.json');cat=read(R/'predicate-catalog.json')
old=(H/'record.md').read_text();intake=old.split('## 2. Intake\n\n')[1].split('## 3. Objective and result')[0].strip()
sections={}
sections['1. Study header']='- **Study id:** 20260918-computed-tritium-breeding\n- **Package:** stellarator_tea\n- **Date executed:** 2026-09-18.\n- **Executor:** delegated transport/study author under the goal coordinator.\n- **Mode:** execute.\n- **Arms:** arm-native.'
sections['2. Intake']=intake
sections['3. Objective and result']='- **LCOE objective channel:** `stellarator_09__stellaris__lcoe_calc__lcoe`.\n- **LCOE result:** $134.126–156.000/MWh over the supported thickness sensitivity; $144.747/MWh at the 0.80 m reference point.\n\nGreater supported blanket thickness increases computed breeding and represented capital cost. The sampled 0.825 m case clears the numerical breeding screen but newly fails peak field. Every case retains other failed plant screens, so this is no economic optimum or feasible design. [Report](report.md) and [complete points](results/points.csv) retain the results.'
s=['| `constraint_id` | `source_local_identity` | Status | Note |','|---|---|---|---|']
for cid,e in cat.items():
 n=sum(x[cid]=='violated' for x in rows);status='satisfied' if n==0 else ('violated' if n==13 else 'mixed')
 note={'tbr_ok':'Violated at supported0.60–0.80 m and all3 undefined diagnostics; satisfied at sampled0.825–1.00 m. Undefined is not physical deficit.','peak_field_ok':'Violated at sampled supported0.825–1.00 m and unsupported1.05 m; satisfied elsewhere.','reference_conductor_current_ok':'Violated all13; native and oracle agree. No reserve change made.','divertor_heat_ok':'Violated all13; retained unchanged.','wp_fit_ok':'Violated all13; retained unchanged.'}.get(e['source_local_identity'],'Satisfied all13.')
 s.append(f"| `{cid}` | `{e['source_local_identity']}` | {status} | {note} |")
sections['4. Constraint outcomes']='All 20 executing predicates are retained, including unrelated failures. The complete pointwise map is in [native cases](results/native-cases.json).\n\n'+'\n'.join(s)
sections['5. Framing']='**As proposed at intake.**\n\n| Axis | Framing proposed | Why |\n|---|---|---|\n| blanket__blanket_t | sensitivity | Supported build response and native cost/adequacy consequences. |\n| plasma__R | sensitivity | One unsupported-domain diagnostic. |\n\n**As judged after the run.**\n\n| Axis | Framing judged | Changed? | Why |\n|---|---|---|---|\n| blanket__blanket_t | sensitivity | no | Observed breeding/cost/field tradeoff; no whole-plant feasible point or boundary search. |\n| plasma__R | sensitivity | no | Changed radius makes breeding undefined; no physical radius response inferred. |'
sections['6. Per-axis account']='#### blanket__blanket_t — feasible structure (search framing)\n\n**Applies:** Not applicable; this axis is sensitivity-framed.\n\n#### blanket__blanket_t — observed response (sensitivity framing)\n\n**Applies:** Yes. Mean breeding and cost rise across the supported samples. The numerical breeding screen fails at sampled0.60–0.80 m and passes at sampled0.825–1.00 m; peak field fails at the latter samples. Divertor heat, reference conductor current and winding-pack fit fail throughout. Both unsupported thicknesses have undefined breeding; the1.05 m diagnostic also fails peak field. No continuous boundary or optimum is claimed.\n\n#### plasma__R — feasible structure (search framing)\n\n**Applies:** Not applicable; this axis is sensitivity-framed.\n\n#### plasma__R — observed response (sensitivity framing)\n\n**Applies:** Yes. At R=12.71 m and thickness0.80 m, breeding is undefined and the TBR predicate fails closed. Divertor heat, reference conductor current and winding-pack fit remain violated. Unrelated outputs remain available. This one diagnostic supports no physical breeding response or radius boundary claim.'
sections['7. Axis groups']='| Axis | Entry key | Provenance | Note |\n|---|---|---|---|\n| blanket__blanket_t | `stellarator_09__stellaris__blanket__blanket_t` | fan_out | Complete public authored thickness key. |\n| plasma__R | `stellarator_09__stellaris__plasma__R` | fan_out | Complete public authored radius key. |\n\n[Declaration](axes.json). No ties or retired held-TBR key are used.'
sections['8. Indicators and rulings']='| Axis | Indicator | Ruling | Note |\n|---|---|---|---|\n| blanket__blanket_t | constraints_reachable | Not applicable: no no-constraint-response result. | Swept; declared graph paths exist. |\n| plasma__R | constraints_reachable | Not applicable: no no-constraint-response result. | One diagnostic; declared graph paths exist. |\n\nBoth groups were traced without a subset and have no sibling warnings. [Indicators](indicators.json) establish possible paths, not observed constraint response. Monotonicity, same-quantity identity across different names and intra-module operand dependency are not derivable. No no-constraint-response model-gap finding is owed because neither axis has that result.'
sections['9. Preflight results']='| Gate | Outcome | Detail |\n|---|---|---|\n| Declared-group key validation | pass | Two complete keys across two groups. |\n| Suffix-sibling scan | pass | No undeclared suffix siblings. |\n| Baseline gate | pass | `results/baseline_result.json`; headline relative deviation0, all20 pinned verdicts match. |\n| Executable identity | pass | `results/package_identity.json`; sealed bytes match, no adapter. |\n| Manifest currency | pass | Both package fingerprints match. |\n| Package cleanliness | pass | Before and after native execution. |\n\n[Full gates](results/preflight_results.json); [post-run check](results/post-run-clean.json). No gate was skipped.'
sections['10. Execution route and why']='- **Route:** study-local direct API using stock `StudyRunner` and `PreparedListStrategy`.\n- **Why this route:** the exact released baseline and all gates passed before the fixed finite list executed. It preserves supported sensitivities and undefined diagnostics in one native store.\n\nGlue ledger: none; no adapter or harness-supplied model quantity. Launcher import setup only exposes the pinned teax runtime. The harness copies native outputs and masks undefined breeding-derived carriers for display, retaining their raw values. [Environment receipt](results/execution-environment.json) records the existing serializer warning; no execution phase refused or failed.'
sections['11. Study definition and window provenance']='The window is engineered from the upstream validated thickness domain, with interior sensitivity samples and three explicit unsupported diagnostics. After the released baseline and gates, the independent oracle evaluated all13 proposed cases and confirmed expected applicability. The full list was then retained without exclusions in `preparation/proposals.json`; [window check](reviews/window-selection.md) records that decision. The study cannot establish a continuous feasible boundary or optimum. No model, allowance or limit was tuned to restore a passing point.'
sections['12. Cross-fingerprint correlation and what it means']='Single fingerprint; no cross-arm correlation is needed. Historical studies are not rewritten or treated as evaluations of this package.'
sections['13. Verification']='All mapped software values and all authored predicate outcomes agree at every case. The generic verifier passes without boundary exceptions. [All-point verification](results/oracle-all-points.json) and [generic verification](results/verification_summary.json) retain the evidence.\n\nAll261 native numeric outputs are retained;16 lie outside the245-channel oracle map. Shared transport-table data are identical by construction and receive no independent physical-verification credit. The copied physical reviews support the bounded conceptual scenario and disclose approximate benchmark reconstruction, material/source sensitivities and absence of actual stellarator qualification.'
sections['14. Review outcomes']='| Lens | Verdict | Disposition |\n|---|---|---|\n| Independent physical/data/interface release | PASS for conditional conceptual integration | [Copied review](reviews/table-release-review.md) applies to the unchanged frozen response and scenario, with benchmark/material/geometry limitations. |\n| Native integration | CANDIDATE; all10 gates pass | [Return](preparation/integration-return.json) and [coordinator release](preparation/execution-release.json) pin the executed candidate. |\n| Framing and window | Executor check passed under coordinator delegation | All proposed cases retained after oracle scan; no optimization or feasible-boundary claim. |\n| Final independent study/goal review | Pending coordinator review | This record is executor-authored; no independent final approval is asserted. |'
findings=[('1','model','Thicker supported breeder clears the sampled breeding screen while incurring peak-field failure and higher cost; all cases retain other failures.','Conditional sampled tradeoff, no whole-plant feasible point.','computed-tritium-breeding goal'),('2','model','Native CAS22 blanket volume aggregates full-shell first wall, breeder and reflector; transport removes3% of breeder/reflector/shield.','Retain quantified inventory/cost convention; no identical-inventory or installed-cost claim.','computed-tritium-breeding goal'),('3','model','Unsupported thickness or fixed-geometry change yields undefined breeding while unrelated outputs and independent fuel-account terms remain available.','Keep native failed TBR screen and raw carriers; null only derived display fields.','computed-tritium-breeding goal')]
sections['15. Findings']='| Id | Kind | Finding | Disposition | Home |\n|---|---|---|---|---|\n'+'\n'.join(f'| {H.name}#{n} | {kind} | {f} | {d} | {home} |' for n,kind,f,d,home in findings)
sections['16. Snapshot']='Pending final evidence freeze; written once after the record and tool copies are complete.'
sections['17. What this record does not contain']='No whole-plant feasible design, continuous feasible boundary, economic optimum, actual stellarator qualification or full physical uncertainty bound is supplied. Large nuclear-data/statepoint/source-bank binaries are absent; compact transport evidence and its original hashes are retained. The copied transport report’s original plot is not copied, but its numerical tables are present. The generated-study plot is retained separately. This record contains no post-execution model repair, independent final study reading or coordinator commit; those are coordinator-owned next steps.'
(H/'record.md').write_text('\n\n'.join('## '+k+'\n\n'+v for k,v in sections.items())+'\n')
log=H.parent/'DISCOVERY_LOG.md';text=log.read_text();assert H.name+'#1' not in text
with log.open('a') as f:
 for n,kind,finding,disposition,home in findings:f.write(f'| 2026-09-18 | {kind} | `{H.name}#{n}` | {finding} | {disposition} | `exploration/stellarator_e2e/studies/{H.name}/report.md` |\n')
print('17-section executor record and3 first-sighting discoveries written')
