"""Fill native record arguments from retained results; no evaluation."""
import json
from pathlib import Path
H=Path(__file__).resolve().parents[1];R=H/'results';read=lambda p:json.loads(p.read_text())
a=read(R/'analysis.json');n=read(R/'neighborhood-summary.json');v=read(R/'oracle-all-points.json');counts=read(R/'campaign-counts.json');groups=read(H/'axes.json')['groups'];pre=read(R/'preflight_results.json');generic=read(R/'generic-verification-refusal.json')
heads=[line for line in Path('.claude/skills/run-study/record-template.md').read_text().splitlines() if line.startswith('## ')][:17]
sections={}
sections[1]=f'Study id: {H.name}. Package: stellarator_tea. Date: 2026-09-17. Executor: /root. Mode: execute. Single arm: arm-native; controls and scenario families share the unchanged executable.'
sections[2]='[OWNER-VERBATIM] “Can the current Stellaris-based model produce a verified neighborhood of designs that passes its implemented engineering screens under defensible assumptions, or can we explain which limits prevent that within a clearly declared search?”\n\n[AGENT, adopted for this run] The owner authorized the campaign scope, caps and reserved gates preserved in preparation/goal-at-authority.md. Execution choices and scientific conclusions remain agent-originated. protocol.md declares axes/bounds/held assumptions before evaluation. No expectation about ARIES is evidence.'
q=n['anchor']['quantities'];sections[3]=f"[AGENT] The reported objective channel is stellarator_09__stellaris__lcoe_calc__lcoe. Anchor conditional LCOE is ${q['LCOE_dollars_MWh']:.8g}/MWh; comparison-form LCOE is separately retained. Selection maximizes engineering margin, not cost. {a['overall']['valid_account_combined_passes']} of {a['overall']['cases']} selected native cases pass all predicates with a valid power account. Results are in report.md and results/analysis.json; incomplete installed costs prevent an economic optimum claim."
sections[4]='| constraint_id | source_local_identity | Status counts | Note |\n|---|---|---|---|\n'+'\n'.join(f"|`{cid}`|`{x['source_local_identity']}`|{x['counts']}|Raw native verdicts; no tolerance changes|" for cid,x in a['predicate_outcomes'].items())
sections[5]='[AGENT] At intake, the eight continuous/integer design axes were search-framed and inventory was a discrete sensitivity for attribution. Judged framing remains the same: native verdict structure exists on the joint domain, while held inventory scenarios preserve raw boundary behavior. Conservative reachability is not proof of independent response. No source-qualified continuous feasibility region or economic optimum is inferred.\n\nThe native feasible fraction is '+str(a['overall']['valid_account_combined_passes']/a['overall']['cases'])+'. This is the policy H1 numeric metric for the selected native set; it is selection-biased. The original space-filling screen found only five passes among512 candidates, with refusals retained, and cannot support a large feasible-volume claim. H2: omissions and qualification gaps remain declared seams, with no new inequality or repair authorized. H3: no new solve or cross-module cycle was introduced.'
per=[]
for g in groups:
 name=g['axis'];inventory='inventory_multiplier' in name
 per.extend([f'#### {name} — feasible structure (search framing)',f"**Applies:** {'not applicable — discrete sensitivity scenario' if inventory else 'yes' }.", 'The exact individual/combined neighborhood results and signed margins are retained in results/neighborhood-summary.json; joint failures and fixed-slice boundaries are in results/analysis.json and map-data.csv. This finite search does not establish a global boundary.' if not inventory else 'No continuous inventory boundary is claimed.',f'#### {name} — observed response (sensitivity framing)',f"**Applies:** {'yes' if inventory else 'not applicable — this axis is search-framed'}.", 'Matched inventory1.0/1.01 controls preserve cost/dimension/current consequences and near-zero numerical exceptions. No tolerance or material law is changed.' if inventory else 'The search-framed account above applies.'])
sections[6]='\n\n'.join(per)
sections[7]='| Axis | Entry key | Provenance | Note |\n|---|---|---|---|\n'+'\n'.join(f"|{g['axis']}|`{k['key']}`|{k['provenance']}|Complete public design-attribute entry; downstream bindings retained|" for g in groups for k in g['keys'])+'\n\npreparation/axis-contract-check.json checks the original contract and pipeline. No ties or computed axes.'
sections[8]='All nine groups report constraints_reachable; no no_constraint_response owner ruling is needed. Transverse accommodation reaches only fit and no objective, so its missing cost/structural resistance limits interpretation. Loops retain hydraulic/power resistance but incomplete installed cost. Peak density/temperature remain authored inputs with internal ash/confinement closure.\n\nNot derivable: monotonicity or sign, same-quantity identity across different key names, or intra-module operand dependency. Reachability is only a possible path. Native data, not these indicators, establish the observed responses.'
sections[9]='Fresh exact manifest baseline and all preflight gates pass; original receipts are results/package_identity.json, baseline_result.json and preflight_results.json. Package cleanliness is checked before and after candidate execution. Two prior standalone launch failures occurred before model evaluation and are retained in baseline.log/baseline-retry1.log; baseline-retry2.log records the successful documented import-path correction. All three runtime provenance tests passed. No environment was installed or synchronized. Integration regeneration is not rerun: preparation/continuity.json establishes unchanged audited sources/package/oracle/route/manifest from the pinned study; the copied integration return and its limitations are reused.'
sections[10]='Study-local direct API: stock StudyRunner plus PreparedListStrategy through the unchanged package-owned study_route.py. The exact baseline exercised this route before preflight and selection. Coordinated input blocks require this route. Glue ledger: none; no adapter or outer physics solver. execution/reproduce.sh documents the retained launcher/import prerequisites. Two importer failures consumed the mechanical retry cap without model calls.'
sections[11]='The initial domain was engineered before screening, as declared in protocol.md.512 seeded Latin-hypercube geometry/current/density/temperature coordinates at fixed accommodation and loops found five oracle passes; four controls provided attribution. The retained maximum-minimum variable-margin choice selected the local anchor. Finite refinement candidates and an R/current lattice were deposited before evaluation. The original bound set did not grow. Exact candidates, selection rule, seed and local map values are retained in preparation/. Domain refusals and invalid accounts are not discarded or counted as physical failures. No external solve or adaptive native runner was used.'
sections[12]='Single unchanged executable and semantic fingerprint. No cross-fingerprint correlation is needed. Exact r2 controls agree byte-for-byte in242 scalar values and20 verdicts; preparation/r2-control-provenance.json pins their original evidence. Source-conditioned Table5 geometry/field has no independent prediction credit.'
sections[13]=f"All {v['scalar_comparisons']} mapped scalar comparisons pass the retained relative/absolute1e-9 comparison. {len(v['strict_relative_misses'])} strict-relative near-zero differences remain visible; all are reviewed separately. Of {v['predicate_comparisons']} independent oracle verdict comparisons, {len(v['boundary_exceptions'])} exact-current-boundary sign exceptions remain raw. All {v['native_operand_checks']} native-operand reconstructions agree. The generic stratified verifier reports {generic['outcome']}; its unmodified receipt is retained and is not relabeled a strict pass. The all-point check scopes every disagreement in results/oracle-all-points.json. No tolerance, predicate or native classification is changed.\n\nAll242 native numeric channels are retained, but16 are outside the oracle map (identities in oracle-all-points.json). Native-operand reconstruction checks classifier arithmetic, not independent scientific equations. Oracle agreement checks implementation, not physical source validity. Existing static L2/L6, integration read-set and broad-consumer limitations remain inherited. Exact r2 reproduction is numerical attribution, not source ignition reproduction."
sections[14]='Pre-execution independent PASS: reviews/preexecution-check.md. Coordinator checks: full native/oracle comparisons, native-operand predicates, store joins and plot/data exports. Fresh result/plot/custody review is commissioned with original evidence under the goal; its final verdict is appended as a later review record so frozen evidence stays immutable. No independent post-execution PASS is claimed here before that review.'
findings=[('model','Sampled screen-passing neighborhood and fixed-slice tradeoff are retained with failed neighbors.','declared seam — bounded result; no certified continuum or buildability claim','report.md'),('model','Multiplier1.0 retains signed near-zero current-boundary disagreements; reserve1.01 buys inventory and margin.','declared seam — preserve raw failures, dimensions and price; no tolerance relaxation','results/oracle-all-points.json'),('model','Geometry, conductor, cooling, achieved breeding and omitted costs limit engineering/economic interpretation.','declared seam — requirements quantified; hardware qualification and installed prices remain open','report.md'),('model','Oracle domain refusals and native invalid power accounts remain distinct from valid failed screens.','declared seam — retain all results and finite-domain scope','results/oracle-scan.json'),('process','Two standalone import-path failures used the retry cap before any model evaluation.','declared seam — documented launcher paths; no runtime replacement','execution/reproduce.sh')]
sections[15]='| Id | Kind | Finding | Disposition | Home |\n|---|---|---|---|---|\n'+'\n'.join(f'| `{H.name}#{i}` | {kind} | {finding} | {disposition} | `{home}` |' for i,(kind,finding,disposition,home) in enumerate(findings,1))
sections[16]='snapshot.json is resolved once immediately before scoped publication; its SHA256 will be inserted after creation. Schema version1. No snapshot field is inferred from a live file by a later reader.'
sections[17]='No full generated executable or licensed environment is embedded in this record; the unchanged r2 archive and retained runtime are reproduction prerequisites. No new source extraction, magnetic equilibrium, neutronics, conductor qualification, installed equipment quote or global-search proof is present. Every failed/invalid evaluated point and oracle refusal is retained. The baseline has its own native store; the selected candidate arm names the main store. Independent final review and executor synthesis are later append-only records.'
(H/'record.md').write_text('# Pre-reveal feasible neighborhood — native study record\n\n'+'\n\n'.join(h+'\n\n'+sections[i] for i,h in enumerate(heads,1))+'\n')
log=H.parent/'DISCOVERY_LOG.md';text=log.read_text();assert f'`{H.name}#1`' not in text
with log.open('a') as f:
 for i,(kind,finding,disposition,home) in enumerate(findings,1):f.write(f'|2026-09-17|{kind}|`{H.name}#{i}`|{finding}|{disposition}|`{H}/{home}`|\n')
print('Filled17 native sections and appended5 first-sighting findings')
