"""Complete executor narrative from retained native result summary."""
import json,re
from pathlib import Path
R=Path(__file__).resolve().parent
read=lambda p:json.loads((R/p).read_text())
a=read('results/cost-analysis.json'); rows=a['cases'];by={r['case']:r for r in rows}; axes=read('axis-plan.json')['axes'];v=read('results/verification_summary.json'); assert v['outcome']=='pass'
p=R/'record.md';s=p.read_text()
def section(n,body):
 global s
 pattern=rf'(## {n}\. [^\n]+\n).*?(?=\n## {n+1}\. |\Z)'
 s=re.sub(pattern,lambda m:m.group(1)+'\n'+body.strip()+'\n',s,flags=re.S)
section(1,f'Study id: `{R.name}`. Package: `aries_integrated`. Executor: study worker, 2026-09-22. Single arm answering conditional accounting uncertainty. Executed at `bd9b9aec5fabda5e9a14d53df84f108d52f7f183`: 113 proposed points, 113 completed native attempts. Execution and all-point verification are complete; coordinator freeze and independent review remain pending.')
section(3,'No LCOE channel or optimization objective is requested. Native overnight capital spans USD2004 1,623,355,845–13,331,716,800 among the sampled assumed-baseline scenarios. Combined no-credit annual operating expense is USD2004 893,907,253.092–11,959,761,809.990/year; the separate supplied-100 kg/year corners give 36,005,723.707–1,959,761,809.990/year. These are engineered scenario corners, not calibrated bounds or a probability envelope. Initial, annual and replacement amounts are separate. See `report.md`, `cost-results.md` and `results/cost-analysis.json` for contribution tables, finite changes and exact stored outputs.')
cat=read('results/constraint_catalog.json')
table=['Every exact predicate is retained. All 110 conditional baseline-family points satisfy every scoped check. Only the three inherited source controls fail: all three heat-removal checks; literal Raffray also fails the balance check. Their net outputs are incomplete/constraint-failing diagnostics, not usable power alternatives.','', '| Constraint id | Local identity | Status counts |','| --- | --- | --- |']
for k,counts in a['constraints'].items():table.append(f"| `{k}` | {cat[k]['source_local_identity']} | {counts} |")
section(4,'\n'.join(table))
section(5,'All 53 axes were proposed as sensitivity and remain sensitivity after execution; none changed framing. The 48 no-constraint-response groups retain their pre-execution owner-authorized rulings and missing-response findings. Observed accounting movement, equal net output or a satisfied scalar check supplies no scientific qualification, probability bound or optimum.')
parts=[]
for axis in axes:
 name=axis['axis'];selected=[r for r in rows if r['axis']==name]
 if name=='purchase_mode':selected=[by[n] for n in ('fixed-budget-nominal','adequate-area-mode-0','adequate-area-mode-1')]
 if name=='adequate_he_area':selected=[by[n] for n in ('adequate-area-mode-0','adequate-area-mode-1')]
 parts += [f'#### {name} — feasible structure (search framing)','','**Applies:** not applicable — this axis is sensitivity-framed.','',f'#### {name} — observed response (sensitivity framing)','','**Applies:** yes. '+axis['missing_response']+' No boundary or optimum claim is made. Every listed case satisfies all scoped checks; net power remains 423.10679410931664 MW.','']
 if name=='supplied_recovery':parts += [axis['response_limit']+' The declared window is 0–200 kg/year; baseline supplies the zero endpoint and 100 is an explicit midpoint.','']
 parts+=['| Case | Δ overnight USD2004 | Δ annual operating USD2004/year | Δ lifetime replacement USD2004 |','| --- | ---: | ---: | ---: |']
 for row in selected:
  d=row['delta_from_baseline'];parts.append(f"| {row['case']} | {d['overnight_USD2004']:.12g} | {d['annual_operating_USD2004']:.12g} | {d['lifetime_replacement_USD2004']:.12g} |")
 parts+=['']
section(6,'\n'.join(parts))
section(10,'The unchanged study-local direct-API route uses the native loader, prepared evaluator, prepared-list strategy, StudyRunner, store lease and query lifecycle. Glue ledger: none; the harness supplies no physical or cost arithmetic. The new baseline/preflight remains under `preparation/` and is copied to `results/integration/`; reused CANDIDATE files have separate provenance.\n\nThe native runner completed all 113 points once. The wrapper then rejected three numerically identical mode inputs because it compared JSON strings after the existing float-normalization contract. First export recovery stopped on a transient SQLite sidecar hash check. The second, final mechanical recovery read a disposable copy through native StudyQuery, matched every full map numerically without tolerance, and exported original evidence. It checked original persistent database/artifact hashes unchanged. No evaluator reran, no proposal changed, and no global route, oracle or package changed. Two mechanical recoveries were counted conservatively against the retry cap. `results/export-failures.txt`, diagnosis, pre-recovery content check and recovery proof preserve the evidence. Historical byte parity before the first recovery is not claimed because no such prior digest was saved; content/evidence checks are retained. See `replay.md` for the safe replay path.')
section(13,'Native verification passed ALL 113 rows with 278 scalar channels and 14 exact predicates each: 31,414 scalar comparisons and 1,582 predicate comparisons. No verdict mismatches. The inherited relative 1e-9 rule and explicit 1e-7 MW residual tolerance remain unchanged. The displayed worst relative residual ratio is near-zero denominator behavior, accepted only through the declared dimensional absolute tolerance; no monetary tolerance was relaxed. See `results/verification_summary.json`.\n\nExact proposal coverage, 113 completed attempts, per-row native evidence digests and export normalization are retained in the recovery proof. Only the three mode scenario integers changed JSON representation to typed floats; numerical values and the 411-field maps are unchanged. The prior frozen thermal record and generated package remain untouched.')
section(14,'Independent Round1 PASS is copied in `prerequisite/thermal-study-review.md`. Coordinator accepted and committed this preparation at bd9b9aec, then released T008. Coordinator authorized the two recorded mechanical export recoveries; no evaluation retry occurred. Completed record awaits coordinator freeze and independent cost-study review.')
new=[('model','T price and selected stock dominate the tested one-factor overnight changes; price factors and capital fractions retain finite assumed-window meaning.','Retain assumption ranking; no market-calibrated range.','cost-results.md'),('model','No-credit annual expense is dominated by supplied T price and throughput; independent100kg/year recovery changes baseline annual expense from3.215100713B to0.215100713B USD2004/year.','Carry separate supply boundaries and missing incremental recovery-cost/qualification law.','report.md'),('model','Adequate He area75000m2 gives UA75MW/K in either mode; selected pricing raises overnight43.4526465M while fixed-budget pricing gives no capital response.','Expose fixed-budget nonresponse; no purchased-capability optimum.','cost-results.md'),('model','Replacement assumptions change discrete event counts and separate event/lifetime costs; reserve is an alternative convention.','Keep scheduled replacements separate from annual operations and reserve.','report.md'),('process','Original wrapper export used JSON string equality across integer-to-float mode normalization; two mechanical export recoveries retained original113 native evaluations.','Preserve original evidence and disposable-copy export proof; no global route modification in this study.','results/export-recovery-proof.json'),('model','All110 conditional cases preserve423.106794MW and pass scoped checks; three source controls retain failures and scientific support remainszero.','Preserve thermal prerequisite and scientific limits in financial handoff.','report.md')]
f=read('preparation-findings.json')['findings']
for n,(kind,finding,disp,home) in enumerate(new,54):f.append(dict(id=R.name+'#'+str(n),kind=kind,finding=finding,disposition=disp,home=home))
(R/'findings.json').write_text(json.dumps({'findings':f},indent=2)+'\n')
t=['| Id | Kind | Finding | Disposition | Home |','| --- | --- | --- | --- | --- |']
for x in f:t.append(f"| {x['id']} | {x['kind']} | {x.get('axis','')+': ' if x.get('axis') else ''}{x['finding']} | {x['disposition']} | {x['home']} |")
section(15,'\n'.join(t))
section(16,'Pending coordinator snapshot, archive and integrity check. Worker has completed all record/source writes and performs no freeze or commit.')
section(17,'No market calibration, inflation conversion, financing/discounting, LCOE, sales-price scenario or economic optimum is supplied. The ranges cover discrete engineered assumptions only. Recovery lacks an incremental cost/qualification law at fixed installed scope. Positive export leaves the import-tariff branch unexercised. Scientific field/conductor, breeding, deposition, hydraulics, materials and machine-map qualification remain unsupported. Source-conditioned failing net outputs are not usable alternatives. Coordinator freeze and independent completed-study review remain pending.')
p.write_text(s)
print('record completed; findings',len(f))
