"""Render the native17-section record from retained study evidence, before freeze."""
import json,hashlib
from pathlib import Path
from collections import Counter
H=Path(__file__).resolve().parents[1];R=H/'results';P='stellarator_09__stellaris__'
read=lambda p:json.loads(p.read_text())
a=read(R/'analysis.json'); rows=read(R/'native-cases.json');cat=read(R/'predicate-catalog.json'); axes=read(H/'axes.json')['groups'];props=read(H/'preparation/proposals.json');defaults=read(H/'preparation/resolved-defaults.json');v=read(R/'oracle-all-points.json');pre=read(R/'preflight_results.json')
search={'plasma__R','plasma__a','magnet__coil__I_coil','magnet__coil__coil_t','magnet__casing__interior_y'}
def table(head,rs):return '\n'.join(['| '+' | '.join(head)+' |','| '+' | '.join(['---']*len(head))+' |']+['| '+' | '.join(map(str,r))+' |' for r in rs])
parts=[]
def sec(n,title,text):parts.append(f'## {n}. {title}\n\n{text}\n')
sec(1,'Study header',f'**Study id:** {H.name}. **Package:** stellarator_tea. **Date executed:** 2026-09-15 (local). **Executor:** goal coordinator. **Mode:** execute. **Arms:** arm-native.')
sec(2,'Intake','Owner goal and scope are retained verbatim in preparation/owner-study-intake.txt.\n\n> Can a magnet carry the required current at the selected operating margin, fit inside an explicitly allocated casing, and satisfy the existing plant constraints under one consistent set of construction and performance assumptions?\n\n[AGENT] Protocol.md declares allocation-first native sizing, held criteria, staged bounds, scenario separation and limits. Runtime arithmetic lives in the native model; the harness supplies prepared independent inputs only.')
best=a['cheapest_default_all20'];besttext=(f"Cheapest sampled default-performance all20 case: {best['proposal_id']}, ${best['lcoe']:.6f}/MWh." if best else 'No sampled default-performance case satisfies all20 predicates; there is no cheapest default feasible choice.')
sec(3,'Objective and result',f'**LCOE channel:** `{P}lcoe_calc__lcoe`. {besttext} Historical30T and enhanced-performance controls are excluded from that ranking. Full priced quantities and all cases are in results/analysis.json. Manufacturing remainder and mixed price bases remain unresolved. Finite samples imply no global optimum or global infeasibility.')
sec(4,'Constraint outcomes',table(['constraint_id','source_local_identity','Status','Count/locations'],[(cid,e['source_local_identity'],'satisfied / violated' if any(r['verdicts'][cid]=='violated' for r in rows) else 'satisfied',f"{sum(r['verdicts'][cid]=='satisfied' for r in rows)}/{len(rows)} satisfied; all point locations in native-cases.json") for cid,e in cat.items()])+ '\n\nCurrent, fit, other18 and all20 outcomes are reported separately in analysis.json. Domain refusals in initial-oracle-scan.json and final-selection.json have no inferred predicate verdict. Exact-boundary native/oracle sign disagreement remains separately in exact-boundary-diagnostic.json.')
fr=[(g['axis'],'search' if g['axis'] in search else 'sensitivity','Physical geometry/current/allocation choice' if g['axis'] in search else 'Held historical control, inventory mode/reserve or separately labeled performance/shape scenario') for g in axes]
sec(5,'Framing','**As proposed:**\n\n'+table(['Axis','Framing','Reason'],fr)+'\n\n**As judged:**\n\n'+table(['Axis','Framing','Changed','Reason'],[(x,y,'no','Finite observed response retained; no continuous-boundary or qualification claim') for x,y,_ in fr]))
accounts=[]
for g in axes:
 axis=g['axis'];key=g['keys'][0]['key'];vals=sorted({r['inputs'].get(key,defaults[key]) for r in rows});sc=axis in search
 response=[]
 for value in vals:
  subset=[r for r in a['cases'] if r['inputs'].get(key,defaults[key])==value]
  response.append((value,len(subset),sum(r['current_satisfied'] for r in subset),sum(r['fit_satisfied'] for r in subset),sum(r['all20_satisfied'] for r in subset),f"{min(r['lcoe'] for r in subset):.3f}–{max(r['lcoe'] for r in subset):.3f}"))
 accounts.append(f"### {axis}\n\n**Feasible structure applies:** {'yes' if sc else 'not applicable: sensitivity-framed'}. "+('The prepared sample and endpoint results locate passing/failing coordinates, not a continuous boundary. ' if sc else '')+f"Observed values: {vals}.\n\n**Observed response applies:** {'not applicable: search-framed' if sc else 'yes'}. "+('Paired scenario quantities and verdict locations are in analysis.json; no boundary claim is made.' if not sc else 'Per-point responses remain in native-cases.json.')+'\n\n'+table(['Value','Cases','Current passes','Fit passes','All 20 passes','LCOE range, $/MWh'],response)+'\n\nThese aggregates mix other coordinates and historical controls; they are not isolated causal effects or default-only feasibility counts. See report.md for the separate default cohort and paired sensitivities.')
sec(6,'Per-axis account','\n\n'.join(accounts))
sec(7,'Axis groups',table(['Axis','Qualified entry key','Provenance'],[(g['axis'],x['key'],x['provenance']) for g in axes for x in g['keys']])+'\n\nComplete public attribute groups, no new physical-identity ties. Inherited historical controls that stay constant are retained in declarations; they are not newly relaxed acceptance axes.')
sec(8,'Indicators and rulings',table(['Axis','Indicator','Ruling'],[(g['axis'],'constraints_reachable','Owner delegated routine engineering/scenario choices; framing per §5') for g in axes])+'\n\nNo proposed group reports no_constraint_response. Indicators do not establish monotonicity, physical identity across different keys, or intra-module operand dependency. constraints_reachable means a possible path only; unresisted would be an agent judgment. Missing shape/cavity physics remains a finding despite conservative reachability.')
sec(9,'Preflight results','All native gates passed; results/preflight_results.json retains each outcome and actual command provenance. Identity and baseline use package_identity.json and baseline_result.json. Package-clean evidence exists before/after execution. Integration retains the inherited assert_read_set_covered omission, with no substitute coverage claimed.\n\n'+table(['Gate','Outcome','Detail'],[(g.get('gate',g.get('name','gate')),g.get('outcome',g.get('status')),g.get('detail','see JSON')) for g in pre['gates']]))
sec(10,'Execution route and why','Study-local direct-API StudyRunner plus PreparedListStrategy on the stock strict loader. Coordinated allocation configurations and staged selected sensitivities need a prepared list. The baseline exercised this route before preflight. Every cohort point goes through native lifecycle and complete scalar publication. **Glue ledger: none.** No caller arithmetic supplies model outputs, no outer sizing solve, and no adaptive native search.')
sec(11,'Study definition and window provenance','The engineered initial scan and retained refusal coordinates are in initial-oracle-scan.json. final-selection.json and reviews/window-selection.md explain refinements, separate sensitivities and the fixed native cohort. Endpoint diagnostics in edge-scan.json record caught/uncaught/unsupported edges from the selected anchor. Bounds are engineering assumptions supported by source-anchored geometry and existing domain guards, not proof of available space or physical feasibility limits. Required pack sizes motivated independently declared allocation ranges. A wider search could find additional designs or lower sampled cost; it cannot establish missing angle/construction/3D/structural/manufacturing evidence.')
sec(12,'Cross-fingerprint correlation and what it means','Single executed fingerprint; no cross-arm correlation is needed. results/entering-all-points.json evaluates the frozen entering independent oracle at matched coordinates, and comparison-entering.json attributes changes. This is not older-native reexecution. Mode0 preservation and mode1 physical changes are separated; historical studies remain unchanged. All twenty predicate definitions are identical.')
sec(13,'Verification',f"All-point comparison: {v['scalar_comparisons']} scalar and {v['predicate_comparisons']} independently derived predicate comparisons; outcome {v['outcome']}. Generic stratified verification is retained in verification_summary.json. sizing-residuals.json reports actual count/area/current closure; allocation precedes field so no numerical iteration or convergence failure exists in this model. Exact-boundary diagnostic disagreement is retained without relaxing acceptance. Native-store joins and every artifact digest are checked. Unmapped older channels are listed explicitly in oracle-all-points.json. Agreement certifies the stated computation, not measured conductor capability or unmodeled geometry.")
sec(14,'Review outcomes','Independent source/math/interface, oracle/protocol and coupled implementation reviews are copied into preparation/ and reviews/. Coordinator window and release checks reuse that coverage. Final frozen-study/goal assurance is commissioned externally after this executor freeze and will be joined in the goal trail. The executor does not self-certify independent study review.')
findings=[('Current-driven inventory','Native minimum current sizing consistently drives pack, procurement and capacity; exact current closure is conditional consistency.'),('Default joint feasibility',besttext),('Accommodation and missing physics','Required cavity is compared with declared space; casing strength/thermal geometry, pack self-field and full3D interference remain unqualified.'),('Performance and construction','Material/orientation/retention scenarios and required gain thresholds are conditional; no exact construction or local angle qualification.'),('Cost completeness','Priced quantities respond to inventory/geometry, but manufacturing remainder, supplier premiums and mixed-year price bases remain unresolved.'),('Numerical boundary and refusals','Exact multiplier1 native/oracle current signs differ at roundoff; diagnostic retained separately. Unsupported-field proposals carry no physical feasibility verdict.'),('Finite search limits','Finite engineered sample and caught/uncaught endpoints establish no global infeasibility or optimum; H1 assessed on the default cohort in report.md.')]
sec(15,'Findings',table(['Id','Kind','Finding','Disposition','Home'],[(f'`{H.name}#{i}`','model',title+': '+body,'Proposed model extension / declared seam; goal review owns acceptance','work/orchestration/goals/joint-magnet-sizing-feasibility/goal.md') for i,(title,body) in enumerate(findings,1)]))
snap=H/'snapshot.json'; digest=hashlib.sha256(snap.read_bytes()).hexdigest() if snap.exists() else 'resolved by final freeze before commit'
sec(16,'Snapshot',f'File: snapshot.json. SHA256: {digest}. Schema version1. It retains resolved lineage, windows, tools, artifacts and native store compatibility.')
sec(17,'What this record does not contain','No independently qualified tape/cable product, local field-angle map, detailed support/casing certification,3D assembly verification or complete factory quote. Frozen entering oracle is retained, but the older native runtime was not reexecuted. Final fresh assurance lives in the goal evidence after this executor freeze. Source witness excerpts are retained; complete original source PDFs and full generated runtime distribution are not duplicated.')
(H/'record.md').write_text('# Joint magnet sizing native study\n\n'+'\n'.join(parts)+'\n**END OF RECORD**\n')
write=H/'preparation/findings.json';write.write_text(json.dumps([{'id':f'{H.name}#{i}','title':title,'finding':body} for i,(title,body) in enumerate(findings,1)],indent=2)+'\n')
print('Wrote17 sections and',len(findings),'findings')
