from pydantic import Field
from simkit.config.schema import MultiOutput

class Controlled_Network_Heat_Driven_ClosureOutput(MultiOutput):
    """Multi-output container for Controlled_Network_Heat_Driven_Closure.

Native selectable legacy or constant-U primary-bypass closure. Full delivered duty fixes required hot temperature from the supplied aggregate return; actual accepted duty closes the cycle and exposes unmet heat. Active HX outlet and mixed loop return are distinct. Mode 0 preserves reviewed legacy arithmetic. **Source**: work/active/WI-097_exchanger-thermal-requirements/design.md. **Reference**: controlled branch equations, coupled cycle closure, domains and exact-return/30 K conditional requirements; original source interpretation in work/orchestration/goals/design-study-exchanger-architecture/evidence/r2-thermal-requirements.md. Units: MW, K, MPa, kg/s, J/(kg K), MW/K; fractions and modes dimensionless. **Last Updated**: 2026-09-27.

SysML Source: root-0/controlled_exchanger_closure.sysml:3
    """
    pbli_secondary_in: float = Field(description="pbli_secondary_in output")
    he_hx_return: float = Field(description="he_hx_return output")
    pbli_hot: float = Field(description="pbli_hot output")
    he_secondary_in: float = Field(description="he_secondary_in output")
    pbli_cold_approach_margin: float = Field(description="pbli_cold_approach_margin output")
    mixed_outlet: float = Field(description="mixed_outlet output")
    pbli_split_used: float = Field(description="pbli_split_used output")
    he_return_residual_magnitude: float = Field(description="he_return_residual_magnitude output")
    heater_inlet: float = Field(description="heater_inlet output")
    pbli_capability_at_solution: float = Field(description="pbli_capability_at_solution output")
    pbli_cold_terminal_difference: float = Field(description="pbli_cold_terminal_difference output")
    pbli_capability: float = Field(description="pbli_capability output")
    divertor_secondary_out: float = Field(description="divertor_secondary_out output")
    divertor_cold_approach_margin: float = Field(description="divertor_cold_approach_margin output")
    divertor_hot: float = Field(description="divertor_hot output")
    divertor_required_hot: float = Field(description="divertor_required_hot output")
    he_cold_approach_margin: float = Field(description="he_cold_approach_margin output")
    divertor_transferred: float = Field(description="divertor_transferred output")
    pbli_return_residual: float = Field(description="pbli_return_residual output")
    pbli_return_residual_magnitude: float = Field(description="pbli_return_residual_magnitude output")
    divertor_stream_out: float = Field(description="divertor_stream_out output")
    divertor_return_residual: float = Field(description="divertor_return_residual output")
    divertor_state_defined: float = Field(description="divertor_state_defined output")
    pbli_active_flow: float = Field(description="pbli_active_flow output")
    network_mode_used: float = Field(description="network_mode_used output")
    divertor_hx_return: float = Field(description="divertor_hx_return output")
    pbli_return: float = Field(description="pbli_return output")
    divertor_cold_terminal_difference: float = Field(description="divertor_cold_terminal_difference output")
    unmet_heat: float = Field(description="unmet_heat output")
    iterations: float = Field(description="iterations output")
    he_state_defined: float = Field(description="he_state_defined output")
    divertor_mixed_return: float = Field(description="divertor_mixed_return output")
    divertor_unmet: float = Field(description="divertor_unmet output")
    pbli_hot_terminal_difference: float = Field(description="pbli_hot_terminal_difference output")
    pbli_secondary_out: float = Field(description="pbli_secondary_out output")
    accepted_heat: float = Field(description="accepted_heat output")
    divertor_hot_approach_margin: float = Field(description="divertor_hot_approach_margin output")
    turbine_temperature: float = Field(description="turbine_temperature output")
    pbli_mixed_return: float = Field(description="pbli_mixed_return output")
    divertor_active_flow: float = Field(description="divertor_active_flow output")
    he_active_flow: float = Field(description="he_active_flow output")
    divertor_return: float = Field(description="divertor_return output")
    pbli_state_defined: float = Field(description="pbli_state_defined output")
    pbli_required_hot_margin: float = Field(description="pbli_required_hot_margin output")
    he_transferred: float = Field(description="he_transferred output")
    he_hot_terminal_difference: float = Field(description="he_hot_terminal_difference output")
    divertor_hot_bound_margin: float = Field(description="divertor_hot_bound_margin output")
    he_capability: float = Field(description="he_capability output")
    he_hot_bound_margin: float = Field(description="he_hot_bound_margin output")
    he_capability_at_solution: float = Field(description="he_capability_at_solution output")
    he_cold_terminal_difference: float = Field(description="he_cold_terminal_difference output")
    pbli_transferred: float = Field(description="pbli_transferred output")
    divertor_secondary_in: float = Field(description="divertor_secondary_in output")
    he_mixed_return: float = Field(description="he_mixed_return output")
    he_required_hot_margin: float = Field(description="he_required_hot_margin output")
    divertor_capability_at_solution: float = Field(description="divertor_capability_at_solution output")
    pbli_stream_out: float = Field(description="pbli_stream_out output")
    pbli_hx_return: float = Field(description="pbli_hx_return output")
    he_secondary_out: float = Field(description="he_secondary_out output")
    he_hot: float = Field(description="he_hot output")
    he_hot_approach_margin: float = Field(description="he_hot_approach_margin output")
    pbli_hot_approach_margin: float = Field(description="pbli_hot_approach_margin output")
    divertor_return_residual_magnitude: float = Field(description="divertor_return_residual_magnitude output")
    he_return: float = Field(description="he_return output")
    divertor_required_hot_margin: float = Field(description="divertor_required_hot_margin output")
    he_return_residual: float = Field(description="he_return_residual output")
    pbli_control_margin: float = Field(description="pbli_control_margin output")
    he_bypass_fraction: float = Field(description="he_bypass_fraction output")
    he_control_margin: float = Field(description="he_control_margin output")
    pbli_unmet: float = Field(description="pbli_unmet output")
    divertor_bypass_fraction: float = Field(description="divertor_bypass_fraction output")
    he_unmet: float = Field(description="he_unmet output")
    divertor_control_margin: float = Field(description="divertor_control_margin output")
    divertor_capability: float = Field(description="divertor_capability output")
    divertor_hot_terminal_difference: float = Field(description="divertor_hot_terminal_difference output")
    expansion_factor: float = Field(description="expansion_factor output")
    closure_residual: float = Field(description="closure_residual output")
    he_required_hot: float = Field(description="he_required_hot output")
    control_mode_used: float = Field(description="control_mode_used output")
    pbli_bypass_fraction: float = Field(description="pbli_bypass_fraction output")
    pbli_required_hot: float = Field(description="pbli_required_hot output")
    pbli_hot_bound_margin: float = Field(description="pbli_hot_bound_margin output")
