"""Write the seventeen-section evidence record from retained numeric results."""
import json,hashlib
from pathlib import Path
H=Path(__file__).resolve().parents[1];R=H/'results';P='stellarator_09__stellaris__';read=lambda p:json.loads(p.read_text());sid=H.name
an=read(R/'analysis.json');rows=an['cases'];cat=read(R/'predicate-catalog.json');axes=read(H/'axes.json')['groups'];ver=read(R/'oracle-all-points.json')
findings=[('Exact source profiles and coordinated Table5 conditioning change the reconstructed outputs while retained raw failures remain explicit.','Use only identified case contrasts; supplied volume and field receive no independent prediction credit.'),('Local cavity fit and absolute conductor capacity remain conditional or unresolved source-transfer questions.','Preserve raw diagnostics; local construction, field-angle and structural qualification remain required.'),('Helium primary-loop and generic radial-build costs and checks do not reconstruct the source water blanket.','Water hardware, transferred breeding and multiplication, and complete qualification costs remain unresolved; do not count scope exclusions as passes.'),('All-point numerical agreement checks generated implementation, not the source assumptions or engineering qualification.','Retain all twenty predicates and sixteen unmapped native outputs; no global feasibility boundary is claimed.')]
home='work/orchestration/goals/stellaris-reference-reconciliation'
fr=[{'id':f'{sid}#{i}','kind':'model','finding':f,'disposition':d,'home':home} for i,(f,d) in enumerate(findings,1)]
(H/'preparation/findings.json').write_text(json.dumps(fr,indent=2)+'\n')
log=H.parent/'DISCOVERY_LOG.md';existing=log.read_text()
with log.open('a') as f:
 for x in fr:
  if x['id'] not in existing:f.write(f"| 2026-09-16 | model | `{x['id']}` | {x['finding']} | {x['disposition']} | {home} |\n")
out=[]
def p(s=''):out.append(s)
def h(n,s):p(f'## {n}. {s}');p()
def table(head,body):
 p('| '+' | '.join(head)+' |');p('| '+' | '.join('---' for _ in head)+' |')
 for r in body:p('| '+' | '.join(str(v).replace('|','/') for v in r)+' |')
 p()
h(1,'Study header');p(f'**Study id:** {sid}. **Package:** stellarator_tea. **Date executed:** 2026-09-16. **Executor:** delegated native-study worker. **Mode:** execute. **Arm:** arm-native.');p()
h(2,'Intake')
for q in ['Ground and pursue a new goal: reconcile the modeled Stellaris reference point with the published design, recovering reference feasibility where justified or explaining the remaining deviations.','Keep alternative scenarios explicit rather than overwriting their history.','Continue autonomously until the reconciliation is implemented where justified, verified, independently reviewed and answered.']:p('[OWNER-VERBATIM] “'+q+'”');p()
p('[AGENT] Eight sensitivity cases, including explicit selected-inventory reserve scenarios, implement the bounded execution design retained in preparation/execution-design.md. Complete owner goal and invariants are retained in preparation/goal-at-authority.md. No search, numerical default change, acceptance relaxation or engineering qualification is claimed.');p()
h(3,'Objective and result');p(f'Objective: `{P}lcoe_calc__lcoe`, dollars/MWh. Eight native cases completed. Case values below are conditional scenario costs; water cooling and local construction qualification remain unpriced. Full numeric outputs appear in results/native-cases.json and case-summary.csv.');p()
table(['Case','LCOE $/MWh','Raw failed predicates'],[(r['proposal_id'],f"{r['quantities']['lcoe_calc__lcoe']:.9f}",', '.join(r['violated']) or 'none') for r in rows])
h(4,'Constraint outcomes');p(f"Combined raw passes: {an['overall']['all20_passes']} of eight. Every failed identity is located by case above. Applicability remains a separate source question; no filtered combined pass is calculated. Complete qualified identities and per-case verdicts are in results/native-cases.json. Per-case source applicability and evidence are joined in results/case-predicate-applicability.json.");p()
table(['constraint_id','source_local_identity','Statuses'],[(k,e['source_local_identity'],an['predicate_outcomes'][k]['counts']) for k,e in cat.items()])
h(5,'Framing');p('Proposed and judged framing are sensitivity for every axis. None changed. Profile and source geometry/current interventions are coordinated groups; their individual causal effects are not isolated. Two geometry checks isolate R and a locally. No optimum or engineering boundary claim is made.');p()
table(['Axis','Proposed','Judged','Changed'],[(g['axis'],'sensitivity','sensitivity','no') for g in axes])
h(6,'Per-axis account')
for g in axes:
 p(f"#### {g['axis']} — feasible structure (search framing)");p();p('**Applies:** not applicable — this axis is sensitivity-framed.');p();p(f"#### {g['axis']} — observed response (sensitivity framing)");p();p('**Applies:** yes.');p();p({'plasma__R':'The isolated R increase raises required auxiliary power from 45.172538 to 55.663445 MW, adding a sustainment failure. Its coordinated Table5 change is not a separate radius effect.','plasma__a':'The isolated a increase lowers LCOE from 144.616024 to 141.940118 dollars/MWh but adds a peak-field failure.','plasma__alpha_n':'The paired exact fuel/temperature profiles reduce fusion from 2652.563263 to 2608.999914 MW and operating auxiliary demand from 49.079601 to 45.172538 MW; no predicate recovers. Individual exponent effects are not isolated.','plasma__alpha_T':'The paired exact profiles change legacy LCOE by −0.131407 dollars/MWh and selected-reserve LCOE by +0.024284 dollars/MWh. Individual exponent effects are not isolated.','plasma__f_shape':'Coordinated Table5 radius/shape/current conditioning sets volume425m³ and preserves9T; legacy LCOE changes by +0.040499 dollars/MWh from the exact-profile case, without predicate recovery. Shape effect is not isolated.','magnet__coil__I_coil':'The source-conditioned ampere-turns compensate R to retain9T. This is supplied conditioning, not current-prediction validation or an isolated current effect.','magnet__winding_pack__sizing_mode':'Mode1 with1.01 reserve recovers the conditional current screen, raises control LCOE by18.446798 dollars/MWh and worsens minimum fit margin from−0.120000 to−0.285309m. Mode and reserve effects are joint.','magnet__winding_pack__inventory_multiplier':'The1.01 reserve accompanies mode1. It must not replace the separately retained exact multiplier1 historical control or imply that boundary discrepancy was resolved.'}[g['axis']]+' Full case-specific violations are in §3. No boundary claim is made.');p()
h(7,'Axis groups');p('Every public attribute has one complete native entry group; plant radius fans out internally. Table5 current compensates the radius change to hold the reduced-model on-axis field; it is agent-derived conditioning, not source current validation. Fixed magnet shape/reference anchors remain historical.');p()
table(['Axis','Entry key','Provenance'],[(g['axis'],k['key'],k['provenance']) for g in axes for k in g['keys']])
h(8,'Indicators and rulings');p('All eight groups have constraints_reachable. No no_constraint_response axis exists, so no missing-pushback ruling is required. A reachable path does not establish response. Monotonicity, physical identity across differing keys and intra-module operand dependency are not derivable. No proposed native axis was declined. Source review and coordinator release precede every scientific run.');p()
h(9,'Preflight results');p('Exact manifest baseline and all mechanical preflight gates pass. Gate detail is retained in results/preflight_results.json; consumed identity and baseline documents are results/package_identity.json and baseline_result.json. Warning-only suffix siblings remain in that report. Native package cleanliness passed before and after execution.');p()
h(10,'Execution route and why');p('Study-local direct API uses the stock StudyRunner and PreparedListStrategy through study_route.run_points. It preserves coordinated source-conditioned inputs. Complete entry models, native store and every output/predicate are retained. Glue ledger: none; no adapter or physical equation supplied by an execution harness. Parameter preparation conditions native inputs explicitly.');p()
h(11,'Study definition and window provenance');p('The oracle scans the same eight planned contrasts after preflight; reviews/window-selection.md fixes that finite sample before native execution. The window is engineered around sourced reference values and 2% local checks. No feasibility bracket or search-edge coverage is claimed. Eight study points plus the separate required baseline are distinct obligations.');p()
h(12,'Cross-fingerprint correlation and what it means');p('Single unchanged executable fingerprint; no cross-arm correlation needed. Legacy control is re-executed explicitly. The selected cases use inventory reserve 1.01; the exact historical selected mode at multiplier 1.0 is retained separately as reused evidence in preparation/selected-mode-check.json. Its 224/226 strict relative scalar passes and 19/20 oracle predicate agreement retain the current-boundary discrepancy without tolerance changes. Comment corrections change source attribution without changing calculation tokens or numeric inputs; integration_return.json establishes the current candidate.');p()
h(13,'Verification');p(f"All {ver['scalar_comparisons']} mapped scalar comparisons and {ver['predicate_comparisons']} exact independently rederived predicates pass. Generic stratified verification separately passes. Exact case contrasts and source-conditioned target accounting are retained in results/contrasts.json and source-conditioned-divertor.json. All 242 native scalars survive; sixteen unmapped channels are listed in results/oracle-all-points.json. Numerical agreement verifies implementation against the independent equation copy; shared physical assumptions and supplied quantities are not independently validated. Native evidence joins and artifact hashes are checked separately.");p()
h(14,'Review outcomes');table(['Lens','Verdict','Disposition'],[('Original source/math','Independent source review accepted before release','preparation/source-review.md; retained limitations apply'),('Integration','CANDIDATE, all ten gates pass','preparation/integration-return.json'),('Execution scope','Coordinator release','preparation/execution-release.json and reviews/preexecution-check.md'),('All-point arithmetic and store custody','Executor checks pass','Not independent certification'),('Final scientific review','Parent-arranged after frozen record','No final independent verdict claimed here')])
h(15,'Findings');table(['Id','Kind','Finding','Disposition','Home'],[(f"`{x['id']}`",x['kind'],x['finding'],x['disposition'],x['home']) for x in fr])
h(16,'Snapshot');p('**File:** snapshot.json. **Schema version:** 1. **sha256:** '+(hashlib.sha256((H/'snapshot.json').read_bytes()).hexdigest() if (H/'snapshot.json').exists() else 'Pending freeze.'));p()
h(17,'What this record does not contain');p('No measured local coil cavity, engineering-qualified conductor/current/field-angle construction, water-loop hardware or installed quote; no demonstrated target spatial heat map, global feasibility boundary, source-qualified plant, or independent final-review verdict. Source-conditioned target accounting supplies peaks and earns no peak-prediction credit. The sixteen unmapped channels have no independent oracle comparison here.');p()
(H/'record.md').write_text('\n'.join(out))
