"""Laser ICF — p-B11 Fast Ignition (HB11 Energy): 1cfe model setup.

Usage:
    uv run python model_setup.py              # print results to terminal
    uv run python model_setup.py | tee model_output.txt  # also save for synthesis stage

Modeling approach:
    This script estimates an LCOE floor for HB11 Energy's concept under a
    "best-case aspirational" scenario in which all of the company's published
    targets are simultaneously achieved: gain >500 from the avalanche mechanism,
    >10% wall-plug efficiency from the Adelaide USPL partnership, 1 Hz rep rate,
    and conventional steam-cycle energy conversion. This is NOT a credible
    engineering estimate — the concept is TRL 1 for its core physics mechanism
    and ~4 orders of magnitude below energy breakeven in experiments. The model
    serves as an LCOE lower bound: if the concept somehow works as advertised,
    this is roughly what the economics look like.

Concept choice rationale:
    ConfinementConcept.LASER_IFE is the correct parent concept for HB11.
    Although HB11 uses "fast ignition" rather than central hot-spot (NIF-style)
    or indirect-drive ignition, the plant architecture is IFE:
    pulsed laser driver → target shot → heat capture → steam cycle.
    The two-laser architecture (ns for kT field, ps CPA for fast ignition) maps
    naturally to p_implosion / p_ignition in the IFE power balance.

Key deviations from LASER_IFE defaults:
    Fuel-specific:
        - Fuel = PB11 (aneutronic: <1% neutron energy fraction from side reactions)
        - mn = 1.0 (no neutron multiplication — no breeding blanket needed)
        - p_trit = 0.0 (no tritium; eliminates the dominant MFE driver cost)
        - p_cryo = 0.0 (no superconducting magnets anywhere in the plant)
        - blanket_t = 0.05 m (thin first wall only; no neutron breeding blanket)
        - ht_shield_t = 0.05 m (minimal shielding; aneutronic fuel)

    Energy conversion (steam cycle, per 2025 website — contradicts 2018 patent):
        - eta_th = 0.35 (steam Rankine cycle; standard IFE pulsed-source estimate)
        - CAS23 retained (steam turbine plant required)
        - NOTE: If direct electrostatic conversion (patent) were used instead,
          eta_th could reach 0.60–0.80, which would dramatically reduce the
          laser energy requirement and improve LCOE. This pivot is unresolved.

    Laser system (aspirational targets, neither demonstrated nor costed):
        - eta_pin1 = 0.10 (ps CPA petawatt laser wall-plug efficiency; target of
          A$8.2M Adelaide USPL partnership — current state-of-the-art is <1%)
        - eta_pin2 = 0.10 (ns laser for kT field; same assumed — not stated)
        - p_implosion derived from gain=500 + 1 GW target (see SCENARIO MATH)
        - p_ignition = 0.1 MW (ns laser ~100 J/shot × 1 Hz; from patent)

    Cost overrides:
        - C220103 = $0: No permanent coil system. The kT field is generated by
          single-shot consumable capacitor-coil targets (cost → C220108 / O&M).
        - C220104 = $0: No NBI heating system. The laser IS the driver.
        - C220108 = $400M: UNCERTAIN target factory estimate covering BOTH the
          HB11 fuel pellets (1 cm × 0.2 mm solid HB11, ~5 µm Ag cover layer)
          AND the capacitor-coil target assemblies, both at 31.5M units/year.
          Framework default ($244M) likely underestimates this dual-consumable
          production challenge; $400M is a rough scaling estimate.
        - CAS21 = $420M: No cryogenics building (saves ~$15/kW); no hot cell
          at full DT scale (aneutronic, saves ~$78/kW); reduced heat exchanger
          ($6/kW for smaller thermal load). Net ~$420M at 1 GWe.

SCENARIO MATH (illustrative, highly uncertain):
    For 1 GWe net at 35% steam efficiency:
        P_fusion = 1000 / 0.35 ≈ 2857 MW
    At gain = 500 (aspirational) and 1 Hz rep rate:
        Laser energy/shot = 2857 MJ / 500 = 5.71 MJ → p_implosion = 5.71 MW avg
    At eta_pin1 = 10% wall-plug:
        Wall-plug power = 5.71 / 0.10 = 57.1 MW drawn from grid for laser
    This implies Q_eng ≈ 1000 / 57.1 ≈ 17.5 — plausible for aneutronic IFE
    if gain is real, but experimentally the concept is ~10,000× below breakeven.

    Patent example (30 kJ laser, gain 500): p_fus = 0.03 MW × 500 = 15 MW —
    insufficient by a factor of ~190 for a 1 GW plant. The "thousands of
    lasers" architecture on the 2025 website implicitly accepts this and scales
    up the laser energy per shot or the number of simultaneous targets.
"""

from costingfe import ConfinementConcept, CostModel, Fuel

# ── Model creation ────────────────────────────────────────────────────
model = CostModel(concept=ConfinementConcept.LASER_IFE, fuel=Fuel.PB11)

# ── Plant configuration constants ─────────────────────────────────────
# HB11 company target: 1 GW baseload net electric output
# Source: hb11-technology-page-2025.md §Energy Conversion
# Confidence: medium (stated goal, no engineering basis published)
NET_ELECTRIC_MW = 1000.0

# UNCERTAIN: 70% availability — lower than mature IFE/MFE estimates (85%)
# because rep-rated petawatt laser operation at 1 Hz is undemonstrated.
# Chamber clearing, pellet injection, and laser thermal management at 1 Hz
# are all engineering challenges without analogues in existing facilities.
# Assumption: best-case for early commercial deployment.
AVAILABILITY = 0.70

# ── Forward model ─────────────────────────────────────────────────────
result = model.forward(
    net_electric_mw=NET_ELECTRIC_MW,
    availability=AVAILABILITY,
    lifetime_yr=30,
    n_mod=1,
    construction_time_yr=5.0,  # DEFAULT: ife_laser_ife.yaml; reasonable for IFE
                                # (no large magnets → shorter than tokamak)
    interest_rate=0.07,
    inflation_rate=0.0245,
    noak=True,

    # ── Geometry (spherical chamber, from patent) ─────────────────
    # Patent specifies spherical stainless steel chamber, ≥1 m diameter.
    # Source: hb11-patent-reactor-design.md §Reactor Geometry
    # Commercial scale chamber size unspecified; use IFE defaults.
    R0=0.0,          # Spherical IFE chamber (no major radius)
    plasma_t=4.0,    # DEFAULT: ife_laser_ife.yaml; chamber radius [m]
    blanket_t=0.05,  # Thin first wall only — no neutron breeding blanket needed.
                     # p-B11 is nearly aneutronic (<1% neutron fraction).
                     # Source: [nuclear physics constant — p-B11 primary reaction aneutronic;
                     #          neutrons only from secondary reactions (D-D, n-B11, etc.)]
    ht_shield_t=0.05,   # Minimal neutron shielding (aneutronic fuel).
                         # Source: analysis.md §Section 4 (materials)
    structure_t=0.15,    # DEFAULT: ife_laser_ife.yaml
    vessel_t=0.10,       # DEFAULT: ife_laser_ife.yaml

    # ── Power balance ─────────────────────────────────────────────
    # ps CPA petawatt laser (fast ignition driver):
    #   UNCERTAIN: p_implosion derived from aspirational gain=500 + 1 GW target.
    #   At gain=500 and 35% steam efficiency, P_fusion ≈ 2857 MW.
    #   Laser optical output average = 2857 MW / 500 gain = 5.71 MW.
    #   Patent example (30 kJ/shot × 1 Hz) gives only 0.030 MW — far less.
    #   The "thousands of lasers" 2025 architecture is uncharacterized.
    #   Source: hb11-patent-reactor-design.md §Laser Specifications (Fusion Laser)
    #           hb11-technology-page-2025.md §Laser System
    #           analysis.md §Section 5 (LCOE table, patent parameters row)
    p_implosion=5.71,  # UNCERTAIN: ps CPA laser avg optical output [MW]

    # ns laser for capacitor-coil target (drives kT magnetic field):
    #   Patent specifies >100 J per shot, <20 ns pulse.
    #   At 1 Hz: average power = 100 J × 1 Hz = 100 W = 0.0001 MW.
    #   Rounded up by ~1000× from 0.0001 MW (100 W physical) to avoid numerical zero in
    #   framework. Impact on results negligible (<0.01% of total driver power).
    #   Source: hb11-patent-reactor-design.md §Laser Specifications (Magnetic Field Laser)
    p_ignition=0.1,  # ns laser for kT field generation [MW avg] (negligible)

    # Neutron energy multiplier:
    #   p-B11 primary reaction: p + B11 → 3 He4 (8.7 MeV, no neutrons).
    #   Side reactions produce <1% of fusion energy as neutrons.
    #   No breeding blanket → mn = 1.0.
    #   Source: [nuclear physics constant — p-B11 primary reaction aneutronic;
    #            neutrons only from secondary reactions (D-D, n-B11, etc.)]
    mn=1.0,

    # Thermal conversion efficiency:
    #   2025 website: "conventional steam cycle generator."
    #   Source: hb11-technology-page-2025.md §Energy Conversion
    #   Assumed 35% for pulsed IFE with steam (consistent with Z-IFE and LIFE
    #   studies for pulsed source + thermal buffer → turbine).
    #   NOTE: The 2018 patent described direct electrostatic conversion at −1.4 MV,
    #   which could achieve 60–80% efficiency. If that approach is viable, the
    #   laser energy requirement drops by ~2× and LCOE improves substantially.
    #   Source for pivot: hb11-newatlas-article.md §Energy Conversion (direct, 2020)
    #                     hb11-technology-page-2025.md §Energy Conversion (steam, 2025)
    #                     analysis.md §Section 2, Challenge 4
    eta_th=0.35,  # UNCERTAIN: Steam Rankine; direct conversion would be 0.60–0.80

    # Laser wall-plug efficiency:
    #   UNCERTAIN: Target of Adelaide USPL partnership (>10%).
    #   Current state-of-the-art for PW-class CPA lasers: <1%.
    #   A 10% improvement represents a ~10× advance over demonstrated performance.
    #   Source: hb11-recent-developments-2024-2025.md §Adelaide Laser Partnership (2025)
    #           analysis.md §Section 2, Challenge 2
    eta_pin1=0.10,  # UNCERTAIN: ps CPA petawatt laser wall-plug (target, not achieved)
    eta_pin2=0.10,  # UNCERTAIN: ns laser wall-plug (assumed same; not stated)

    eta_p=0.5,     # DEFAULT: pumping efficiency
    f_sub=0.03,    # DEFAULT: subsystem power fraction

    # Auxiliary power loads:
    p_pump=1.0,    # DEFAULT: ife_laser_ife.yaml; vacuum pumping [MW]
    p_trit=0.0,    # No tritium processing — p-B11 produces no tritium.
                   # Source: hb11-technology-page.md §Key Technical Details
                   # This eliminates a major DT cost driver (~$10M/MW equivalent).
    p_house=4.0,   # DEFAULT: housekeeping power [MW]
    p_cryo=0.0,    # No superconducting magnets anywhere in the plant.
                   # The kT field is from transient laser-driven capacitor-coil targets.
                   # Source: hb11-patent-reactor-design.md §Magnetic Field Generation
    p_target=1.0,  # DEFAULT: ife_laser_ife.yaml; target factory aux power [MW]

    # ── Cost overrides ────────────────────────────────────────────
    cost_overrides={
        # C220103: Coils — $0 (no permanent coil system).
        #   The kT magnetic field is generated per-shot by consumable capacitor-coil
        #   targets (a small metal coil attached to each fuel pellet assembly).
        #   There is no standing magnet infrastructure. Capital cost of the ns laser
        #   system and pulsed power conditioning for the kT field is small (~$5M
        #   for the pulse delivery system, captured in the laser driver capital).
        #   Source: hb11-patent-reactor-design.md §Magnetic Field Generation
        "C220103": 0.0,  # No permanent coils [M$]

        # C220104: Heating / Driver system — $0 (laser IS the driver).
        #   For IFE concepts, NBI heating does not apply. The laser driver capital
        #   cost is captured separately in the laser system model (C220103 in some
        #   MFE frameworks, or implicitly through the laser power scaling in IFE).
        #   The framework's LASER_IFE concept already accounts for laser capital
        #   through the p_implosion/p_ignition parameterization.
        "C220104": 0.0,  # No NBI heating system [M$]

        # C220108: Target factory — UNCERTAIN upward adjustment from $244M default.
        #   HB11's factory must produce two consumable components per shot at 1 Hz:
        #   (1) HB11 fuel pellet: 1 cm × 0.2 mm cylindrical solid, ~5 µm Ag cover
        #       layer, held on quartz fiber → 31.5M units/year.
        #   (2) Capacitor-coil target assembly: a small metal coil with electrical
        #       leads, matched to the fuel pellet geometry → 31.5M units/year.
        #   This dual-component requirement is structurally more demanding than
        #   conventional ICF (single cryogenic DT capsule). The $400M estimate
        #   scales from the framework default ($244M) by ~1.6× for dual-component.
        #   This is highly uncertain — no production cost estimates exist for either
        #   component at volume. The 07-maglif analysis identified analogous RTL
        #   (return current limiter) per-shot consumables as a blocking cost gap.
        #   Source: hb11-patent-reactor-design.md §Reactor Geometry
        #           analysis.md §Section 2, Challenge 3 (per-shot consumables)
        "C220108": 400.0,  # UNCERTAIN: dual-component target factory [M$]

        # CAS21: Buildings — adjusted for aneutronic fuel (no cryogenics building,
        #   reduced hot cell, smaller heat exchanger relative to DT IFE).
        #   Framework default for LASER_IFE/PB11 at 1 GWe ≈ $511M (non-DT scaling
        #   per costing_constants.yaml §building_costs_per_kw).
        #   Adjustments: remove cryogenics ($15/kW × 1000 = −$15M); reduce hot cell
        #   by 50% (aneutronic, low activation, −$47M); reduce heat exchanger
        #   (thin blanket, −$6M). Net reduction ≈ −$68M → $443M (= $511M − $68M).
        "CAS21": 443.0,  # Adjusted buildings (no cryo, reduced hot cell) [M$]
    },
)

# ── Results ───────────────────────────────────────────────────────────
c = result.costs
pt = result.power_table

print("Laser ICF — p-B11 Fast Ignition (HB11 Energy)")
print(f"  BEST-CASE ASPIRATIONAL: gain=500, eta_pin=10%, steam cycle at 35%")
print(f"  {NET_ELECTRIC_MW:.0f} MWe net | {AVAILABILITY:.0%} availability | 30 yr lifetime")
print()
lcoe_ckwh = float(c.lcoe) / 10
print(
    f"LCOE: {c.lcoe:.1f} $/MWh ({lcoe_ckwh:.2f} ¢/kWh)"
    f" | Overnight: {c.overnight_cost:.0f} $/kW"
)
print(f"Fusion: {pt.p_fus:.0f} MW | Net: {pt.p_net:.0f} MW | Q_eng: {pt.q_eng:.1f}")
print(f"Recirculating fraction: {pt.rec_frac:.1%}")
print(f"Scientific Q (P_fus / P_laser): {pt.q_sci:.1f}")
print()

# ── CAS breakdown ─────────────────────────────────────────────────────
cas = [
    ("CAS10", "Preconstruction", c.cas10),
    ("CAS21", "Buildings", c.cas21),
    ("CAS22", "Reactor Plant Equipment", c.cas22),
    ("CAS23", "Turbine Plant", c.cas23),
    ("CAS24", "Electrical Plant", c.cas24),
    ("CAS25", "Miscellaneous", c.cas25),
    ("CAS26", "Heat Rejection", c.cas26),
    ("CAS27", "Special Materials", c.cas27),
    ("CAS28", "Digital Twin", c.cas28),
    ("CAS29", "Contingency", c.cas29),
    ("CAS30", "Indirect Costs", c.cas30),
    ("CAS40", "Owner's Costs", c.cas40),
    ("CAS50", "Supplementary", c.cas50),
    ("CAS60", "IDC", c.cas60),
    ("CAS70", "O&M (annualized)", c.cas70),
    ("CAS80", "Fuel (annualized)", c.cas80),
    ("CAS90", "Financial", c.cas90),
]

print(f"{'Code':<8} {'Account':<28} {'M$':>10}")
print("-" * 48)
for code, name, val in cas:
    print(f"{code:<8} {name:<28} {float(val):>10.1f}")
print("-" * 48)
print(f"{'':8} {'Total Capital':<28} {float(c.total_capital):>10.1f}")

# ── CAS22 sub-account detail ─────────────────────────────────────────
print("\nCAS22 Reactor Plant Equipment Breakdown:")
print("-" * 48)
for k, v in sorted(result.cas22_detail.items()):
    if float(v) > 0:
        print(f"  {k:<28} {float(v):>10.1f} M$")

# ── Overridden accounts ───────────────────────────────────────────────
print(f"\nOverridden accounts: {', '.join(result.overridden)}")

# ── Key assumptions summary ───────────────────────────────────────────
print("\nKey Assumptions (aspirational / uncertain — see docstring):")
print("-" * 60)
print(f"  Net electrical output:       {NET_ELECTRIC_MW:.0f} MWe (company target)")
print(f"  Availability:                {AVAILABILITY:.0%} (undemonstrated rep-rate laser)")
print(f"  Fuel:                        p-B11 (aneutronic, no tritium)")
print(f"  Rep rate:                    1 Hz (company target; not yet demonstrated)")
print(f"  Energy gain (Q_plasma):      ~500 (aspirational; avalanche mechanism unvalidated)")
print(f"  Laser wall-plug eff (ps):    10% (Adelaide USPL target; current <1%)")
print(f"  Laser wall-plug eff (ns):    10% (assumed; not stated)")
print(f"  Thermal conversion:          35% (steam Rankine; direct conv. could be 60-80%)")
print(f"  Neutron multiplier:          1.0 (aneutronic, no breeding blanket)")
print(f"  Cryogenics:                  None (no superconducting magnets)")
print(f"  Tritium processing:          None (p-B11 produces no tritium)")
print(f"  Target factory:              $400M UNCERTAIN (dual-component: pellet + cap-coil)")
print()
print("Modeling notes:")
print("  - This model represents a physically impossible scenario with today's")
print("    technology: the 'avalanche' gain mechanism (gain >500) has zero")
print("    experimental confirmation and the concept is ~10,000× below breakeven.")
print("    The model estimates the LCOE floor only — if the concept works.")
print("  - The energy conversion method is unresolved: the 2018 patent describes")
print("    direct electrostatic conversion at -1.4 MV (no steam turbine needed).")
print("    The 2025 website says 'conventional steam cycle generator'. This model")
print("    uses the steam cycle assumption. Direct conversion at eta_th=0.70 would")
print("    reduce the required laser power by ~2× and reduce LCOE significantly.")
print("  - p_implosion=5.71 MW assumes the aspirational scenario math closes.")
print("    The patent's stated parameters (30 kJ × gain 500 = 15 MW fusion) would")
print("    give ~5 MWe net — a factor of 190× below the 1 GW company target.")
print("  - Target factory cost ($400M) is a rough estimate. The per-shot dual-")
print("    component consumable challenge (fuel pellet + capacitor-coil assembly")
print("    at 31.5M units/year) has no precedent and no published cost study.")
print("  - Laser system capital cost is among the largest uncertainties; 1 Hz PW")
print("    CPA laser systems have no commercial supply chain. The framework's")
print("    laser driver capital is an IFE default derived from indirect-drive DT")
print("    ICF studies and may not be representative of HB11's USPL architecture.")

# ── Sensitivity Analysis ──────────────────────────────────────────────
sens = model.sensitivity(result.params)

print("\nSensitivity (elasticity = %LCOE / %param)")
print("-" * 48)

print("\nEngineering levers:")
for k, v in sorted(sens["engineering"].items(), key=lambda x: abs(x[1]), reverse=True):
    print(f"  {k:<28} {v:+.4f}")

print("\nFinancial:")
for k, v in sorted(sens["financial"].items(), key=lambda x: abs(x[1]), reverse=True):
    print(f"  {k:<28} {v:+.4f}")
