from pydantic import Field
from simkit.config.schema import MultiOutput

class Matched_Steam_CycleOutput(MultiOutput):
    """Multi-output container for Matched_Steam_Cycle.

*Source**: work/orchestration/goals/current-model-comparison-readiness/evidence/round2/cycle-proposal-v2.md **Reference**: WI-073 design.md and interface-inventory.md; original NIST tables and independent physical review. **Basis**: [AGENT] reviewed reduced extraction/reheat cycle and conditional cooling-water scenario; equipment and installed cost unqualified. **Last Updated**: 2026-09-19 Numerical semantic: the normative handwritten implementation executes the exact state/work equations in the cited design. Disabled modes branch before property access; no extrapolation. Units are given by the scalar names and interface inventory.

SysML Source: root-0/mfe_matched_steam_cycle.sysml:3
    """
    s_main_kJ_kgK: float = Field(description="s_main_kJ_kgK output")
    reheat_min_gap_K: float = Field(description="reheat_min_gap_K output")
    mdot_heater_kg_s: float = Field(description="mdot_heater_kg_s output")
    h_hp_kJ_kg: float = Field(description="h_hp_kJ_kg output")
    s_lp_kJ_kgK: float = Field(description="s_lp_kJ_kgK output")
    p_condensate_pumped_MPa: float = Field(description="p_condensate_pumped_MPa output")
    mdot_main_kg_s: float = Field(description="mdot_main_kg_s output")
    mdot_reheat_kg_s: float = Field(description="mdot_reheat_kg_s output")
    q_generator_loss_MW: float = Field(description="q_generator_loss_MW output")
    t_feed_C: float = Field(description="t_feed_C output")
    p_cycle_net_before_cooling_MW: float = Field(description="p_cycle_net_before_cooling_MW output")
    main_UA_available: bool = Field(description="main_UA_available output")
    p_feedwater_electric_MW: float = Field(description="p_feedwater_electric_MW output")
    q_rejection_before_cooling_MW: float = Field(description="q_rejection_before_cooling_MW output")
    p_lp_MPa: float = Field(description="p_lp_MPa output")
    lp_quality: float = Field(description="lp_quality output")
    h_condensate_pumped_kJ_kg: float = Field(description="h_condensate_pumped_kJ_kg output")
    t_heater_C: float = Field(description="t_heater_C output")
    p_cycle_pumps_MW: float = Field(description="p_cycle_pumps_MW output")
    t_condensate_C: float = Field(description="t_condensate_C output")
    salt_reheat_flow_kg_s: float = Field(description="salt_reheat_flow_kg_s output")
    s_reheat_kJ_kgK: float = Field(description="s_reheat_kJ_kgK output")
    salt_main_flow_kg_s: float = Field(description="salt_main_flow_kg_s output")
    p_gross_MW: float = Field(description="p_gross_MW output")
    p_feedwater_shaft_MW: float = Field(description="p_feedwater_shaft_MW output")
    h_main_kJ_kg: float = Field(description="h_main_kJ_kg output")
    t_reheat_C: float = Field(description="t_reheat_C output")
    installed_sg_capacity_qualified: bool = Field(description="installed_sg_capacity_qualified output")
    p_hp_shaft_MW: float = Field(description="p_hp_shaft_MW output")
    p_main_MPa: float = Field(description="p_main_MPa output")
    t_hp_C: float = Field(description="t_hp_C output")
    mdot_feed_kg_s: float = Field(description="mdot_feed_kg_s output")
    mdot_bleed_kg_s: float = Field(description="mdot_bleed_kg_s output")
    p_condensate_MPa: float = Field(description="p_condensate_MPa output")
    salt_heat_residual_MW: float = Field(description="salt_heat_residual_MW output")
    p_hp_MPa: float = Field(description="p_hp_MPa output")
    active: bool = Field(description="active output")
    eta_gross: float = Field(description="eta_gross output")
    h_lp_kJ_kg: float = Field(description="h_lp_kJ_kg output")
    mdot_condensate_kg_s: float = Field(description="mdot_condensate_kg_s output")
    h_feed_kJ_kg: float = Field(description="h_feed_kJ_kg output")
    heater_energy_residual_MW: float = Field(description="heater_energy_residual_MW output")
    lp_moisture_fraction: float = Field(description="lp_moisture_fraction output")
    t_main_C: float = Field(description="t_main_C output")
    cycle_electric_residual_MW: float = Field(description="cycle_electric_residual_MW output")
    p_feed_MPa: float = Field(description="p_feed_MPa output")
    main_UA_MW_K: float = Field(description="main_UA_MW_K output")
    bleed_fraction: float = Field(description="bleed_fraction output")
    p_reheat_MPa: float = Field(description="p_reheat_MPa output")
    mdot_lp_kg_s: float = Field(description="mdot_lp_kg_s output")
    reheat_UA_MW_K: float = Field(description="reheat_UA_MW_K output")
    p_lp_shaft_MW: float = Field(description="p_lp_shaft_MW output")
    p_heater_MPa: float = Field(description="p_heater_MPa output")
    q_main_MW: float = Field(description="q_main_MW output")
    q_pump_motor_loss_MW: float = Field(description="q_pump_motor_loss_MW output")
    q_mechanical_loss_MW: float = Field(description="q_mechanical_loss_MW output")
    p_condensate_electric_MW: float = Field(description="p_condensate_electric_MW output")
    main_min_gap_K: float = Field(description="main_min_gap_K output")
    heater_mass_residual_kg_s: float = Field(description="heater_mass_residual_kg_s output")
    s_hp_kJ_kgK: float = Field(description="s_hp_kJ_kgK output")
    h_heater_kJ_kg: float = Field(description="h_heater_kJ_kg output")
    main_admission_ok: bool = Field(description="main_admission_ok output")
    q_condenser_MW: float = Field(description="q_condenser_MW output")
    mdot_hp_kg_s: float = Field(description="mdot_hp_kg_s output")
    h_condensate_kJ_kg: float = Field(description="h_condensate_kJ_kg output")
    p_condensate_shaft_MW: float = Field(description="p_condensate_shaft_MW output")
    turbine_equipment_qualified: bool = Field(description="turbine_equipment_qualified output")
    h_reheat_kJ_kg: float = Field(description="h_reheat_kJ_kg output")
    cycle_shaft_residual_MW: float = Field(description="cycle_shaft_residual_MW output")
    reheat_admission_ok: bool = Field(description="reheat_admission_ok output")
    s_heater_kJ_kgK: float = Field(description="s_heater_kJ_kgK output")
    q_reheat_MW: float = Field(description="q_reheat_MW output")
    s_feed_kJ_kgK: float = Field(description="s_feed_kJ_kgK output")
    salt_flow_total_kg_s: float = Field(description="salt_flow_total_kg_s output")
    reheat_UA_available: bool = Field(description="reheat_UA_available output")
    s_condensate_kJ_kgK: float = Field(description="s_condensate_kJ_kgK output")
    mdot_condensate_pumped_kg_s: float = Field(description="mdot_condensate_pumped_kg_s output")
    t_lp_C: float = Field(description="t_lp_C output")
