"""Materialize the reviewed scalar SysML contract; no runtime or oracle implementation here."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[4];HERE=Path(__file__).resolve().parent
P={
'facilities_enabled':True,'facilities_cost_mode':1,'facilities_capacity_mode':1,
'sector_count':4,'sector_bays':4,'sector_service_teams':2,'exterior_allowance':2,'sector_route_clearance':6,'sector_headroom':3,
'component_width':4,'component_height':2,'component_length':2,'component_handling_margin':.5,'component_material_fraction':.5,'divertor_packages_per_sector':4,'waste_package_yield':1,
'component_remove_days':.5,'component_install_days':.5,'sector_clean_days':7,'sector_test_days':7,'sector_split_days':7,'sector_join_days':7,'sector_transport_days':2,'cooldown_days':30,'recommission_days':30,
'initial_receipt_lead_days':180,'initial_sector_start_days':-120,'component_receipt_lead_days':90,'component_prepare_days':1,'component_process_days':1,'component_hold_days':365.25,'clean_positions':36,'dirty_buffer_positions':18,'dirty_store_positions':36,
'cooling_initial_receipt_lead_days':180,'cooling_initial_handoff_days':-30,'cooling_receipt_lead_days':90,'cooling_hold_days':365.25,'cooling_prepare_stations':2,'cooling_machine_stations':2,'cooling_bundle_stations':2,'cooling_prepare_machine_days':.5,'cooling_prepare_bundle_days':1,'cooling_machine_process_days':2,'cooling_bundle_process_days':5,'cooling_field_cycle_days':.2,'cooling_internal_move_days':.1,
'cooling_clean_helium_positions':29,'cooling_clean_salt_positions':29,'cooling_clean_bundle_positions':14,'cooling_dirty_helium_positions':28,'cooling_dirty_salt_positions':28,'cooling_dirty_bundle_positions':14,
'helium_package_length':6,'helium_package_width':3,'helium_package_height':4,'salt_package_length':3,'salt_package_width':2,'salt_package_height':3,'hx_end_allowance':2,'cooling_package_margin':1,'cooling_aisle_width':6,'cooling_cross_width':17,'cooling_headroom':9,'cooling_airlock_length':17,
'nuclear_wall':2,'nuclear_floor':1,'nuclear_roof':1,'nuclear_rebar_density':150,'conventional_wall':.3,'conventional_floor':.3,'conventional_roof':.2,'conventional_rebar_density':100,'building_separation':10,'external_access_width':12,'provisional_envelope_scale':1,
'administration_occupants':200,'control_occupants':30,'security_occupants':10,'administration_area_per_person':12,'control_area_per_person':15,'security_area_per_person':12,'occupancy_circulation_factor':1.3,'occupancy_height':4,'occupancy_aspect_ratio':2,
'heat_rejection_length':100,'heat_rejection_width':60}
BOPS={'turbine':(60,20,15),'cryo_coldbox':(20,12,10),'cryo_compressors':(30,12,8),'fuel':(30,20,8),'reactor_aux':(30,20,10),'power_supply':(20,10,8),'onsite_ac':(16,8,6),'service_water':(20,15,8),'conventional_shop':(20,15,8),'site_services':(20,10,6)}
for stem,dims in BOPS.items():
 for suffix,value in zip(('length','width','height'),dims):P[stem+'_'+suffix]=value
RATES={'sub_concrete_rate':(358772.036+354136.3796)/(2100*.764554857984),'sub_formwork_rate':(182434.8277+19191.92427)/(3100*.09290304),'sub_rebar_rate':(568568.0349+546291.652)/(260*907.18474),'super_concrete_rate':(3527928.923+1989909.18)/(11800*.764554857984),'super_formwork_rate':(14196509.53+1403236.116)/(234300*.09290304),'super_rebar_rate':(4861416.797+3571906.955)/(1700*907.18474),'civil_cpi_ratio':321.9/251.1,'civil_rate_multiplier':1.,'tonne_interpretation_kg':907.18474,'ventilation_coefficient':1000.,'ventilation_exponent':.8,'ventilation_cpi_ratio':321.9/130.7,'land_rate_per_acre':10000.,'retained_site_improvements':85e6}
UP={'n_mod':'n_mod','major_radius':'plasma.R','minor_outer_radius':'radial_outer_radius','blanket_volume':'rb.blanket_vol','calendar_q':'blanket.wall_load_peak','calendar_fluence':'blanket.first_wall.fluence_limit','calendar_years':'operational_years','calendar_outage':'outage_years','calendar_unplanned':'unplanned_fraction','calendar_mode':'availability_direct','calendar_life':'calendar.physical_life_fpy','calendar_count':'calendar.n_replacements','calendar_availability':'calendar.availability','cooling_circuits':'heat_transport.n_loops','cooling_helium_count':'heat_transport.helium_machine_count','cooling_salt_count':'heat_transport.salt_machine_count','cooling_bundle_count':'heat_transport.exchanger_count','cooling_machine_life':'heat_transport.equipment_machine_life','cooling_bundle_life':'heat_transport.equipment_bundle_life','hx_shell_bore':'heat_transport.hx_shell_bore','hx_shell_wall':'heat_transport.hx_shell_wall','hx_shell_length':'heat_transport.hx_shell_length','hx_tube_length':'heat_transport.hx_tube_length'}
NAMES=['reactor_hall']+[f'sector_wing_{d}' for d in ('east','north','west','south')]+[f'sector_link_{d}' for d in ('east','north','west','south')]+['cooling_hall','cooling_annex','cooling_link','turbine_hall','cryo_coldbox','cryo_compressors','fuel_building','reactor_auxiliaries','power_supply_building','electrical_building','service_water_building','maintenance_shop','site_services_building','administration','control','security']
SUFFIXES='clear_length clear_width clear_height clear_area gross_area air_volume sub_concrete super_concrete sub_formwork super_formwork sub_rebar super_rebar'.split()
OUTPUTS='active cost_mode capacity_mode sector_length sector_width sector_height parcel_area controlled_air_volume total_clear_area total_gross_area total_air_volume blanket_packages_per_sector packages_per_sector material_capacity_volume unused_material_capacity initial_clean_required dirty_buffer_required dirty_store_required initial_ready_margin_days replacement_ready_margin_days outage_required_days outage_allowed_days outage_margin_days calendar_event_count calendar_first_event_year calendar_last_event_year cooling_clean_helium_required cooling_clean_salt_required cooling_clean_bundle_required cooling_dirty_helium_required cooling_dirty_salt_required cooling_dirty_bundle_required cooling_helium_queue_peak cooling_salt_queue_peak cooling_bundle_queue_peak cooling_initial_ready_margin_days cooling_replacement_ready_margin_days cooling_jobs_after_shutdown cooling_last_release_year cooling_carrier_moves clean_positions_allocated dirty_buffer_positions_allocated dirty_store_positions_allocated cooling_clean_helium_allocated cooling_clean_salt_allocated cooling_clean_bundle_allocated cooling_dirty_helium_allocated cooling_dirty_salt_allocated cooling_dirty_bundle_allocated initial_margin_days readiness_margin_days capacity_margin_units route_margin_m exterior_envelope_qualified sector_load_qualified contamination_procedure_qualified cooling_outage_basis_resolved provisional_room_count'.split()+[n+'_'+s for n in NAMES for s in SUFFIXES]
CIVILINPUTS=['enabled']+SUFFIXES[6:]+list(RATES)[:9]
DOC='Source: work/active/WI-068_layout-based-facilities/design.md; layout-capacity-design.md; evidence/facility-contract.md. Ref: released geometry, capacity, exact civil takeoff and account boundary. Basis: conditional conceptual scenario; unqualified shielding/loading/transport and explicit provisional equipment envelopes.'
def dumpmeta():
 (HERE/'facility-contract.json').write_text(json.dumps(dict(parameters=P,rates=RATES,upstream=UP,facilities=NAMES,quantity_suffixes=SUFFIXES,layout_outputs=OUTPUTS,civil_inputs=CIVILINPUTS),indent=2)+'\n')
def typ(v):return 'Boolean' if isinstance(v,bool) else 'Real'
def val(v):return str(v).lower() if isinstance(v,bool) else repr(float(v))
def author():
 dumpmeta()
 lines=['package mfe_facilities {','    private import ScalarValues::*;',"    calc def 'Facility Layout' {",f'        doc /* {DOC} Manual completion reuses the live calendar and emits the declared finite scalar contract; deterministic ledgers are diagnostics. */']
 for k,v in P.items():lines.append(f'        in attribute {k}_in : {typ(v)} default := {val(False if k=="facilities_enabled" else 0 if k.startswith("facilities_") else v)};')
 for k in UP:lines.append(f'        in attribute {k}_in : Real default := 0.0;')
 lines += [f'        out attribute {k} : Real;' for k in OUTPUTS]+['    }',"    calc def 'Facility Civil Cost' {",f'        doc /* {DOC} Six installed-direct commodity products, original2018 and CPI-normalized2025 purchasing power. Disabled returns zero; no repeated installation. */']
 for k in CIVILINPUTS:lines.append(f'        in attribute {k}_in : {"Boolean" if k=="enabled" else "Real"};')
 lines += [f'        out attribute {k} : Real;' for k in ['sub_cost_2018','super_cost_2018','cost_2018','cost_2025']]+['    }',"    calc def 'Facility Shipping Scope' {",f'        doc /* {DOC} Reject negative/nonfinite exclusions or sum exceedingCAS20, never clamp. */']
 for k in ['cas20','cooling_exclusion','facility_exclusion']:lines.append(f'        in attribute {k}_in : Real;')
 lines += [f'        out attribute {k} : Real;' for k in ['cooling_exclusion','facility_exclusion','remaining_shipping_base']]+['    }',"    calc def 'Facility Ventilation Cost' {",f'        doc /* {DOC} Historical PROCESS1990 empirical nuclear-ventilation relation; does not qualify airflow. */','        in attribute served_volume_in : Real;','        in attribute coefficient_in : Real;','        in attribute exponent_in : Real;','        in attribute cpi_ratio_in : Real;','        out attribute cost_1990 : Real = coefficient_in * served_volume_in ** exponent_in;','        out attribute cost_2025 : Real = cost_1990 * cpi_ratio_in;','    }',"    constraint def 'Facility Nonnegative Margin' {",f'        doc /* {DOC} Executable compatibility check only; qualification remains disclosed separately. */','        in margin_in : Real;','        margin_in >= 0.0','    }','}']
 (ROOT/'models/library/analyses/mfe_facilities.sysml').write_text('\n'.join(lines)+'\n')
 lines=['package mfe_facilities_parts {','    private import ScalarValues::*;','    private import costed_component::*;','    private import mfe_facilities::*;',"    part def 'Facility Building' :> 'Costed Component' {",f'        doc /* {DOC} Physical civil occurrence with its own quantities and cost. */','        :>> cas_code = "21";','        attribute enabled : Boolean;']
 lines += [f'        attribute {k} : Real;' for k in SUFFIXES]+[f'        attribute {k} : Real;' for k in list(RATES)[:9]]
 lines += ["        calc civil : 'Facility Civil Cost' {"]+[f'            in {k}_in = {k};' for k in CIVILINPUTS]+['        }','        :>> capital_cost = civil.cost_2025;','    }',"    part def 'Facility Service Account' :> 'Costed Component' {",f'        doc /* {DOC} Separately identified services or inherited site allowance. */','        :>> cas_code = "21";','    }','}']
 (ROOT/'models/library/structure/mfe_facilities_parts.sysml').write_text('\n'.join(lines)+'\n')
 # Surgical add at Buildings; rerun refuses to duplicate.
 path=ROOT/'models/designs/generic_mfe/mfe_subsystems.sysml';s=path.read_text();assert 'calc layout :' not in s
 s=s.replace('package mfe_subsystems {','package mfe_subsystems {\n    private import mfe_facilities::*;\n    private import mfe_facilities_parts::*;')
 add=[f'        // WI-068: {DOC}']
 for k,v in P.items():add.append(f'        attribute {k} : {typ(v)} default {val(False if k=="facilities_enabled" else 0 if k.startswith("facilities_") else v)};')
 for k,v in RATES.items():add.append(f'        attribute {k} : Real default {val(v)};')
 for k in UP:add.append(f'        attribute {k} : Real default 0.0;')
 add += ["        calc layout : 'Facility Layout' {"]+[f'            in {k}_in = {k};' for k in P|UP]+['        }']
 add += [f'        attribute {k} : Real = layout.{k};' for k in OUTPUTS]
 for n in NAMES:
  add += [f"        part {n} : 'Facility Building' {{",f'            :>> enabled = facilities_enabled;']+[f'            :>> {q} = {n}_{q};' for q in SUFFIXES]+[f'            :>> {k} = Buildings::{k};' for k in list(RATES)[:9]]+['        }']
 add += ["        calc ventilation : 'Facility Ventilation Cost' {",'            in served_volume_in = controlled_air_volume;','            in coefficient_in = ventilation_coefficient;','            in exponent_in = ventilation_exponent;','            in cpi_ratio_in = ventilation_cpi_ratio;','        }',"        part nuclear_ventilation : 'Facility Service Account' { :>> capital_cost = ventilation.cost_2025; }", "        part site_improvements : 'Facility Service Account' { :>> capital_cost = retained_site_improvements; }"]
 add += ['        attribute civil_capital : Real = '+' + '.join(n+'.capital_cost' for n in NAMES)+';','        attribute installed_facility_capital : Real = civil_capital + nuclear_ventilation.capital_cost;','        attribute layout_buildings_capital : Real = installed_facility_capital + site_improvements.capital_cost;','        attribute layout_land_cost : Real = parcel_area / 4046.8564224 * land_rate_per_acre;']
 s=s.replace("    part def 'Buildings' :> 'CAS21 Structures' {", "    part def 'Buildings' :> 'CAS21 Structures' {\n"+'\n'.join(add))
 s=s.replace(':>> capital_cost = buildings_cost.cost;',':>> capital_cost = (1.0 - cost_mode) * buildings_cost.cost + cost_mode * layout_buildings_capital;')
 # Declarations use quoted definition names in owner qualification.
 s=s.replace('Buildings::',"'Buildings'::")
 path.write_text(s)
 path=ROOT/'models/designs/stellarator_09/stellarator_plant.sysml';s=path.read_text();bind=[]
 for k,v in (P|RATES).items():bind.append(f'            :>> {k} = {val(v)} {{ doc /* {DOC} */ }}')
 s=s.replace('        part :>> buildings {','        part :>> buildings {\n'+'\n'.join(bind));path.write_text(s)
 path=ROOT/'models/designs/generic_mfe/mfe_plant.sysml';s=path.read_text().replace('package mfe_plant {','package mfe_plant {\n    private import mfe_facilities::*;')
 anchor="        part buildings : 'Buildings' {";assert anchor in s
 s=s.replace(anchor,anchor+'\n'+'\n'.join(f'            :>> {k} = {v};' for k,v in UP.items()))
 s=s.replace('        attribute preconstruction_capital : Real = precon_cost.cost;','        attribute preconstruction_capital : Real = (1.0 - buildings.cost_mode) * precon_cost.cost + buildings.cost_mode * (precon_fixed_base + buildings.layout_land_cost);')
 anchor='        attribute supplementary_decom_base : Real;'
 s=s.replace(anchor,anchor+'\n        attribute facility_shipping_exclusion : Real = buildings.cost_mode * (1.0 + contingency_rate) * buildings.installed_facility_capital;\n        calc shipping_scope : \'Facility Shipping Scope\' {\n            in cas20_in = cas20_capital;\n            in cooling_exclusion_in = heat_transport.shipping_exclusion;\n            in facility_exclusion_in = facility_shipping_exclusion;\n        }')
 s=s.replace('in delivered_shipping_exclusion_in = heat_transport.shipping_exclusion;','in delivered_shipping_exclusion_in = shipping_scope.cooling_exclusion;\n            in facility_exclusion_in = shipping_scope.facility_exclusion;')
 assertions={'facility_initial_ready':'initial_margin_days','facility_replacement_ready':'readiness_margin_days','facility_outage_ok':'outage_margin_days','facility_capacity_ok':'capacity_margin_units','facility_routes_ok':'route_margin_m'}
 s=s.replace('        // MFE-divergent power core', '        attribute radial_outer_radius : Real = rb.outer_radius;\n'+'\n'.join(f"        assert constraint {name} : 'Facility Nonnegative Margin' {{ in margin_in = buildings.{out}; }}" for name,out in assertions.items())+'\n        // MFE-divergent power core',1);path.write_text(s)
 path=ROOT/'models/library/analyses/mfe_plasma_scaling.sysml';s=path.read_text().replace('        out attribute r_coil : Real = vessel_or;','        out attribute outer_radius : Real = lt_shield_or;\n        out attribute r_coil : Real = vessel_or;');path.write_text(s)
 path=ROOT/'models/library/structure/mfe_plant_systems.sysml';s=path.read_text();anchor='        attribute coolant_cost : Real = cooling_selection.cost;'
 # Geometry constants remain in their owning subsystem; unchanged existing costing constants verified separately.
 s=s.replace(anchor,anchor+'\n        attribute hx_shell_bore : Real = 3.2;\n        attribute hx_shell_wall : Real = equipment_shell_wall;\n        attribute hx_shell_length : Real = 13.0;\n        attribute hx_tube_length : Real = 11.6;\n        attribute helium_machine_count : Real = equipment.circulator_count;\n        attribute salt_machine_count : Real = equipment.salt_pump_count;\n        attribute exchanger_count : Real = equipment.ihx_count;');path.write_text(s)
 path=ROOT/'models/library/analyses/mfe_account_costs.sysml';s=path.read_text().replace('        in attribute delivered_shipping_exclusion_in : Real default 0.0;','        in attribute delivered_shipping_exclusion_in : Real default 0.0;\n        in attribute facility_exclusion_in : Real default 0.0;').replace('shipping_frac * (cas20 - delivered_shipping_exclusion_in)','shipping_frac * (cas20 - delivered_shipping_exclusion_in - facility_exclusion_in)');path.write_text(s)
 path=ROOT/'tests/model_families.py';s=path.read_text().replace('        "analyses/mfe_account_costs.sysml",','        "analyses/mfe_account_costs.sysml",\n        "analyses/mfe_facilities.sysml",\n        "structure/mfe_facilities_parts.sysml",');path.write_text(s)
if __name__=='__main__':author()
