import json,hashlib,collections
from pathlib import Path
H=Path(__file__).resolve().parents[1];R=H/'results'
def read(p):return json.loads(p.read_text())
def dump(p,v):p.write_text(json.dumps(v,indent=2)+'\n')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
rows=read(R/'cases.json'); extra=read(R/'additional-verification.json'); assert extra['outcome']=='pass'
cat=read(R/'constraint-catalog.json'); counts={cid:dict(collections.Counter(r['verdicts'][cid] for r in rows)) for cid in cat}
summary={'cases':len(rows),'feasible':sum(r['feasible'] for r in rows),'constraint_counts':counts,'violations_by_case':{r['label']:[cid for cid,s in r['verdicts'].items() if s!='satisfied'] for r in rows},'duplicate_baseline_controls':{'proposal_indices':[2,6,8],'labels':[rows[i]['label'] for i in [2,6,8]],'all_141_outputs_identical':all(rows[i]['values']==rows[2]['values'] for i in [6,8])}}
# Attribute every exported cost, annual and capital channel by its actual delta.
cost_names=list(read(H/'preparation/required-channels.json'))[24:68]
cost_names+=['cas72_annual','calendar_availability','cas90_1cfe','lcoe_1cfe']
summary['cost_account_deltas']=[{'proposal_index':r['proposal_index'],'label':r['label'],'deltas':{k:r['values'][k]-rows[2]['values'][k] for k in cost_names}} for r in rows]
dump(R/'report-summary.json',summary)
# Historical bridge: independently reconstruct actual numerator from copied scalar values.
historical=read(H/'context/inherited-baseline-attribution.json');scalars=historical['all_compared_scalars']; inp=read(R/'package-inputs.json');P='stellarator_09__stellaris__';d=inp[P+'discount_rate'];N=int(inp[P+'operational_years']);t=inp[P+'construction_years'];crf=1/sum((1+d)**(-i) for i in range(1,N+1))
old={k:v['before'] for k,v in scalars.items()}
# Full copied inventory supplies these recorded current/previous values.
annual=old['cas70_calc__annual_total'];energy=8760*old['pb__p_net']*old['calendar__availability'];head=old['total_capital__total_capital']*(1+d)**(t/2)*crf;comp=(old['overnight_capital__overnight_capital']+old['idc__cost'])*crf
bridge={'evidence_class':'Copied inherited model-audit scalar ledger, recomputed accounting only; old package was not rerun','before':{'capital_head':head,'capital_comparison':comp,'annual':annual,'energy':energy,'headline_lcoe':old['lcoe_calc__lcoe'],'comparison_lcoe':old['lcoe_1cfe_calc__lcoe']},'after':extra['finance'][2],'copied_bridge':historical['financial_bridge']}
assert abs((head+annual)/energy-old['lcoe_calc__lcoe']) < 1e-9
assert abs((comp+annual)/energy-old['lcoe_1cfe_calc__lcoe']) < 1e-9
dump(R/'inherited-bridge-reconstruction.json',bridge)
text=(H/'record.md').read_text();sections={i:text.split(f'## {i}. ',1)[1].split('\n',1)[1].split(f'## {i+1}. ',1)[0].strip() for i in [2,7,8]}
out=[]
def sec(n,title,body):out.append(f'## {n}. {title}\n\n{body.strip()}\n')
sec(1,'Study header','''- **Study id:** 20260911-operating-heating
- **Package:** stellarator_tea
- **Date executed:** 2026-09-11
- **Executor:** Native T-019 execution agent, under parent authorization recorded in preparation/dispositions.md.
- **Mode:** execute; results and draft report ready for fresh final review. Final registration and commit remain pending.
- **Arms:** arm-reserve, arm-retained-alpha, arm-density, arm-signed-bracket.''')
sec(2,'Intake',sections[2])
sec(3,'Objective and result','''The study separates installed heating reserve from operating demand. At fixed plasma, increasing installed electrical capacity from 100 to 120 MW changes heating procurement from $264,145,000 to $316,974,000 while leaving all checked operating flows and annual energy unchanged. Headline LCOE rises from **224.269233 to 225.413073 $/MWh**, on sealed candidate a9514eb6505dea1589f47cb20bd004e480d61b3be98e7d793bf195b1b2d773b0 with the captured runtime in `results/runtime.json` (no era adapter/pin). The increase is entirely capital attribution under the retained finance convention.

At fixed heating installation, raising retained-alpha fraction from 0.95 to 0.96 reduces signed operating coupled demand from 49.079601 to 43.769169 MW and headline LCOE to 222.326284 $/MWh. Installed heating procurement stays fixed. Density changes also alter fusion, ash, confinement, radiation, equipment sizing and calendar outcomes; their economic changes are not an isolated auxiliary-heating intervention.

**Zero of fifteen cases is fully feasible.** Every case violates the existing divertor target screen. Finite LCOE at negative demand is an invalid burn-hold diagnostic, never an improvement. The lowest displayed LCOE is not an optimum claim.

All fifty previously audited cost, annual, calendar and finance modules have their actual inputs, outputs and baseline deltas in `results/cost-operands.json`. Installed delivered power drives heating procurement. Held heating procurement in demand cases coexists with legitimate changes in retained design-point turbine, heat-rejection, electric and indirect accounts; replacement amounts and annual accounts can change with those priced components. These are modeled sizing consequences, not repricing purchased heating or a pure running-expense change. The current bindings and classifications are copied in `context/inherited-cost-operand-coverage.json`.

Both objective channels, `stellarator_09__stellaris__lcoe_calc__lcoe` and `stellarator_09__stellaris__lcoe_1cfe_calc__lcoe`, are exported in `results/points.csv`. All fifteen case identities, inputs, 141 numeric channels and verdicts are in `results/cases.json`; actual capital numerators, annual accounts, energy and both additive LCOE bridges are in `results/additional-verification.json`. Baseline controls at proposal indices 2, 6 and 8 have identical outputs and remain separately labeled with their actual native candidate IDs.

For the 0.95→0.96 retained-alpha case, the headline change is −1.942948499 $/MWh: capital +0.014242582, annual accounts +0.025110437, energy −1.982301518. The comparison change is −1.905635676: capital +0.013934861, annual +0.025110437, energy −1.944680974. Both bridges use the measured numerator operands, never an LCOE-derived numerator. Reserve adds +1.143840050 headline and +1.119126564 comparison, with zero annual and energy contributions.

The historical pre-repair headline 224.609524728→224.269232884 $/MWh is a copied audit comparator. Its −0.340291844 change has capital +0.002479292, annual +0.004380321 and energy −0.347151457 contributions. The historical comparison change is −0.333756416, with +0.002425725 capital, +0.004380321 annual and −0.340562462 energy. `results/inherited-bridge-reconstruction.json` carries the actual historical and current numerators/energy and `context/inherited-baseline-attribution.json` carries the full source ledger. The old package was not rerun.

All figures depend on the single sealed identity in `results/package_identity.json`, the runtime in `results/runtime.json`, and unchanged empirical, cost, calendar and finance assumptions. These are modeled design-point economics, not a plant feasibility certificate.''')
ct=['| constraint_id | source_local_identity | Status | Note |','|---|---|---|---|']
for cid,c in cat.items():
 counts_this=counts[cid]; nums=', '.join(f'{s}: {counts_this.get(s,0)}/15' for s in ['satisfied','violated','indeterminate']);ct.append(f"| {cid} | {c['source_local_identity']} | {nums} | Exact case locations in results/report-summary.json. |")
sec(4,'Constraint outcomes','Every native case completed. All eighteen assertions are retained by both qualified constraint ID and source local identity.\n\n'+'\n'.join(ct)+'\n\nNo verdict was suppressed or reclassified. Divertor violations occur in all fifteen cases; sustainment additionally fails at installed-80 and alpha-0.94. Wall and loop-capacity screens fail for density multipliers 1.1–1.4 and both signed-bracket cases. Burn hold fails at density-1.4 and negative-near-zero. All other native checks are satisfied throughout.')
sec(5,'Framing','''**As proposed at intake.** Installed capacity, retained-alpha fraction and density were sensitivity-framed interventions. Temperature was proposed as sensitivity, then declined because the preliminary candidate range did not provide the signed-demand diagnostic. All four indicators remain in the record.

**As judged after the run.** All three executed axes retain sensitivity framing. Reserve isolates procurement from operation; retained alpha changes operating demand with compensating divertor heat; density changes the coupled plasma solution. The negative brackets locate diagnostic signs, not an engineering boundary. Temperature remains declined and unjudged by execution. None of these observations supports a search optimum, a caught feasible-region edge, or an engineering operating window. Policy H1's search feasible-fraction bar does not apply to these sensitivities; the actual 0/15 feasibility is still reported.''')
axis_text=[]
responses={'p_wallplug_heat':'Reserve leaves operating heat, source/loop/net/divertor channels and calendar availability unchanged. Procurement and downstream capital/IDC increase. Installed-80 fails sustainment; the exact baseline-derived equality case satisfies it. Every reserve case violates divertor heat.','f_alpha_fast':'At baseline density, increasing retained fraction from 0.94 to 0.96 changes demand 54.390032→43.769169 MW. Alpha-0.94 also violates sustainment; all three violate divertor heat. Retained alpha plus demanded auxiliary heat exactly compensates within floating tolerance, so divertor absorbed heat and target peak stay fixed while source heat and electricity change. At density 6.578e20 the two coordinated brackets give +0.008164627807332181 and −0.008164627807559555 MW; the negative case fails burn hold, and both fail divertor, wall and loop capacity.','n_e0':'Density multipliers 1.0→1.4 change demand 49.079601→−15.308579 MW, net power 1013.931933→1596.518763 MW and target peak 10.517842→16.316537 MW/m². Multipliers 1.1–1.4 fail wall and loop capacity; 1.4 also fails burn hold. Divertor heat fails everywhere. Fusion, ash, confinement, radiation and calendar changes prevent attribution solely to heating.','T_i0':'Not applicable: declined before execution. Preliminary temperature probes remain available; no executed response is claimed.'}
for axis,response in responses.items():
 axis_text.append(f'#### {axis} — feasible structure (search framing)\n\n**Applies:** not applicable — sensitivity-framed'+(' and declined.' if axis=='T_i0' else '.')+f'\n\n#### {axis} — observed response (sensitivity framing)\n\n**Applies:** '+('not applicable — declined.' if axis=='T_i0' else 'yes.')+f'\n\n{response} No physical boundary claim is made.')
sec(6,'Per-axis account','\n\n'.join(axis_text));sec(7,'Axis groups',sections[7]);sec(8,'Indicators and rulings',sections[8])
gates=read(R/'preflight.json');table=['| Gate | Outcome | Detail |','|---|---|---|']+[f"| {g['gate']} | {g['status']} | {g['detail']} |" for g in gates['gates']]
sec(9,'Preflight results','\n'.join(table)+'\n\nAll six gates ran after exact pinned baseline execution and before the formal oracle scan. `results/preflight.json` records the gated identity and baseline documents, input digests and tool identity. `results/baseline_result.json` reproduces the pinned headline exactly and all eighteen expected verdicts. Post-run and post-verification cleanliness also pass, in their named results documents.')
sec(10,'Execution route and why','''**Route:** study-local direct-API. The baseline exercised the stock strict loader before preflight passed. A single PreparedListStrategy/StudyRunner run then executed all fifteen coordinated proposals through `study.py::run_all`, sharing one store because all arms share one fingerprint. No hand-written evaluator sweep was used.

**Glue disclosure:** glue ledger: none. There is no adapter or harness-supplied model result. `execution/run.py` exports only after validating all required outputs, exact catalog verdict membership, persisted proposal IDs, original raw proposals and actual case inputs. Labels join by the stock positional proposal ID and persisted candidate ID, never by query order. The baseline uses a separate native preparation store; it is not another study arm.''')
sec(11,'Study definition and window provenance','''The fifteen executed cases are an engineered sensitivity window. `results/oracle-window-scan.json` records a fresh oracle evaluation of every candidate after all baseline/preflight gates. `results/window-freeze.json` records the window decision made before the stock sweep. It confirms the reserve equality against both generated baseline and oracle demand before freezing its unchanged value. The scan retains opposite signed brackets and reveals the density-coupled violations. There is no sourced engineering density envelope or claimed feasible anchor.

The preserved original sixteen-case proposal and preliminary probes served preparation only. Fresh critique declined the ill-conditioned algebraic center before any TEAx execution, retaining its nonzero preliminary residual and two flanks. The effective fifteen-case proposal, including metadata correction timing, is `preparation/execution-proposal.json`; `execution/corrections.md` records the correction. No result-dependent point retuning occurred. Temperature remains declined. Geometry is held at the pinned baseline and satisfies the existing radial-stack mask. No negative-demand validity mask was applied.''')
sec(12,'Cross-fingerprint correlation and what it means','Single fingerprint — no cross-arm correlation needed. Copied historical model-audit comparison is an inherited ledger, not another executed arm or a rerun of an old package. No historical plant-closure study window, regrade, or engineering closure is inherited.')
sec(13,'Verification','''The stock verifier passed on every one of the fifteen completed cases: 25 objective/predicate channels and all eighteen independently re-derived predicates, covering every observed verdict combination. The additional checker passed 2,115 comparisons across all 141 required oracle channels and 566 identities, finance checks and invariance checks. The source/loop/thermal/net/divertor identities use named captured inputs and channels. Net power is independently checked against every named recirculating load. Finance uses finite discount sums and actual levelized annual accounts.

The first additional checker failed two alpha-demand-delta checks because it substituted the source-heat ratio for the distinct recorded sustainment fraction. Both failed results and checker are preserved. Parent authorized a checker-only correction to the captured sustainment input; all other verification tolerances and executed evidence stayed unchanged. `execution/corrections.md` gives the cause, timing and references. This failure is not represented as a first-pass verification success.

The retained model uses 0.2002 for sustainment alpha and 3.52/17.58 for source heat. They are close but unequal. The checker correction respects both authored bases; it does not reconcile them or certify a single exact physical convention. Copied source files and package inputs make that difference recoverable.

Translation parity is not independent validation of source assumptions. Some copied oracle statement forms mirror historical modules, and outputs held fixed by construction are not fresh engineering verification. The study does not rerun 1costingFE; the copied audit records where direct registered-source comparison was applicable. Exact native component zero in `context/inherited-boundary-results.json` remains inherited component evidence. No full-plant exact-zero case was executed.''')
sec(14,'Review outcomes','''| Lens | Verdict | Disposition |
|---|---|---|
| Fresh pre-execution framing critique | FINDINGS | F1: one shared store implemented; F2: algebraic center declined. Original named verdict preserved in preparation/pre-execution-review.md; parent dispositions authorize execution. |
| Executor correctness checks | First additional checker failed; corrected checks and stock verification pass | Failed evidence preserved; checker transcription corrected under parent authorization. This is execution verification, not independent final review. |
| Fresh correctness, honesty and readability review | Pending | Parent will arrange a fresh non-author review before registration and final freeze. |''')
findings=[('1','model','Reserve now changes procurement without changing the measured operating ledger.','Proposed: retain bounded WI-050 evidence for goal review; no engineering closure claim.','work/active/WI-050_mfe-coherent-operating-heating'),('2','model','All fifteen cases remain divertor-violating; high-density diagnostics add wall/loop violations and negative demand remains invalid.','Proposed: route remaining engineering coverage to a future scoped goal decision; no feasible-plant or optimum claim.','work/orchestration/goals/fusion-audit-remediation'),('3','model','Sustainment retains alpha fraction 0.2002 while source heat retains 3.52/17.58; verified arithmetic does not make these one physical convention.','Proposed: assess inherited basis consistency in a separately authorized modeling review; no accepted residual or source waiver.','work/orchestration/goals/fusion-audit-remediation'),('4','process','Pre-execution review caught per-arm store splitting and an ill-conditioned algebraic center.','Corrected before execution: shared store, center declined, brackets retained; named review remains FINDINGS.','preparation/dispositions.md'),('5','process','Additional checker initially conflated the two retained alpha bases.','Corrected checker only under parent authorization; failed script/results retained and fresh final review required.','execution/corrections.md')]
ft=['| Id | Kind | Finding | Disposition | Home |','|---|---|---|---|---|']+[f'| `20260911-operating-heating#{n}` | {k} | {f} | {d} | {h} |' for n,k,f,d,h in findings]
sec(15,'Findings','\n'.join(ft)+'\n\nThese are proposed first-sighting rows for final review. Discovery-log registration and the final commit are pending parent authorization; no goal disposition is executed by this draft.')
# Snapshot built from resolved values below.
manifest=read(H/'context/manifest.json'); indicators=read(H/'indicators.json'); runtime=read(R/'runtime.json');compat=read(R/'store-compatibility.json'); ver=read(R/'verification_summary.json')
fp=manifest['fingerprints'];inputfp=indicators['package']['indicator_input_fingerprint']
artifacts=[{'path':str(p.relative_to(H)),'sha256':sha(p)} for p in R.rglob('*') if p.is_file() and not p.is_symlink()]
context_artifacts=[{'path':str(p.relative_to(H)),'sha256':sha(p)} for p in (H/'context').rglob('*') if p.is_file()]
content={k:manifest[k] for k in ['ties','objective_catalog','baseline','oracle']};content['fingerprint_names']=['indicator_inputs','recorded_provenance.executable_fingerprint','recorded_provenance.semantic_fingerprint'];from scripts.study import common
content['oracle']['source_digest']=common.tool_source_digest(('exploration/stellarator_e2e/studies/oracle_entry.py','exploration/stellarator_e2e/verify_stellaris.py'))
content['oracle']['copied_sources']=['context/oracle_entry.py','context/verify_stellaris.py']
snapshot={'snapshot_schema_version':'1','status':'DRAFT ready for fresh final review; not frozen','study_id':H.name,'package':{'path':manifest['package']['path'],'package_name':'stellarator_tea','repo_commit':runtime['repo_revision'],'git_clean':True},'fingerprints':{'indicator_inputs':inputfp,'recorded_provenance.executable_fingerprint':fp['recorded_provenance']['executable_fingerprint'],'recorded_provenance.semantic_fingerprint':fp['recorded_provenance']['semantic_fingerprint']},'manifest':{'path':'context/manifest.json','schema_version':manifest['schema_version'],'digest':sha(H/'context/manifest.json'),'content_used':content},'stores':[{'store_id':'operating-heating-shared','path':str((R/'_study/20260911-operating-heating.db').relative_to(H)),'sha256':sha(R/'_study/20260911-operating-heating.db'),'compatibility_tuple':compat}],'arms':[],'tools':[indicators['tool'],gates['tool'],ver['tool']],'teax':{'revision':runtime['teax_revision'],'era_pin':None,'runtime':'results/runtime.json'},'indicators':{'path':'indicators.json','sha256':sha(H/'indicators.json'),'output_schema_version':indicators['schema_version'],'axis_declaration':{'path':'axes.json','schema_version':'study-axis-declaration/v1','digest':sha(H/'axes.json'),'groups_declared':[g['axis'] for g in read(H/'axes.json')['groups']],'subset':False}},'context_artifacts':context_artifacts,'execution_artifacts':[{'path':str(p.relative_to(H)),'sha256':sha(p)} for p in (H/'execution').glob('*') if p.is_file()],'result_artifacts':artifacts,'baseline_store_note':'Native baseline preparation store is under results/_work; not an executed comparison arm. Native database/evidence files may remain local with hashes; exported complete values are committed-facing evidence.'}
freeze=read(R/'window-freeze.json')
for a in freeze['proposal']['arms']:
 snapshot['arms'].append({'arm_id':a['arm_id'],'store_id':'operating-heating-shared','effective_executable_fingerprint':{'value':compat['executable_fingerprint'],'inputs':None,'no_adapter':True,'note':'Stock strict route; sealed fingerprint is identity'},'entry_models':read(R/'entry-models.json'),'strategy':'prepared-list/v1','window':{'bounds':{'cases':a['cases']},'provenance':'engineered'},'verification':{'command':'.codex-test/run bash -c '+repr('PYTHONPATH="$PWD:$STOP_PARSER_TEAX_ROOT/packages/teax-simkit" STUDY_REQUIRE_TEAX=1 python scripts/study/verify.py --package exploration/stellarator_e2e/generated --manifest exploration/stellarator_e2e/studies/manifest.json --identity exploration/stellarator_e2e/studies/20260911-operating-heating/results/package_identity.json --store exploration/stellarator_e2e/studies/20260911-operating-heating/results/_study/20260911-operating-heating.db --sample-size 15 --out exploration/stellarator_e2e/studies/20260911-operating-heating/results/verification_summary.json'),'tool_revision':ver['tool'],'sampling_scheme':'all fifteen completed native cases; all verdict strata','tolerance':{'stock_relative':1e-9,'additional_identity_relative':1e-9,'additional_identity_absolute':1e-9},'summary_sha256':sha(R/'verification_summary.json')},'glue_ledger':[],'glue_ledger_none':True,'artifacts':artifacts})
dump(H/'snapshot.json',snapshot)
sec(16,'Snapshot',f"- **File:** snapshot.json\n- **sha256:** {sha(H/'snapshot.json')}\n- **Schema version:** 1\n\nDraft snapshot resolved from present artifacts. Parent will refresh after fresh review and before final registration/freeze. All result and copied-context artifacts carry digests; study arms reference one complete compatibility tuple.")
sec(17,'What this record does not contain','''There is no fresh final review, discovery-log registration, final record commit, administrator synthesis or goal disposition yet. There is no full-plant exact-zero execution, old-package rerun, engineering operating envelope, completed historical plant-closure window, new source certification or regrade. The native databases and evidence bodies may remain local; their paths/digests and complete exported numerical cases, proposal mappings, runtime, catalog, package inputs and schemas are retained for record-only administration.

Copied audits preserve the inherited ten Level-2 findings, 227 inherited plus two accepted Level-6 diagnostic additions, legacy trace limits and excluded historical exporter failures. The package audit records 164 passes, one optional historical skip and eight publication checks; 86 excluded historical-export failures remain disclosed. These are bounded inherited audit facts, not tests rerun by T-019. Four positive/unit efficiency-domain constraints execute in this study, but the held efficiencies and engineering omissions remain assumptions. No source quarantine was bypassed.''')
body='\n'.join(out);assert '<' not in body
(H/'record.md').write_text(body)
print('Draft report and snapshot written')
