"""Render complete scalar attribution and reviewed cost operand coverage."""
from pathlib import Path
import json,subprocess
import yaml
h=Path(__file__).resolve().parent;p='stellarator_09__stellaris__'
a=json.loads((h/'baseline-attribution.json').read_text());r=json.loads((h/'results.json').read_text())
models=Path((h/'scratch.txt').read_text().strip())/'models'
pkg=models.parent/'generated'
m=yaml.safe_load((pkg/'pipelines/pipeline.yaml').read_text())['modules']
old=yaml.safe_load(subprocess.check_output(['git','show','546218a5:exploration/stellarator_e2e/generated/pipelines/pipeline.yaml']))['modules']
selectors=['cost','capital','supplement','installation','coolant','remote_handling','waste','owner','indirect','contingency','other_rpe','fuel_handling','aux_cooling','cas71','cas72','cas80','cas90','cas70','calendar','lcoe','reactor_equipment_subtotal','idc','fuel_calc']
selected={k:v for k,v in m.items() if k.startswith(p) and any(t in k.removeprefix(p) for t in selectors)}
coverage={}
for name,module in selected.items():
 if name not in old: continue
 assert module['inputs']==old[name]['inputs'],name
 outputs={key.removeprefix(p):{'baseline':v,'reserve':r['reserve']['outputs'][key],'demand':r['demand']['outputs'][key]} for key,v in r['baseline']['outputs'].items() if key.startswith(name+'__')}
 label='installed procurement' if name==p+'heating_cost' else ('calendar/annual/financial propagation' if any(t in name for t in ['calendar','cas70','cas71','cas80','cas90','lcoe','idc']) else 'reviewed design-point sizing or dependent capital rollup')
 coverage[name.removeprefix(p)]={'classification':label,'inputs_unchanged':True,'inputs':module['inputs'],'outputs':outputs}
(h/'cost-operand-coverage.json').write_text(json.dumps(coverage,indent=2)+'\n')
lines=['# Production baseline and cost attribution','', '[AGENT] Production matches the deposited independent conservation and explicit financial formulas. Every common scalar from T-015 is compared in `baseline-attribution.json`; the table below contains every changed scalar, regardless of materiality. The original first-attempt generated-body failure remains in `attempt-1-preserved-auto-body/`. Correcting that body restores the unchanged required-minus-installed diagnostic, reducing the prototype\'s 73 changed scalars to 72.','','Heating procurement remains $264145000 at baseline and rises to $316974000 under the 120 MW reserve control. Online source, loop, gross/net, divertor heat, calendar and annual accounts remain exactly invariant under reserve. The signed diagnostic changes from -0.920399212073221 to -10.920399212073221 MW. The f_alpha_fast=0.96 demand control holds procurement and fusion fixed. Its retained alpha gain equals its auxiliary reduction, so divertor absorbed heat stays fixed.','','The baseline is a diagnostic operating point with divertor peak 10.517841546 MW/m^2 above the 10 MW/m^2 bound. Seventeen assertions are satisfied and one violated. The coupling=0.8 control additionally violates installed capacity. Zero efficiency rejects execution; negative and over-one values remain explicitly violated diagnostics.','','## Independent financial bridge','','Capital charges are evaluated directly from overnight capital, discount rate, construction time and operating life. They are never inferred from LCOE. Each bridge uses old annual energy for the capital/annual contributions and the new numerator for the energy contribution. The checked residual is floating-point roundoff.','','| LCOE | Capital effect $/MWh | Annual effect $/MWh | Energy effect $/MWh | Total change $/MWh | Residual |','|---|---:|---:|---:|---:|---:|']
for k,v in a['financial_bridge'].items():lines.append('| '+k+' | '+' | '.join(f'{v[x]:.12g}' for x in ['capital','annual','energy','delta','residual'])+' |')
lines+=['','## Reviewed cost coverage','','`cost-operand-coverage.json` records the actual generated input bindings and baseline/reserve/demand outputs for all selected cost, rollup, annual, calendar and LCOE modules. Every recorded input binding is identical to entering revision 546218a5. The unchanged authored cost, lifecycle, loop and DCF files are verified byte-for-byte in the focused cost test. The two pre-production classification tables in `../design.md` govern these classifications; no additional cost operand was found.','','Installed ECRH capacity and the direct NBI/ICRF/LHCD procurement inputs are unchanged. Blanket, shield and divertor capital retain thermal sizing; structure, vessel, supplies, electric and miscellaneous plant retain gross sizing; turbine retains cycle-output sizing. Buildings combine fixed/fusion, thermal and gross terms; preconstruction land and O&M staffing follow net power. Remote handling follows gross; coolant follows net and thermal; auxiliary cooling follows thermal, while its cryoplant term stays fixed with geometry. Waste and I&C follow thermal; fuel handling, other reactor equipment and owner costs follow net. Supplementary costs retain their capital-based and net-based terms.','','The power-core subtotal adds heating and other equipment; installation follows the core plus remote handling; CAS22 includes both. BOP and geometry-based CAS27/CAS28 stay fixed under reserve. CAS2x, contingency, CAS20, CAS30 and supplementary shipping/tax/insurance pass the reserve increase through their existing formulas. Spares follow unchanged BOP; startup/decommissioning follow unchanged net power. Overnight and IDC follow those totals. Replacement event costs follow blanket plus divertor; calendar dates depend on the unchanged neutron load. CAS71 follows staffing, CAS72 discounts dated events, CAS80 follows annual fusion time, and each LCOE uses its unchanged capital and annual-energy convention.','','| Generated cost/rollup module | Classification | Bindings |','|---|---|---|']
for k,v in coverage.items():lines.append(f'| `{k}` | {v["classification"]} | Unchanged; exact operands in companion JSON |')
lines+=['','## Every changed scalar against T-015','','| Scalar | Before | After | Delta |','|---|---:|---:|---:|']
for k,v in a['all_compared_scalars'].items():
 if v['delta']!=0: lines.append('| `'+k+'` | '+' | '.join(f'{v[x]:.12g}' for x in ['before','after','delta'])+' |')
unchanged=[k for k,v in a['all_compared_scalars'].items() if v['delta']==0]
lines+=['','## Unchanged scalars','',f'{len(unchanged)} common scalars are unchanged. The full exact list and values are retained in the companion JSON. Geometry, fusion, plasma sustainment, coil/casing/cold-volume quantities and source-held efficiencies do not depend on installed reserve or the repaired downstream heating route. Procurement remains installed; calendar timing remains neutron-fluence-driven. The installed-capacity diagnostic retains its original meaning. New operating outputs and efficiency assertions have no historical counterpart.']
(h/'baseline-attribution.md').write_text('\n'.join(lines)+'\n')
print('Coverage',len(coverage),'changed',a['changed_count'],'unchanged',len(unchanged))
