"""Native WI-050 acceptance; invoke with the repository .codex-test/run launcher."""
from __future__ import annotations
import hashlib
import json
import os
import shutil
import sys
import tempfile
from collections.abc import Mapping
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[4]
HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(Path(os.environ['STOP_PARSER_TEAX_ROOT']) / 'packages/teax-simkit'))
from tests.model_families import MFE, materialize_canonical_subset
from sysml_codegen.cli import GenerationConfig, run_codegen
from simkit.evaluation.evaluator import PreparedEvaluator
from simkit.evaluation.package_load import ProvisionalPackageLoader
from simkit.study.bridge import CandidateBridge

P = 'stellarator_09__stellaris__'
CASES = {'baseline': {}, 'reserve': {'p_wallplug_heat':120.0},
         'demand':{'f_alpha_fast':0.96}, 'efficiency':{'eta_couple_heat':0.8},
         'availability':{'unplanned_fraction':0.10},
         'negative_efficiency':{'eta_source_heat':-0.5},
         'zero_efficiency':{'eta_source_heat':0.0},
         'overunit_efficiency':{'eta_source_heat':1.01}}

def dump(path, value):
    path.write_text(json.dumps(value, indent=2, default=lambda v:dict(v) if isinstance(v,Mapping) else str(v))+'\n')

def hashes(root):
    return {str(f.relative_to(root)):hashlib.sha256(f.read_bytes()).hexdigest()
            for f in sorted(root.rglob('*')) if f.is_file() and '__pycache__' not in str(f) and f.suffix != '.pyc'}

def evaluator(package, name, link):
    ev = PreparedEvaluator(ProvisionalPackageLoader(package,name,link,strict=True),package/'pipelines/pipeline.yaml',expects_constraint_report=True)
    return ev, CandidateBridge(ev.entry_models)

def execute(ev, bridge, changes):
    try:
        r=ev.evaluate(bridge.build(changes))
        return {'outputs':dict(r.outputs),'responses':dict(r.responses),'report':r.report}
    except Exception as exc:
        return {'error':type(exc).__name__,'message':str(exc)}

def run(destination=HERE):
    destination.mkdir(parents=True, exist_ok=True)
    tmp=Path(tempfile.mkdtemp(prefix='wi050-implementation-'))
    models=materialize_canonical_subset(MFE,tmp/'models')
    package=tmp/'generated'
    shipped=ROOT/'exploration/stellarator_e2e/generated'
    shutil.copytree(shipped,package)
    # Existing preserve mode retains every handwritten-directory file, including
    # autogenerated bodies. Refresh this changed AUTO_IMPLEMENTED calculation.
    auto_body=package/'handwritten/mfe_divertor_heat/divertor_heat_ledger_impl.py'
    assert 'AUTO_IMPLEMENTED = True' in auto_body.read_text().split('SysML Source:')[0]
    auto_body.unlink()
    before=hashes(package)
    dump(destination/'execution-start.json',{'utc':datetime.now(timezone.utc).isoformat(),
        'expectations_sha256':hashlib.sha256((HERE/'expectations.md').read_bytes()).hexdigest(),
        'command':'.codex-test/run python '+str(Path(__file__).relative_to(ROOT)),
        'scratch':str(tmp),'source_hashes':hashes(models),'entering_package_hashes':before})
    assert run_codegen(GenerationConfig(models_path=models,output_path=package,package_name='stellarator_tea',overwrite=True,preserve_handwritten=True))
    ev,bridge=evaluator(package,'stellarator_tea',tmp/'link')
    results={name:execute(ev,bridge,{P+k:v for k,v in changes.items()}) for name,changes in CASES.items()}
    dump(destination/'results.json',results)
    after=hashes(package)
    normative={k:v for k,v in before.items() if k.startswith('handwritten/') and k.endswith('_impl.py') and 'AUTO_IMPLEMENTED = True' not in (shipped/k).read_text().split('SysML Source:')[0]}
    assert len(normative)==4,normative
    assert all(after[k]==v for k,v in normative.items())
    dump(destination/'normative-handwritten.json',normative)
    dump(destination/'package-hashes.json',after)
    inputs={}
    for path in (package/'inputs').glob('*.json'): inputs.update(json.loads(path.read_text()))
    dump(destination/'inputs.json',inputs)
    (destination/'scratch.txt').write_text(str(tmp)+'\n')
    return tmp,results,inputs

if __name__=='__main__':
    scratch,_,_=run()
    print('Acceptance package:',scratch)
