from pydantic import BaseModel, Field


class CombinationsLoopBraytonParams(BaseModel):
    """Parameters from combinations_loop_brayton.

    Generated from SysML calculation definitions.
    """
    combinations_loop_brayton__loop_brayton__blanket_source__q_source: float = Field(default=3125.9322770825056, description="Entry point: q_source")
    combinations_loop_brayton__loop_brayton__checks__energy_tolerance: float = Field(default=1e-06, description="Entry point: energy_tolerance")
    combinations_loop_brayton__loop_brayton__compressor_1__efficiency: float = Field(default=0.89, description="Entry point: efficiency")
    combinations_loop_brayton__loop_brayton__compressor_1__selected_ratio: float = Field(default=1.5182944859378311, description="Entry point: selected_ratio")
    combinations_loop_brayton__loop_brayton__compressor_2__efficiency: float = Field(default=0.89, description="Entry point: efficiency")
    combinations_loop_brayton__loop_brayton__compressor_2__selected_ratio: float = Field(default=1.5182944859378311, description="Entry point: selected_ratio")
    combinations_loop_brayton__loop_brayton__compressor_3__efficiency: float = Field(default=0.89, description="Entry point: efficiency")
    combinations_loop_brayton__loop_brayton__compressor_3__selected_ratio: float = Field(default=1.5182944859378311, description="Entry point: selected_ratio")
    combinations_loop_brayton__loop_brayton__compressor_capacity__assumed_supported: bool = Field(default=1.0, description="Entry point: assumed_supported")
    combinations_loop_brayton__loop_brayton__compressor_capacity__demand_available: bool = Field(default=1.0, description="Entry point: demand_available")
    combinations_loop_brayton__loop_brayton__compressor_capacity__scenario_applicable: bool = Field(default=1.0, description="Entry point: scenario_applicable")
    combinations_loop_brayton__loop_brayton__compressor_capacity__selected_rating: float = Field(default=1600.0, description="Entry point: selected_rating")
    combinations_loop_brayton__loop_brayton__cycle__cp: float = Field(default=5193.0, description="Entry point: cp")
    combinations_loop_brayton__loop_brayton__cycle__gamma: float = Field(default=1.6666666666666667, description="Entry point: gamma")
    combinations_loop_brayton__loop_brayton__cycle__low_temperature: float = Field(default=308.15, description="Entry point: low_temperature")
    combinations_loop_brayton__loop_brayton__cycle__recuperator_effectiveness: float = Field(default=0.8, description="Entry point: recuperator_effectiveness")
    combinations_loop_brayton__loop_brayton__cycle__return_pressure: float = Field(default=4.285714285714286, description="Entry point: return_pressure")
    combinations_loop_brayton__loop_brayton__cycle__selected_flow: float = Field(default=2500.0, description="Entry point: selected_flow")
    combinations_loop_brayton__loop_brayton__cycle__turbine_efficiency: float = Field(default=0.93, description="Entry point: turbine_efficiency")
    combinations_loop_brayton__loop_brayton__electrical__auxiliary_heat: float = Field(default=20.0, description="Entry point: auxiliary_heat")
    combinations_loop_brayton__loop_brayton__electrical__control: float = Field(default=5.0, description="Entry point: control")
    combinations_loop_brayton__loop_brayton__electrical__cryo: float = Field(default=10.0, description="Entry point: cryo")
    combinations_loop_brayton__loop_brayton__electrical__fuel_base: float = Field(default=5.0, description="Entry point: fuel_base")
    combinations_loop_brayton__loop_brayton__electrical__fuel_coefficient: float = Field(default=1e-22, description="Entry point: fuel_coefficient")
    combinations_loop_brayton__loop_brayton__electrical__fuel_exhaust: float = Field(default=0.0, description="Entry point: fuel_exhaust")
    combinations_loop_brayton__loop_brayton__electrical__generator_efficiency: float = Field(default=0.98, description="Entry point: generator_efficiency")
    combinations_loop_brayton__loop_brayton__electrical__heating_efficiency: float = Field(default=0.5, description="Entry point: heating_efficiency")
    combinations_loop_brayton__loop_brayton__electrical__motor_efficiency: float = Field(default=0.95, description="Entry point: motor_efficiency")
    combinations_loop_brayton__loop_brayton__electrical__other_electric: float = Field(default=5.0, description="Entry point: other_electric")
    combinations_loop_brayton__loop_brayton__generator_capacity__assumed_supported: bool = Field(default=1.0, description="Entry point: assumed_supported")
    combinations_loop_brayton__loop_brayton__generator_capacity__demand_available: bool = Field(default=1.0, description="Entry point: demand_available")
    combinations_loop_brayton__loop_brayton__generator_capacity__scenario_applicable: bool = Field(default=1.0, description="Entry point: scenario_applicable")
    combinations_loop_brayton__loop_brayton__generator_capacity__selected_rating: float = Field(default=1800.0, description="Entry point: selected_rating")
    combinations_loop_brayton__loop_brayton__he_capacity__assumed_supported: bool = Field(default=1.0, description="Entry point: assumed_supported")
    combinations_loop_brayton__loop_brayton__he_capacity__demand_available: bool = Field(default=1.0, description="Entry point: demand_available")
    combinations_loop_brayton__loop_brayton__he_capacity__scenario_applicable: bool = Field(default=1.0, description="Entry point: scenario_applicable")
    combinations_loop_brayton__loop_brayton__he_capacity__selected_rating: float = Field(default=1500.0, description="Entry point: selected_rating")
    combinations_loop_brayton__loop_brayton__he_hx__assumed_u: float = Field(default=1000.0, description="Entry point: assumed_u")
    combinations_loop_brayton__loop_brayton__he_hx__selected_area: float = Field(default=50000.0, description="Entry point: selected_area")
    combinations_loop_brayton__loop_brayton__heat_exchangers__he_cp: float = Field(default=5193.0, description="Entry point: he_cp")
    combinations_loop_brayton__loop_brayton__heat_exchangers__network_mode: float = Field(default=0.0, description="Entry point: network_mode")
    combinations_loop_brayton__loop_brayton__heat_exchangers__pbli_split_fraction: float = Field(default=0.85, description="Entry point: pbli_split_fraction")
    combinations_loop_brayton__loop_brayton__idle_branches__available: float = Field(default=0.0, description="Entry point: available")
    combinations_loop_brayton__loop_brayton__idle_branches__cp: float = Field(default=1.0, description="Entry point: cp")
    combinations_loop_brayton__loop_brayton__idle_branches__dummy_flow: float = Field(default=1.0, description="Entry point: dummy_flow")
    combinations_loop_brayton__loop_brayton__idle_branches__limit: float = Field(default=308.15, description="Entry point: limit")
    combinations_loop_brayton__loop_brayton__idle_branches__ua: float = Field(default=0.0, description="Entry point: ua")
    combinations_loop_brayton__loop_brayton__intercooler_1__heating_role: float = Field(default=0.0, description="Entry point: heating_role")
    combinations_loop_brayton__loop_brayton__intercooler_1__target_temperature: float = Field(default=308.15, description="Entry point: target_temperature")
    combinations_loop_brayton__loop_brayton__intercooler_2__heating_role: float = Field(default=0.0, description="Entry point: heating_role")
    combinations_loop_brayton__loop_brayton__intercooler_2__target_temperature: float = Field(default=308.15, description="Entry point: target_temperature")
    combinations_loop_brayton__loop_brayton__precooler__heating_role: float = Field(default=0.0, description="Entry point: heating_role")
    combinations_loop_brayton__loop_brayton__pressure_loss__loss_fraction: float = Field(default=0.045, description="Entry point: loss_fraction")
    combinations_loop_brayton__loop_brayton__primary_loop__dp_loop_ref: float = Field(default=329187.1856931558, description="Entry point: dp_loop_ref")
    combinations_loop_brayton__loop_brayton__primary_loop__eta_drive: float = Field(default=1.0, description="Entry point: eta_drive")
    combinations_loop_brayton__loop_brayton__primary_loop__eta_is: float = Field(default=0.772796639536644, description="Entry point: eta_is")
    combinations_loop_brayton__loop_brayton__primary_loop__eta_p_direct: float = Field(default=0.0, description="Entry point: eta_p_direct")
    combinations_loop_brayton__loop_brayton__primary_loop__f_loss: float = Field(default=1.0, description="Entry point: f_loss")
    combinations_loop_brayton__loop_brayton__primary_loop__loop_T_in: float = Field(default=573.15, description="Entry point: loop_T_in")
    combinations_loop_brayton__loop_brayton__primary_loop__loop_cp: float = Field(default=5193.0, description="Entry point: loop_cp")
    combinations_loop_brayton__loop_brayton__primary_loop__loop_dT_blanket: float = Field(default=200.0, description="Entry point: loop_dT_blanket")
    combinations_loop_brayton__loop_brayton__primary_loop__loop_gamma: float = Field(default=1.6666666666666667, description="Entry point: loop_gamma")
    combinations_loop_brayton__loop_brayton__primary_loop__loop_live: float = Field(default=1.0, description="Entry point: loop_live")
    combinations_loop_brayton__loop_brayton__primary_loop__loop_p: float = Field(default=8000000.0, description="Entry point: loop_p")
    combinations_loop_brayton__loop_brayton__primary_loop__mdot_loop_rated: float = Field(default=225.07777777777778, description="Entry point: mdot_loop_rated")
    combinations_loop_brayton__loop_brayton__primary_loop__mdot_loop_ref: float = Field(default=225.07777777777778, description="Entry point: mdot_loop_ref")
    combinations_loop_brayton__loop_brayton__primary_loop__n_loops: float = Field(default=14.0, description="Entry point: n_loops")
    combinations_loop_brayton__loop_brayton__primary_loop__p_pump_direct: float = Field(default=0.0, description="Entry point: p_pump_direct")
    combinations_loop_brayton__loop_brayton__rejection_capacity__assumed_supported: bool = Field(default=1.0, description="Entry point: assumed_supported")
    combinations_loop_brayton__loop_brayton__rejection_capacity__demand_available: bool = Field(default=1.0, description="Entry point: demand_available")
    combinations_loop_brayton__loop_brayton__rejection_capacity__scenario_applicable: bool = Field(default=1.0, description="Entry point: scenario_applicable")
    combinations_loop_brayton__loop_brayton__rejection_capacity__selected_rating: float = Field(default=2500.0, description="Entry point: selected_rating")
    combinations_loop_brayton__loop_brayton__turbine_capacity__assumed_supported: bool = Field(default=1.0, description="Entry point: assumed_supported")
    combinations_loop_brayton__loop_brayton__turbine_capacity__demand_available: bool = Field(default=1.0, description="Entry point: demand_available")
    combinations_loop_brayton__loop_brayton__turbine_capacity__scenario_applicable: bool = Field(default=1.0, description="Entry point: scenario_applicable")
    combinations_loop_brayton__loop_brayton__turbine_capacity__selected_rating: float = Field(default=3500.0, description="Entry point: selected_rating")

    model_config = {"frozen": True, "extra": "forbid", "populate_by_name": True}
