from pydantic import BaseModel, Field


class MfeViabilityParams(BaseModel):
    """Parameters from mfe_viability.

    Generated from SysML calculation definitions.
    """
    component_alternatives__plant__gas_loss_water__cooling_approach_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__gas_loss_water__cooling_approach_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__gas_loss_water__cooling_approach_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__gas_loss_water__cooling_approach_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_conditions__supported_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_conditions__supported_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_conditions__supported_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_conditions__supported_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_cycle__main_UA_available_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_cycle__main_UA_available_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_cycle__main_UA_available_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_cycle__main_UA_available_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_cycle__main_admission_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_cycle__main_admission_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_cycle__main_admission_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_cycle__main_admission_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_cycle__reheat_UA_available_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_cycle__reheat_UA_available_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_cycle__reheat_UA_available_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_cycle__reheat_UA_available_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_cycle__reheat_admission_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_cycle__reheat_admission_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_cycle__reheat_admission_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_cycle__reheat_admission_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_transport__design_motor_base_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_transport__design_motor_base_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_transport__design_motor_base_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_transport__design_motor_base_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_transport__design_motor_factor_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_transport__design_motor_factor_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_transport__design_motor_factor_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_transport__design_motor_factor_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_transport__design_pump_size_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_transport__design_pump_size_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_transport__design_pump_size_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_transport__design_pump_size_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_transport__design_pump_type_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_transport__design_pump_type_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_transport__design_pump_type_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_transport__design_pump_type_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_transport__ihx_capacity_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_transport__ihx_capacity_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_transport__ihx_capacity_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_transport__ihx_capacity_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_transport__motor_base_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_transport__motor_base_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_transport__motor_base_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_transport__motor_base_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_transport__motor_factor_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_transport__motor_factor_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_transport__motor_factor_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_transport__motor_factor_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_transport__pump_size_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_transport__pump_size_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_transport__pump_size_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_transport__pump_size_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_transport__pump_type_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_transport__pump_type_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_transport__pump_type_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_transport__pump_type_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_transport__salt_flow_regime_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_transport__salt_flow_regime_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_transport__salt_flow_regime_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_transport__salt_flow_regime_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_transport__salt_head_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_transport__salt_head_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_transport__salt_head_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_transport__salt_head_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")
    component_alternatives__plant__steam_water__cooling_approach_ok_required_screen__applicable_in: bool = Field(default=1.0, description="Entry point: applicable_in")
    component_alternatives__plant__steam_water__cooling_approach_ok_required_screen__demand_available_in: bool = Field(default=1.0, description="Entry point: demand_available_in")
    component_alternatives__plant__steam_water__cooling_approach_ok_required_screen__demand_in: float = Field(default=0.0, description="Entry point: demand_in")
    component_alternatives__plant__steam_water__cooling_approach_ok_required_screen__rating_in: float = Field(default=1.0, description="Entry point: rating_in")

    model_config = {"frozen": True, "extra": "forbid", "populate_by_name": True}
