"""Assemble the executor record and synthesis from retained numerical evidence."""
import hashlib
import json
from pathlib import Path

H = Path(__file__).resolve().parents[1]
R = H / 'results'
read = lambda path: json.loads(path.read_text())
a = read(R / 'analysis.json')
v = read(R / 'oracle-all-points.json')
comparison = read(R / 'comparison-entering.json')
cat = read(R / 'predicate-catalog.json')
axes = read(H / 'axes.json')['groups']
preflight = read(R / 'preflight_results.json')
edges = read(R / 'edge-scan.json')
native = read(R / 'native-cases.json')
proposals = read(H / 'preparation/proposals.json')
responses = read(R / 'axis-responses.json')
base = a['baseline']
out = []


def section(number, title, text):
    out.append(f'## {number}. {title}\n\n{text}\n')


def choice(row):
    return 'none' if row is None else f"{row['proposal_id']}: ${row['lcoe']:.5f}/MWh"


section(1, 'Study header', f'Study id: `{H.name}`. Package: `stellarator_tea`. Executed 2026-09-15. Executor: delegated fit-study session. Mode: execute. One native arm, `arm-native`; {a["unique_cases"]} unique cases and {a["report_rows"]} coordinate-joined reporting rows. The explicit baseline aliases an original nominal point. This is an executor-authored record and synthesis.')
intake = (H / 'preparation/study-brief.md').read_text().split('Owner intake VERBATIM: ')[1].split('\n\n')[0]
section(2, 'Intake', '[OWNER-VERBATIM]\n\n' + intake + '\n\n[AGENT] Preserve sixty original nominal proposals, add twelve existing radial-allocation alternatives and 44 one-at-a-time local-geometry alternatives at 0.50 m allocation, plus an explicit baseline report row. These are engineered sensitivity samples. Owner-delegated routine choices do not turn the dimensions into qualified device measurements.')
overall = a['overall']
family_lines = ['| Family | Unique cases | Old eighteen pass | All nineteen pass | Fit passes | Cheapest without fit | Cheapest with fit |', '|---|---:|---:|---:|---:|---|---|']
for name, data in a['families'].items():
    family_lines.append(f'| {name} | {data["unique_cases"]} | {data["feasible_18"]} | {data["feasible_19"]} | {data["fit_passes"]} | {choice(data["cheapest_without_fit"])} | {choice(data["cheapest_with_fit"])} |')
section(3, 'Objective and result', f'The objective is `stellarator_09__stellaris__lcoe_calc__lcoe`, in dollars/MWh. Baseline LCOE stays ${base["lcoe"]:.8f}/MWh. Baseline margins are {base["fit_dimensions_m"]["margin_x"]:.6f} m radial and {base["fit_dimensions_m"]["margin_y"]:.6f} m transverse; it fails fit and the inherited divertor-heat predicate. At fixed old inputs the screen changes no old scalar or old verdict. [Results](results/analysis.json); [matched entering evidence](results/comparison-entering.json).\n\n' + '\n'.join(family_lines) + f'\n\nAcross the same complete sample, {overall["feasible_18"]} cases pass the old eighteen predicates and {overall["feasible_19"]} also pass fit. Cheapest without fit: {choice(overall["cheapest_without_fit"])}. Cheapest including fit: {choice(overall["cheapest_with_fit"])}. The sampled increment is ${overall["cheapest_lcoe_shift"]:.5f}/MWh. This is a within-sample feasibility restriction under the same held assumptions, not a comparison with an older historical cheapest result or a qualified optimum. The cheapest retained pass uses increased reference current density and an extrapolated 30 T envelope; absolute current margin remains unknown. It also changes radial allocation to 0.50 m, with the existing physical and economic consequences.\n\nAt the original 0.30 m allocation, every fit screen fails and all three old-predicate passes lose feasibility. No nominal fit-feasible replacement exists in this sample. Larger-allocation and local-geometry families are explicitly conditional alternatives, not a repair of the nominal result.')
lines = ['Every executing constraint is retained by qualified identity. All cases completed; statuses are satisfied or violated, never indeterminate. Counts use unique native cases.', '', '| constraint_id | source_local_identity | Satisfied | Violated |', '|---|---|---:|---:|']
for cid, entry in sorted(cat.items()):
    count = a['violation_counts'][cid]
    lines.append(f'| `{cid}` | `{entry["source_local_identity"]}` | {a["unique_cases"] - count} | {count} |')
lines.append('\nAll eighteen old catalog entries, including definition identities and predicate_ir, are exactly unchanged. The new predicate is minimum_margin greater than or equal to zero; minimum_margin is the minimum of the two published finite signed margins. Exact equality passes. [Catalog](results/predicate-catalog.json); [all verdicts](results/native-cases.json).')
section(4, 'Constraint outcomes', '\n'.join(lines))
section(5, 'Framing', '| Axis | Proposed | Judged | Reason |\n|---|---|---|---|\n' + '\n'.join(f'| {group["axis"]} | sensitivity | sensitivity, unchanged | Engineered response sample; no continuous-boundary or global-optimum claim. |' for group in axes) + '\n\nThe search-framed feasible-fraction hypothesis is inapplicable. Geometry controls receive no procurement or wall-cost coupling from this additive screen, so their fit response cannot establish an economic optimum.')
account = []
for group in axes:
    axis = group['axis']
    selected = [edge for edge in edges['edges'] if edge['axis'] == axis]
    description = '; '.join(f'{edge["edge"]} endpoint {edge["value"]}: ' + (', '.join(edge['violated']) if edge['violated'] else 'no violated predicate') for edge in selected)
    account.append(f'#### {axis} — feasible structure (search framing)\n\n**Applies:** not applicable — this axis is sensitivity-framed.\n\n#### {axis} — observed response (sensitivity framing)\n\n**Applies:** yes.\n\nThe native results contain {len(responses[axis])} matched response groups for this axis. Every group includes exact inputs, dimensions, LCOE and old/new verdicts in [axis-responses.json](results/axis-responses.json). From the separately recorded all-predicate feasible anchor, {description}. These edge diagnostics are oracle-only. Native violation locations remain in [analysis.json](results/analysis.json) and [points.csv](results/points.csv). No continuous-boundary claim is made.')
account.append('Lower current density, higher selected envelope or higher coil current enlarge the required pack. Local aspect ratio redistributes extents while preserving nominal area. Wall thickness reduces radial cavity width; transverse interior changes only its own cavity dimension. Internal transverse build, ground insulation and assembly clearance increase required dimensions under distinct inclusion conventions. Radius/allocation changes retain their existing field, circumference, thermal, support and economic effects. New geometry-only perturbations preserve all 195 old native scalars and all eighteen old predicates at their 0.50 m allocation anchor. These are local-screen and numerical-isolation statements, not thermal or structural requalification. [Isolation evidence](results/geometry-isolation.json).')
section(6, 'Per-axis account', '\n\n'.join(account))
section(7, 'Axis groups', '| Axis | Qualified entry key | Provenance |\n|---|---|---|\n' + '\n'.join(f'| {group["axis"]} | `{entry["key"]}` | {entry["provenance"]} |' for group in axes for entry in group['keys']) + '\n\nEach declared attribute has one public entry key; downstream fan-out remains model-owned. In particular coil_t is the existing radial-build allocation key, so its field, radius and inventory effects execute normally. No physical ties or injected physics are declared. Internal radial build stays zero. All other inputs are retained in preparation/resolved-defaults.json.')
section(8, 'Indicators and rulings', '| Axis | Indicator | Ruling |\n|---|---|---|\n' + '\n'.join(f'| {group["axis"]} | constraints_reachable | [AGENT] Proceed as bounded sensitivity under owner delegation. |' for group in axes) + '\n\nEvery proposed group was traced; none was declined and none reports no_constraint_response. Therefore no missing-constraint-response ruling or associated mandatory finding is needed. Indicators cannot establish monotonicity, physical identity across keys or intra-module dependency. constraints_reachable means a possible path, not an observed response. unresisted is an agent judgment, never tool output. [Indicators](indicators.json).')
section(9, 'Preflight results', '| Gate | Outcome | Detail |\n|---|---|---|\n' + '\n'.join(f'| {gate["gate"]} | {gate["status"]} | {gate["detail"]} |' for gate in preflight['gates']) + '\n\nThe route first deposited results/package_identity.json and results/baseline_result.json from the exact manifest baseline. All preflight gates passed before the candidate oracle scan and native sample. Package cleanliness passed before and after execution. [Preflight](results/preflight_results.json); [execution](results/execution-summary.json).')
section(10, 'Execution route and why', 'The study-local direct API uses stock StudyRunner and PreparedListStrategy through study_route.run_points. A prepared list handles coordinated sensitivity blocks and deduplication. All 212 native numeric channels were required before publication; all nineteen predicates retain qualified identities. Every case completed. The explicit baseline was separately executed as the mandatory gate, then its same coordinates appear once in the unique study store.\n\nGlue ledger: none. No adapter or harness-supplied physics exists. The generated fit completion is part of the sealed model package, not study glue. Preparation resolves default values and aliases; report rows join native cases by canonical proposal ID and exact resolved coordinates. [Definition](study.py); [execution script](execution/execute.py).')
section(11, 'Study definition and window provenance', f'The window is engineered. The independently scanned {a["unique_cases"]} proposed cases had {overall["feasible_18"]} old-predicate passes and {overall["feasible_19"]} all-predicate passes; the final list retained them all. The original allocation produced the expected fit failures while the alternatives exercised radial and transverse restrictions, so no expansion was necessary. Exact bounds live in snapshot.json and preparation/proposals.json.\n\nAll-axis endpoint diagnostics use `{edges["anchor_proposal_id"]}`, a candidate-feasible anchor with explicit larger radial allocation and transverse cavity. Each edge is recorded caught or uncaught in results/edge-scan.json. An uncaught endpoint is not a located optimum. The validity mask recomputes the build as 1.95 m held non-coil layers plus each point\'s coil_t; all proposed R exceed a plus that stack, so no point is excluded. Binary-exact contact and invalid-domain tests are reused from the independently reviewed component/native suite, retained in preparation/test_winding_pack_fit.py and reviews/fit-tests-final.log. This native sample does not claim an exact or continuous fit boundary.')
section(12, 'Cross-fingerprint correlation and what it means', f'There is one native candidate fingerprint, so native cross-arm store correlation is not required. The entering captures at {comparison["entering_revision"]} are independent-oracle results, not old-package native execution. The record retains the entering source, mappings, defaults/contracts and identity needed to interpret them.\n\nSixty original nominal and twelve allocation cases join by exact original input coordinates. Every old catalog entry agrees exactly, including definition-qualified names, local identities and predicate_ir; the candidate adds only the fit predicate. All {comparison["unchanged_scalar_comparisons"]:,} mapped entering scalar comparisons and {comparison["old_predicate_comparisons"]:,} old verdict comparisons agree. Allocation-to-allocation changes are legitimate pre-existing geometry effects. Geometry-only candidate alternatives separately preserve old native quantities at the same allocation. These comparisons support additive-screen attribution; they do not claim historical native replay or independent verification of the sixteen unmapped native quantities. [Matched comparison](results/comparison-entering.json).')
section(13, 'Verification', f'All {v["scalar_comparisons"]:,} scalar comparisons across 196 independently mapped outputs per case and all {v["predicate_comparisons"]:,} independently rederived verdict comparisons pass. Maximum relative scalar deviation is {v["max_relative_deviation"]:.4g}. The stock verifier also passes a sample stratified by observed verdict combination; its exact sample, tolerances and operands are retained in results/verification_summary.json. [All-point checks](results/oracle-all-points.json).\n\nSixteen native numeric channels remain outside the oracle map and are explicitly listed in the all-point check. All 212 numeric values remain in each native record. Geometry-isolation comparisons check old outputs against native anchors and are not an independent source validation. Held defaults are equal by construction. Parity does not qualify current margin, the field-envelope extrapolation, a manufactured cavity, insulation procurement, cold deformation or the inherited thermal/stress approximations. Snapshot and native-store evidence closure is checked in reviews/artifact-check.json after the snapshot is written.')
section(14, 'Review outcomes', '| Lens | Verdict | Disposition |\n|---|---|---|\n| Independent source/math/interface | PASS for conditional design | Reused at reviewed source and geometry scope; reviews/design-review.md and preparation/source-evidence. |\n| Independent implementation | PASS for released candidate | Reused reviews/implementation-review.md; ten native integration gates pass in preparation/integration-return.json. |\n| Pre-execution framing and window | Executor check, clear | reviews/preexecution-check.md and reviews/window-selection.md; no independent study verdict claimed. |\n| Native parity, attribution and evidence closure | Executor checks | results verification artifacts and reviews artifact/record checks. Coordinator performs independent final review after freeze. |\n\nNative runs retain the inherited Boolean serialization warning; complete evidence and comparisons pass. Original model validation residue and incomplete broad-suite/all-diagnostic-identity coverage remain disclosed in the reused implementation review. The first static preparation check found an omitted prefix in the expected predicate identity; it was fixed before evaluation, as retained in reviews/static-preparation-check.json.')
findings = [
    ('1', 'The inherited 0.30 m radial allocation rejects every nominal sample, including all three prior old-predicate passes.', 'Answered, no forced nominal repair; retain the explicit allocation conflict.', 'results/analysis.json; preparation/implemented-design.md'),
    ('2', 'Larger allocation and local geometry produce conditional passes; local passage does not establish manufactured or structural feasibility.', 'Declared engineering seam, open; qualify with local dimensions, tolerances and load/temperature state.', 'preparation/geometry-research.md; preparation/implemented-design.md'),
    ('3', 'Screen addition preserves all old mapped quantities and eighteen predicate definitions/verdicts at matched entering inputs.', 'Bounded additive correction verified; no further correction proposed.', 'results/comparison-entering.json; results/geometry-isolation.json'),
    ('4', 'Geometry alternatives change fit without repricing insulation or walls or requalifying thermal/stress proxies; current margin and field extrapolation remain conditional.', 'Declared model seam, open; no economic-optimum or qualification credit.', 'preparation/implemented-design.md; record.md §3 and §6'),
]
section(15, 'Findings', '| Id | Kind | Finding | Disposition | Home |\n|---|---|---|---|---|\n' + '\n'.join(f'| `{H.name}#{number}` | model | {finding} | {disposition} | {home} |' for number, finding, disposition, home in findings))
snapshot = H / 'snapshot.json'
section(16, 'Snapshot', 'File: snapshot.json. Schema version: 1. SHA256: `' + hashlib.sha256(snapshot.read_bytes()).hexdigest() + '`.' if snapshot.exists() else 'Snapshot is being resolved before the immutable commit.')
section(17, 'What this record does not contain', 'No native execution of the entering package, device-qualified dimensions, continuous boundary or global optimum is present. Source originals and inspected images, released contracts/inputs/pipelines, oracle sources, study tools, complete native stores and content-addressed artifacts are retained. The full generated implementation tree and installed runtime wheels are not copied; re-execution needs the sealed candidate and runtime identified in snapshot.json. The coordinator\'s later independent final review is outside this frozen execution evidence.')
(H / 'record.md').write_text('\n'.join(out))
if snapshot.exists():
    synthesis = f'''# Winding-pack/casing fit — executor synthesis

Authorship: the study executor, not an independent administrator. Date: 2026-09-15. Snapshot SHA256: `{hashlib.sha256(snapshot.read_bytes()).hexdigest()}`.

## Question and result

The study tests the new local rectangular fit screen while preserving old feasibility separately. It completed {a['unique_cases']} native cases. All {overall['feasible_18']} old-predicate passes become {overall['feasible_19']} passes when fit is required; {len(overall['lost_feasibility'])} lose feasibility. All three old-predicate passes in the original nominal family lose feasibility and that family has no fit-feasible case. [Numerical record](results/analysis.json).

The nominal reference has radial margin {base['fit_dimensions_m']['margin_x']:.3f} m and transverse margin {base['fit_dimensions_m']['margin_y']:.3f} m. LCOE remains ${base['lcoe']:.5f}/MWh. The existing 0.30 m exterior allocation is smaller than the 0.36 m nominal pack even before the new allowances; the result was not tuned to pass. [Reference dimensions](results/analysis.json); [declared model](preparation/implemented-design.md).

## Same-sample cheapest comparison

Across the identical full sample, the cheapest old-predicate pass is {choice(overall['cheapest_without_fit'])}. Including fit selects {choice(overall['cheapest_with_fit'])}, an increment of ${overall['cheapest_lcoe_shift']:.5f}/MWh. That result requires an explicit larger radial allocation and is conditional on increased reference density, unknown absolute current margin and a 30 T extrapolated envelope. It is not a nominal repair or a global optimum. Geometry-only alternatives have no new wall or insulation cost coupling. [Family comparisons](results/analysis.json).

## Framing and constraint structure

Every axis remains an engineered sensitivity. All twelve indicator groups reach a possible constraint; actual responses and old/new verdicts are recorded per point. Radius and radial allocation retain existing physics/economic effects. Local geometry changes preserve all old quantities at the same allocation. The new minimum-margin inequality rejects either-axis interference and accepts equality. Component tests establish exact-boundary semantics; the native sample does not locate a continuous boundary. [Edges](results/edge-scan.json); [responses](results/axis-responses.json); [independent implementation review](reviews/implementation-review.md).

## Agreement and findings carried forward

All {v['scalar_comparisons']:,} mapped scalar and {v['predicate_comparisons']:,} predicate comparisons pass. Seventy-two matched entering captures preserve {comparison['unchanged_scalar_comparisons']:,} mapped scalars and {comparison['old_predicate_comparisons']:,} old verdicts; the old catalog is identical. Entering evidence is oracle capture, not old-package native execution. [Oracle verification](results/oracle-all-points.json); [entering comparison](results/comparison-entering.json).

Findings #1–#4 preserve the nominal allocation conflict, conditional geometry qualification, successful additive attribution, and uncoupled manufacturing/thermal/structural limits. Qualifying measurements include each coil's limiting local pack and cavity sections, internal-insulation inclusion, alignment/offset/fillets, wrap/tolerance/assembly build and common load/temperature state. [Findings](record.md); [research](preparation/geometry-research.md).

## What the record does not support

No manufactured fit, stress certification, full three-dimensional interference, insertion path, absolute current margin or economic optimum is established. Sixteen native numeric channels lack independent oracle mapping. The record does not contain native old-package execution or the full generated implementation/runtime distribution. These limits are explicit; no missing value is recovered from an external live artifact for this synthesis.
'''
    (H / 'synthesis.md').write_text(synthesis)
