"""Publish author interpretation from retained native evidence; no plant execution."""
from collections import Counter
from pathlib import Path
import hashlib,json,re

H=Path(__file__).resolve().parents[1];R=H/'results';ROOT=H.parents[3]
read=lambda p:json.loads(p.read_text())
assert not (H/'snapshot.json').exists(),'Frozen record is immutable'
ver=read(R/'oracle-all-points.json');checks=read(R/'account-and-dependency-checks.json')
assert ver['outcome']==checks['outcome']=='pass'
rows=read(R/'interpreted-cases.json');by={r['id']:r for r in rows};base=by['reference']
raw=read(R/'native-cases.json');props=read(H/'preparation/proposals.json');summary=read(R/'summary.json')
catalog=read(R/'predicate-catalog.json');ind=read(H/'preparation/indicator-summary.json')
release=read(H/'preparation/integration-return.json')['candidate'];coverage=read(H/'preparation/coverage.json')
fmt=lambda x:f'{x:,.3f}'
source=[r for r in rows if r['family']=='source-envelope'];diag=[r for r in rows if r['family']=='contingency-diagnostic'];stress=[r for r in rows if r['family']=='downtime-stress']
low=min(source,key=lambda r:r['LCOE']);high=max(source,key=lambda r:r['LCOE'])
refzero=by['zero-contingency-reference']
failures=Counter(catalog[cid]['source_local_identity'] for c in raw for cid,v in c['verdicts'].items() if v!='satisfied')
fields=[('Direct before contingency','direct',1e6,'million USD'),('CAS29 contingency','contingency',1e6,'million USD'),('Indirect','indirect',1e6,'million USD'),('Supplementary','supplementary',1e6,'million USD'),('Overnight capital','overnight',1e9,'billion USD'),('Construction interest diagnostic','idc',1e9,'billion USD'),('Comparison financed capital','financed_comparison_capital',1e9,'billion USD'),('Headline annual capital','headline_annual_capital',1e6,'million USD/year'),('Routine O&M levelized','routine_levelized',1e6,'million USD/year'),('Cooling replacement equivalent','cooling_replacement',1e6,'million USD/year'),('All replacement equivalent','replacement_total',1e6,'million USD/year'),('Fuel expense levelized','fuel_levelized',1e6,'million USD/year'),('Total noncapital expense','annual_expense',1e6,'million USD/year'),('Annual electricity','energy_MWh',1,'MWh/year'),('Headline LCOE','LCOE',1,' USD/MWh'),('Comparison LCOE','LCOE_comparison',1,' USD/MWh')]
report=['# Conditional estimate-uncertainty results',f'[AGENT] Executor analysis. The 36 source cases give headline LCOE **{fmt(low["LCOE"])}–{fmt(high["LCOE"])} USD/MWh**, with nominal **{fmt(base["LCOE"])} USD/MWh**. This is a finite conditional source-interpretation/model-analogy envelope at one fixed design. It is not a confidence interval, a complete plant uncertainty range or the price of a feasible plant. The separate 36 contingency diagnostics and 2 downtime stresses are excluded from that headline envelope.','## Estimate and result scope',f'The audited candidate executable is `{release["executable_fingerprint"]}` with semantic fingerprint `{release["semantic_fingerprint"]}` and integration pin `{release["pin"]}`. Complete inputs, source qualifications, account amounts and evidence are retained under preparation/. The retained reference has 14 cooling circuits. All money is mixed-source-year; cooling uses an approximate annual-CPI purchasing-power conversion of January 2017 source prices. The historical r2 archive and other design identities are separate.','## Costs and electricity','| Quantity | Unit | Nominal | Source minimum | Source maximum | Nominal zero-contingency diagnostic |','|---|---|---:|---:|---:|---:|']
for label,k,scale,unit in fields:report.append(f'| {label} | {unit} | {fmt(base[k]/scale)} | {fmt(min(r[k] for r in source)/scale)} | {fmt(max(r[k] for r in source)/scale)} | {fmt(refzero[k]/scale)} |')
report+=['The table gives each output’s own minimum/maximum over the 36 cases. It does not imply all extrema belong to the same scenario. results/points.csv contains the complete input combinations and exact outputs. Overnight capital includes direct contingency and its downstream charges; CAS60 is separately reported and is not added a second time in the headline financing formula.','## What changes the result','The common fabrication rate changes exchanger and both pipe supply bills, dependent installation/delivery exclusions and future bundle replacements together. Civil TN interpretation changes all affected reinforcement rates together; containment date changes both that row’s equipment and installation; sheet inclusion changes only the extra stock charge at fixed physical stock and winding effort. These are finite alternatives with no probability weights.','| Single driver, other source assumptions nominal | LCOE minimum | LCOE maximum | Span USD/MWh |','|---|---:|---:|---:|']
axes={'fabrication':'heat_transport__equipment_stainless_fabrication_usd2017_per_kg','tonne':'buildings__tonne_interpretation_kg','containment':'fuel_cycle__processing_containment_cpi','sheet':'magnet__winding_pack__insulation_sheet_price'}
attribution={}
for name,k in axes.items():
 selected=[r for r in source if all(r[other]==base[other] for other in axes.values() if other!=k)]
 lo=min(r['LCOE'] for r in selected);hi=max(r['LCOE'] for r in selected)
 attribution[name]={'cases':[r['id'] for r in selected],'lcoe_min':lo,'lcoe_max':hi,'span':hi-lo}
 report.append(f'| {name} | {fmt(lo)} | {fmt(hi)} | {fmt(hi-lo)} |')
(R/'attribution.json').write_text(json.dumps(attribution,indent=2)+'\n')
report+=['The source cases use fabrication rates of 240, 310 and 360 USD (2017)/kg; TN conversions of 907.18474 and 1,000 kg; containment CPI values of 65.2, 82.4 and 96.5; and sheet rates of 0 and 61.67720668774671 USD/m². The minimum headline case combines 240, 1,000, 96.5 and 0 respectively; the maximum combines 360, 907.18474, 65.2 and 61.67720668774671. Exact unrounded single-driver spans are retained in results/attribution.json.', 'This attribution describes the selected finite cases only. Exposure to a common source does not measure the fraction of total uncertainty captured. No continuous interval extrema are claimed; replacing discrete source cases with arbitrary intermediate models requires an additional argument.','## Contingency diagnostic',f'At nominal source assumptions, native removal of direct contingency changes overnight capital from {fmt(base["overnight"]/1e9)} to {fmt(refzero["overnight"]/1e9)} billion USD and LCOE from {fmt(base["LCOE"])} to {fmt(refzero["LCOE"])} USD/MWh. All dependent indirect, freight, tax/insurance and finance terms are recomputed. It is not equivalent to subtracting CAS29 from final capital. Supplementary contingency remains 0. This diagnostic does not recommend changing the retained 10% policy or imply that its allowance covers every omitted risk. No further uncertainty uplift is added.','## Separate electricity-denominator stresses','| Unplanned downtime input | Availability | Annual electricity MWh | Annual noncapital expense USD | LCOE USD/MWh |','|---:|---:|---:|---:|---:|']
for r in [base]+stress:report.append(f'| {r["unplanned_fraction"]:g} | {r["availability"]:.9f} | {fmt(r["energy_MWh"])} | {fmt(r["annual_expense"])} | {fmt(r["LCOE"])} |')
report+=['These 0.05/0.10 inputs are engineered downtime stresses, not evidence-supported reliability bounds. The live calendar propagates annual electricity and expense effects; running fuel-processing capacity remains distinct from annual processed mass. None belongs in the source envelope.','## Engineering failures and verification',f'All {len(raw)} proposals are retained. Whole-plant passing count is {sum(all(v=="satisfied" for v in c["verdicts"].values()) for c in raw)}. Predicate failure counts are `{dict(failures)}`. The salt-pump equation-range screen is satisfied in this 14-circuit case, while the salt/conversion temperature-interface screen remains unsatisfied; motor/manufacturing qualification remains unresolved. Both numerical screens are retained in results/summary.json; authored predicates do not cover every qualification gap.',f'Independent-software checks pass {ver["scalar_comparisons"]} mapped scalar comparisons and {ver["predicate_comparisons"]} predicate comparisons. Account/dependency checks pass {len(checks["checks"])} checks; exact shared-output comparison reproduces the retained WI-070 nominal. Generic verification passes. There are {len(coverage["unmapped_numeric"])} native numeric channels outside the oracle map; preparation/coverage.json names them. Shared source assumptions and transport data are not independently validated by numerical agreement. Static-validation and integration read-set limitations remain in the retained audit/integration evidence.','The original failures persist: peak divertor target heat exceeds its limit; the breeding lower-bound estimate falls below required TBR despite its higher mean; reference conductor operating current exceeds the permitted margin; and the required winding pack does not fit the casing cavity. Exact authored operators and source identities are retained in results/predicate-catalog.json, with operand outputs in results/all-native-channels.csv.', '## Maturity and unquantified remainder','The reviewed generic AACE 17R-97 Class 5 judgment is provisional conceptual project maturity, using the historical matrix reproduced by DOE with its edition stated. Account detail varies: cooling/facilities have explicit but unqualified quantities; magnets/fuel have incomplete manufacturing/process coverage; other systems and project services retain factors. Software detail is not an engineering-completion percentage. No class-derived accuracy band is applied.','The source cases leave target fabrication transfer, pressure-qualified geometry, routing, procurement, magnet tape/winding/support uncertainty, civil productivity, conventional equipment, project execution, routine O&M, component reliability and unavailable equipment costs unbounded. Missing equipment is retained as unpriced or coverage unresolved in preparation/references/uncertainty-register.md, with evidence/action and domain roles. It is not modeled as a zero-cost random variable. This study does not independently certify R12.S.']
paired=[(r,by['zero-contingency-'+r['id']]) for r in source]
report.insert(report.index('## Separate electricity-denominator stresses'), f'Across all 36 matched source pairs, removing direct contingency reduces overnight capital by {fmt(min(a["overnight"]-b["overnight"] for a,b in paired)/1e9)}–{fmt(max(a["overnight"]-b["overnight"] for a,b in paired)/1e9)} billion USD and headline LCOE by {fmt(min(a["LCOE"]-b["LCOE"] for a,b in paired))}–{fmt(max(a["LCOE"]-b["LCOE"] for a,b in paired))} USD/MWh. Annual noncapital expense and electricity are unchanged within every matched pair.')
(H/'report.md').write_text(re.sub(r'(?<=\|)\n\n(?=\|)', '\n', '\n\n'.join(report))+'\n')
# Replace the drafted record sections only after execution has supplied their evidence.
text=(H/'record.md').read_text();headers=[f'## {n}.' for n in range(1,18)]
starts=[text.index(h) for h in headers];parts=[text[starts[i]:starts[i+1] if i<16 else len(text)].rstrip() for i in range(17)]
parts[0]=parts[0].replace('Not executed; preparation opened2026-09-19.','2026-09-19.').replace('execute, awaiting audited candidate release.','execute.')
parts[2]=f'## 3. Objective and result\n\nThe source-envelope headline LCOE is {fmt(low["LCOE"])}–{fmt(high["LCOE"])} USD/MWh; nominal {fmt(base["LCOE"])} USD/MWh. Both qualified LCOE channels are retained. [Report](report.md) separates source cases, contingency diagnostics and downtime stresses; [points](results/points.csv) retains all outputs. No probability or feasible-cost claim.'
lines=['## 4. Constraint outcomes','All authored predicates remain qualified and retained at every case.','| constraint_id | source_local_identity | Satisfied | Violated | Other |','|---|---|---:|---:|---:|']
for cid,c in sorted(catalog.items()):
 counts=Counter(case['verdicts'][cid] for case in raw)
 lines.append(f'| `{cid}` | `{c["source_local_identity"]}` | {counts["satisfied"]} | {counts["violated"]} | {sum(v for k,v in counts.items() if k not in ("satisfied","violated"))} |')
parts[3]='\n\n'.join(lines[:2])+'\n\n'+'\n'.join(lines[2:])
parts[4]='## 5. Framing\n\nAs proposed: all axes sensitivity-framed, separated into source alternatives, contingency diagnostic and downtime stress. As judged: unchanged. The finite native results quantify the declared comparisons and preserve failures. No constraint boundary or optimum is inferred.'
from importlib.util import spec_from_file_location,module_from_spec
spec=spec_from_file_location('local_props',H/'execution/proposals.py');pm=module_from_spec(spec);spec.loader.exec_module(pm)
body='## 6. Per-axis account\n'
for name,suffix in pm.AXES.items():
 body+=f'\n#### {suffix} — feasible structure (search framing)\n\n**Applies:** Not applicable; sensitivity-framed.\n\n#### {suffix} — observed response (sensitivity framing)\n\n**Applies:** Yes. '
 if name in attribution:body+=f'Selected single-driver LCOE span {fmt(attribution[name]["span"])} USD/MWh; combined source cases in report.md. '
 elif name=='contingency':body+=f'Matched nominal LCOE delta {fmt(refzero["LCOE"]-base["LCOE"])} USD/MWh; financial diagnostic only. '
 else:body+='The separate downtime stresses change the live electricity denominator and expense response; values in report.md. '
 body+='No boundary claim. Qualified failure identities and case locations remain in results/native-cases.json; all selected cases retain failed plant predicates.\n'
parts[5]=body
parts[6]=parts[6].replace('Proposed public owner keys below must be confirmed from the actual released pipeline before execution. No tie is proposed.','All public owner keys are confirmed against the released pipeline; complete direct fan-out is in preparation/fan-out-evidence.json. No ties.').replace('fan_out, pending released-package confirmation','fan_out')
lines=['## 8. Indicators and rulings','Every proposed axis was traced. Coordinator axis-rulings.json applies the explicit owner study authorization; window-release.json records the post-scan release.','| Axis | Indicator | Framing |','|---|---|---|']
for i in ind:lines.append(f'| {i["axis"]} | {i["indicator"]} | sensitivity |')
parts[7]='\n\n'.join(lines[:2])+'\n\n'+'\n'.join(lines[2:])+'\n\nNot derivable: monotonicity, physical identity across different keys and intra-module operand dependence. constraints_reachable is a possible path, not observed response; unresisted is an executor judgment. No-response findings are retained in section 15.'
pre=read(R/'preflight_results.json');parts[8]='## 9. Preflight results\n\nAll native preflight gates pass; exact gate details are in results/preflight_results.json. They read retained results/package_identity.json and baseline_result.json. Declared keys, sibling scan, identity, manifest currency, pinned baseline and git-clean package were checked. Before/after execution cleanliness receipts pass. No gate was skipped.'
parts[9]='## 10. Execution route and why\n\nStudy-local direct API using stock StudyRunner/PreparedListStrategy through retained study_route.py. The route loaded the sealed package and reproduced its pin before preflight. It executes the coordinated prepared list through the native store and preserves all cases. Glue ledger: none. Scripts supply no plant evaluator.'
parts[10]='## 11. Study definition and window provenance\n\nThe full 74-candidate list was scanned through the independent oracle after baseline/preflight. All were retained and coordinator window release precedes native execution. The finite combination design is engineered from reviewed source-family/interpretation values; the financial diagnostic and downtime stresses remain separately labeled. No feasible anchor or optimization claim. Numeric source-case extrema refer only to evaluated alternatives, not an unproved continuous distribution.'
parts[11]='## 12. Cross-fingerprint correlation and what it means\n\nSingle generated fingerprint; no cross-arm correlation needed. Exact nominal preservation against the retained WI-070 channels is an implementation limiting check, not independent source accuracy evidence.'
parts[12]=f'## 13. Verification\n\nAll {ver["scalar_comparisons"]} mapped scalar and {ver["predicate_comparisons"]} predicate comparisons pass. Generic verification requests all cases. Independent account/dependency checks pass {len(checks["checks"])} checks. There are {len(coverage["unmapped_numeric"])} native numeric channels outside the oracle map, named in preparation/coverage.json. Shared source assumptions are not independent physical validation. Native reproduction is a separate frozen-package check; no full static-validation or read-set pass is inferred.'
parts[13]='## 14. Review outcomes\n\nSource/method/register review: PASS at retained checkpoint. Implementation audit and native integration: candidate release retains evidence. Axis framing and post-scan window: coordinator release under owner authorization. Native numerical/account checks: author verification passes. Freeze release and independent final R12.S grading remain coordinator-owned; the executor does not self-certify.'
# Findings generated here, then the coordinator reviews their exact wording before freeze.
findings=[]
issues={
 pm.AXES['fabrication']:'Fabrication source analogy has no independent target quote, manufacturing qualification or calibrated economic bound.',
 pm.AXES['tonne']:'Original civil TN unit convention is unresolved; no model predicate selects its correct monetary interpretation.',
 pm.AXES['containment']:'Historical containment chronology and equipment escalation remain uncertain; date interpretation is not checked by plant constraints.',
 pm.AXES['sheet']:'Winding/stock scope overlap remains unresolved; no procurement-coverage predicate identifies the correct charge.',
 pm.AXES['contingency']:'Contingency has no calibrated project-risk acceptance rule; retained percentage is an allowance convention.',
 pm.AXES['downtime']:'Unplanned downtime lacks calibrated reliability evidence; no modeled reliability limit establishes these stress values.',
}
for i in ind:
 if i['indicator']=='no_constraint_response':findings.append(('model',issues[i['axis']],'Authorized sensitivity only; retain gap and concrete action in uncertainty register.','work/orchestration/goals/cost-estimate-maturity-and-uncertainty/uncertainty-register.md'))
findings += [('model','All selected cases retain failed plant screens; finite cost envelope excludes major unbounded transfer errors and missing scope.','No feasible-plant cost or plant-wide confidence claim.','work/orchestration/goals/cost-estimate-maturity-and-uncertainty/uncertainty-register.md'),('model','Existing contingency and its indirect/finance effects differ from a statistical uncertainty measure.','Keep convention diagnostic separate from headline source envelope.','work/orchestration/goals/cost-estimate-maturity-and-uncertainty/uncertainty-register.md')]
lines=['## 15. Findings','| Id | Kind | Finding | Disposition | Home |','|---|---|---|---|---|'];logrows=[]
for n,(kind,finding,disposition,home) in enumerate(findings,1):
 fid=f'{H.name}#{n}';lines.append(f'| `{fid}` | {kind} | {finding} | {disposition} | `{home}` |')
 logrows.append(f'| 2026-09-19 | {kind} | `{fid}` | {finding} | {disposition} | `{home}` |')
parts[14]=lines[0]+'\n\n'+'\n'.join(lines[1:])
(H/'preparation/discovery-first-sighting-rows.txt').write_text('\n'.join(logrows)+'\n')
parts[16]='## 17. What this record does not contain\n\nProducer package and required tool/helper sources are copied at freeze. The later scoped commit and final independent grade are outside the frozen snapshot. The record does not contain an installed Python environment, syside credentials, entire external checkouts or every full historical paper. Reproduction needs the recorded compatible runtime. Source/review extracts and original critical page images are retained. No market quotation, measured reliability or complete manufactured/installed plant scope is supplied.'
(H/'record.md').write_text('\n\n'.join(parts)+'\n')
(H/'synthesis.md').write_text('# Executor synthesis\n\n[AGENT] Study-author reading prepared for the immutable record, not independent administration. Source envelope: '+fmt(low['LCOE'])+'–'+fmt(high['LCOE'])+' USD/MWh at fixed design and retained contingency. Nominal: '+fmt(base['LCOE'])+' USD/MWh. See report.md and results/points.csv for exact cases.\n\nAll axes remain sensitivity-framed. Contingency diagnostics and downtime stresses are separate from source uncertainty. All cases preserve failed plant screens. Source transfer, geometry, manufacturing, operating reliability and omitted scope remain outside the finite envelope. The record supplies no probability, feasible optimum or independent R12.S grade.\n')
print('Report,17-section record, author synthesis and proposed discovery rows generated for coordinator review')
