from pathlib import Path
import sys
sys.path.insert(0,str(Path.cwd()))
p=Path('models/library/analyses/mfe_matched_steam_cycle.sysml');s=p.read_text().replace('enabled_in == 0.0 or gap_in > 0.0','enabled_in <= 0.0 or gap_in > 0.0');s=s.replace("    constraint def 'Active Steam Heat Direction' {", "    constraint def 'Active Steam Heat Direction' {\n        // Exact mode domain {0,1} is enforced by the solver; <=0 means disabled only.\n        // Invalid modes refuse before predicate reporting. Physical approach remains strictly positive.");p.write_text(s)
p=Path('models/designs/generic_mfe/mfe_plant.sysml');s=p.read_text().replace('        connect electric_plant.recirculating to turbine.condensate_pump.electric_in;\n','').replace('        connect electric_plant.recirculating to turbine.feedwater_pump.electric_in;\n','').replace('        connect electric_plant.recirculating to heat_rejection.circulating_water_pump.electric_in;\n','');p.write_text(s)
p=Path('models/designs/generic_mfe/mfe_subsystems.sysml');s=p.read_text().replace("        port cycle_rejection : 'Heat Duty Port';", "        port cycle_rejection : 'Heat Duty Port';\n        port conversion_losses : 'Heat Duty Port';\n        // Conversion-loss boundary collects mechanical, generator and pump-motor losses.\n        // Total rejection is q_rejection_before_cooling_MW, not condenser duty alone.");s=s.replace('        connect condenser.rejection to cycle_rejection;', '        connect condenser.rejection to cycle_rejection;\n        connect conversion_losses to cycle_rejection;\n        connect pump_electric_in to condensate_pump.electric_in;\n        connect pump_electric_in to feedwater_pump.electric_in;');s=s.replace("        calc cooling_water : 'Cooling Water Rejection' {", "        connect electric_in to circulating_water_pump.electric_in;\n        calc cooling_water : 'Cooling Water Rejection' {");p.write_text(s)
p=Path('models/designs/stellarator_09/stellarator_plant.sysml');s=p.read_text().replace("preset's; the cycle's efficiency is computed by 'Power Cycle\n            Efficiency' on Kovari 2016's helium-primary Rankine row (WI-045) --", "preset's; selected efficiency now comes from the WI-073 matched extraction/reheat cycle.\n            The Kovari 2016 helium-primary Rankine fit remains a legacy diagnostic (WI-045) --");p.write_text(s)
from tests.model_families import MFE,materialize_canonical_subset
materialize_canonical_subset(MFE,MFE.twin)
from sysml_codegen.cli import GenerationConfig,run_codegen
assert run_codegen(GenerationConfig(models_path=MFE.twin,output_path=Path('/tmp/wi073-stencil-v2'),package_name='stellarator_tea',overwrite=True))
