from pydantic import BaseModel, Field


class IntegratedEquipmentCostsParams(BaseModel):
    """Parameters from integrated_equipment_costs.

    Generated from SysML calculation definitions.
    """
    aries_integrated_plant__contingency_basis__evaluate__amount3_in: float = Field(default=0.0, description="Entry point: amount3_in")
    aries_integrated_plant__contingency_basis__evaluate__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__contingency_basis__evaluate__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__contingency_basis__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__contingency_basis__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__contingency_basis__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__conversion_equipment__evaluate__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__conversion_equipment__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__conversion_equipment__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__conversion_equipment__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__core_cost__evaluate__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__core_cost__evaluate__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__core_cost__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__core_cost__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__core_cost__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__cost_ledger__evaluate__currency_year_in: float = Field(default=2004.0, description="Entry point: currency_year_in")
    aries_integrated_plant__cost_ledger__evaluate__source_coil_excess_in: float = Field(default=5287000.0, description="Entry point: source_coil_excess_in")
    aries_integrated_plant__cost_ledger__evaluate__source_core_excess_in: float = Field(default=31000.0, description="Entry point: source_core_excess_in")
    aries_integrated_plant__cost_ledger__evaluate__source_reactor_gap_in: float = Field(default=28396000.0, description="Entry point: source_reactor_gap_in")
    aries_integrated_plant__direct_cost__evaluate__amount3_in: float = Field(default=0.0, description="Entry point: amount3_in")
    aries_integrated_plant__direct_cost__evaluate__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__direct_cost__evaluate__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__direct_cost__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__direct_cost__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__direct_cost__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__fuel_equipment__evaluate__amount3_in: float = Field(default=0.0, description="Entry point: amount3_in")
    aries_integrated_plant__fuel_equipment__evaluate__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__fuel_equipment__evaluate__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__fuel_equipment__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__fuel_equipment__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__fuel_equipment__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__heat_transport_cost__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__heat_transport_cost__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__heat_transport_cost__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__magnet_inventory__inventory__amount3_in: float = Field(default=0.0, description="Entry point: amount3_in")
    aries_integrated_plant__magnet_inventory__inventory__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__magnet_inventory__inventory__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__magnet_inventory__inventory__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__magnet_inventory__inventory__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__magnet_inventory__inventory__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__primary_heat_cost__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__replacement_scope__evaluate__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__replacement_scope__evaluate__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__replacement_scope__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__replacement_scope__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__replacement_scope__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__shield_inventory__inventory__amount3_in: float = Field(default=0.0, description="Entry point: amount3_in")
    aries_integrated_plant__shield_inventory__inventory__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__shield_inventory__inventory__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__shield_inventory__inventory__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__shield_inventory__inventory__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__shield_inventory__inventory__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__vacuum_equipment__inventory__amount3_in: float = Field(default=0.0, description="Entry point: amount3_in")
    aries_integrated_plant__vacuum_equipment__inventory__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__vacuum_equipment__inventory__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__vacuum_equipment__inventory__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__vacuum_equipment__inventory__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__vacuum_equipment__inventory__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")

    model_config = {"frozen": True, "extra": "forbid", "populate_by_name": True}
