from pydantic import BaseModel, Field


class IntegratedEquipmentCostsParams(BaseModel):
    """Parameters from integrated_equipment_costs.

    Generated from SysML calculation definitions.
    """
    aries_integrated_plant__contingency_basis__evaluate__amount3_in: float = Field(default=0.0, description="Entry point: amount3_in")
    aries_integrated_plant__contingency_basis__evaluate__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__contingency_basis__evaluate__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__contingency_basis__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__contingency_basis__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__contingency_basis__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__conversion_equipment__evaluate__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__conversion_equipment__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__conversion_equipment__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__conversion_equipment__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__core_cost__evaluate__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__core_cost__evaluate__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__core_cost__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__core_cost__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__core_cost__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__cost_ledger__evaluate__currency_year_in: float = Field(default=2004.0, description="Entry point: currency_year_in")
    aries_integrated_plant__direct_cost__evaluate__amount3_in: float = Field(default=0.0, description="Entry point: amount3_in")
    aries_integrated_plant__direct_cost__evaluate__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__direct_cost__evaluate__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__direct_cost__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__direct_cost__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__direct_cost__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__fuel_equipment__evaluate__amount3_in: float = Field(default=0.0, description="Entry point: amount3_in")
    aries_integrated_plant__fuel_equipment__evaluate__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__fuel_equipment__evaluate__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__fuel_equipment__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__fuel_equipment__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__fuel_equipment__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__heat_transport_cost__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__heat_transport_cost__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__heat_transport_cost__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__inventory_comparison__support__factor_in: float = Field(default=1.0, description="Entry point: factor_in")
    aries_integrated_plant__known_dry_inventory__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__known_dry_inventory__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__known_dry_inventory__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__magnet_inventory__inventory__amount3_in: float = Field(default=0.0, description="Entry point: amount3_in")
    aries_integrated_plant__magnet_inventory__inventory__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__magnet_inventory__inventory__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__magnet_inventory__inventory__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__magnet_inventory__inventory__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__magnet_inventory__inventory__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__primary_heat_cost__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__replacement_scope__evaluate__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__replacement_scope__evaluate__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__replacement_scope__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__replacement_scope__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__replacement_scope__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__shield_inventory__inventory__amount3_in: float = Field(default=0.0, description="Entry point: amount3_in")
    aries_integrated_plant__shield_inventory__inventory__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__shield_inventory__inventory__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__shield_inventory__inventory__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__shield_inventory__inventory__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__shield_inventory__inventory__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__source_coil_children__evaluate__amount1_in: float = Field(default=115960000.0, description="Entry point: amount1_in")
    aries_integrated_plant__source_coil_children__evaluate__amount2_in: float = Field(default=13358000.0, description="Entry point: amount2_in")
    aries_integrated_plant__source_coil_children__evaluate__amount3_in: float = Field(default=5318000.0, description="Entry point: amount3_in")
    aries_integrated_plant__source_coil_children__evaluate__amount4_in: float = Field(default=93535000.0, description="Entry point: amount4_in")
    aries_integrated_plant__source_coil_children__evaluate__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__source_coil_children__evaluate__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__source_coil_children__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__source_coil_children__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__source_core_children_first__evaluate__amount1_in: float = Field(default=59347000.0, description="Entry point: amount1_in")
    aries_integrated_plant__source_core_children_first__evaluate__amount2_in: float = Field(default=228627000.0, description="Entry point: amount2_in")
    aries_integrated_plant__source_core_children_first__evaluate__amount4_in: float = Field(default=66427000.0, description="Entry point: amount4_in")
    aries_integrated_plant__source_core_children_first__evaluate__amount5_in: float = Field(default=73126000.0, description="Entry point: amount5_in")
    aries_integrated_plant__source_core_children_first__evaluate__amount6_in: float = Field(default=137135000.0, description="Entry point: amount6_in")
    aries_integrated_plant__source_core_children_first__evaluate__amount7_in: float = Field(default=70624000.0, description="Entry point: amount7_in")
    aries_integrated_plant__source_core_children_first__evaluate__amount8_in: float = Field(default=6561000.0, description="Entry point: amount8_in")
    aries_integrated_plant__source_fuel_children__evaluate__amount1_in: float = Field(default=14134000.0, description="Entry point: amount1_in")
    aries_integrated_plant__source_fuel_children__evaluate__amount2_in: float = Field(default=16590000.0, description="Entry point: amount2_in")
    aries_integrated_plant__source_fuel_children__evaluate__amount3_in: float = Field(default=7067000.0, description="Entry point: amount3_in")
    aries_integrated_plant__source_fuel_children__evaluate__amount4_in: float = Field(default=3353000.0, description="Entry point: amount4_in")
    aries_integrated_plant__source_fuel_children__evaluate__amount5_in: float = Field(default=7067000.0, description="Entry point: amount5_in")
    aries_integrated_plant__source_fuel_children__evaluate__amount6_in: float = Field(default=7067000.0, description="Entry point: amount6_in")
    aries_integrated_plant__source_fuel_children__evaluate__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__source_fuel_children__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__source_reactor_children__evaluate__amount2_in: float = Field(default=474771000.0, description="Entry point: amount2_in")
    aries_integrated_plant__source_reactor_children__evaluate__amount3_in: float = Field(default=3735000.0, description="Entry point: amount3_in")
    aries_integrated_plant__source_reactor_children__evaluate__amount4_in: float = Field(default=6655000.0, description="Entry point: amount4_in")
    aries_integrated_plant__source_reactor_children__evaluate__amount6_in: float = Field(default=60723000.0, description="Entry point: amount6_in")
    aries_integrated_plant__source_reactor_children__evaluate__amount7_in: float = Field(default=44558000.0, description="Entry point: amount7_in")
    aries_integrated_plant__source_reactor_children__evaluate__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")
    aries_integrated_plant__vacuum_equipment__inventory__amount3_in: float = Field(default=0.0, description="Entry point: amount3_in")
    aries_integrated_plant__vacuum_equipment__inventory__amount4_in: float = Field(default=0.0, description="Entry point: amount4_in")
    aries_integrated_plant__vacuum_equipment__inventory__amount5_in: float = Field(default=0.0, description="Entry point: amount5_in")
    aries_integrated_plant__vacuum_equipment__inventory__amount6_in: float = Field(default=0.0, description="Entry point: amount6_in")
    aries_integrated_plant__vacuum_equipment__inventory__amount7_in: float = Field(default=0.0, description="Entry point: amount7_in")
    aries_integrated_plant__vacuum_equipment__inventory__amount8_in: float = Field(default=0.0, description="Entry point: amount8_in")

    model_config = {"frozen": True, "extra": "forbid", "populate_by_name": True}
