"""Generate and seal the combinations package from existing definitions (WI-093, goal design-space-combinations).

Stage the library sources and the four combination design files, run the stock generator, copy the reviewed
completion bodies from the generated Stellaris and ARIES packages with only the import prefix rewritten (a typed
public adapter is added only where the stock smart-regeneration signature reader needs one, the ARIES rule),
regenerate with the handwritten bodies preserved, prove the fixed point, capture the snapshot and hash everything.
No library file, completion body or live assembly is changed.

Build: .codex-test/run python exploration/combinations/build.py
"""
import ast
import hashlib
import json
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
PACKAGE = HERE / 'combinations_tea'
EVIDENCE = ROOT / 'work/active/WI-093_combination-assemblies/evidence'
LIBRARY = [
    'models/library/structure/mfe_interfaces.sysml', 'models/library/structure/mfe_plasma.sysml',
    'models/library/analyses/mfe_plasma_sustainment.sysml', 'models/library/analyses/mfe_plasma_scaling.sysml',
    'models/library/analyses/mfe_primary_loop.sysml', 'models/library/analyses/mfe_power_cycle.sysml',
    'models/library/analyses/mfe_viability.sysml', 'models/library/analyses/integrated_heat_electricity.sysml',
    'models/library/analyses/dual_circuit_heat_accounting.sysml', 'models/library/analyses/ideal_gas_brayton_components.sysml',
    'models/library/analyses/integrated_equipment_costs.sysml', 'models/library/structure/integrated_equipment_parts.sysml',
    'models/library/foundation/costed_component.sysml', 'models/library/analyses/mfe_fuel_cycle.sysml',
]
DESIGNS = sorted(p.relative_to(ROOT).as_posix() for p in (ROOT / 'models/designs/combinations').glob('*.sysml'))
SOURCES = [ROOT / p for p in LIBRARY + DESIGNS]
STELLARIS = ROOT / 'exploration/stellarator_e2e/generated/handwritten'
ARIES = ROOT / 'exploration/aries_integrated/aries_integrated/handwritten'
# Reviewed handwritten bodies to reuse (AUTO_IMPLEMENTED = False in their source packages): (root, relative path, import prefix).
# Auto-implemented definitions ('Plasma Geometry', 'Volume-Averaged Beta', 'Fuel Cycle Flows', the constraints) are regenerated by the stock generator.
BODIES = [
    (STELLARIS, 'mfe_plasma_sustainment/plasma_sustainment_impl.py', 'stellarator_tea'),
    (STELLARIS, 'mfe_plasma_scaling/dt_fusion_power_impl.py', 'stellarator_tea'),
    (STELLARIS, 'mfe_primary_loop/primary_coolant_loop_impl.py', 'stellarator_tea'),
    (STELLARIS, 'mfe_power_cycle/power_cycle_efficiency_impl.py', 'stellarator_tea'),
    (STELLARIS, 'mfe_viability/offered_capacity_screen_impl.py', 'stellarator_tea'),
    (ARIES, 'integrated_heat_electricity/common.py', 'aries_integrated'),
    (ARIES, 'integrated_heat_electricity/network_heat_driven_closure_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_heat_electricity/integrated_heat_source_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_heat_electricity/fusion_source_selector_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_heat_electricity/passive_recuperator_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_heat_electricity/plant_electrical_balance_impl.py', 'aries_integrated'),
    (ARIES, 'dual_circuit_heat_accounting/coolant_branch_heat_impl.py', 'aries_integrated'),
    (ARIES, 'ideal_gas_brayton_components/ideal_gas_compressor_impl.py', 'aries_integrated'),
    (ARIES, 'ideal_gas_brayton_components/ideal_gas_expander_impl.py', 'aries_integrated'),
    (ARIES, 'ideal_gas_brayton_components/fixed_outlet_conditioning_impl.py', 'aries_integrated'),
    (ARIES, 'ideal_gas_brayton_components/fractional_pressure_loss_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_equipment_costs/common.py', 'aries_integrated'),
    (ARIES, 'integrated_equipment_costs/exchanger_area_conductance_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_equipment_costs/selected_flow_pump_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_equipment_costs/selected_inventory_purchase_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_equipment_costs/selected_stock_atoms_impl.py', 'aries_integrated'),
]
NAME = 'combinations_tea'
sha = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()


def run(command, name):
    with (EVIDENCE / name).open('w') as log:
        subprocess.run([str(ROOT / '.codex-test/run')] + command, check=True, cwd=ROOT, stdout=log, stderr=subprocess.STDOUT)


def first_run(tree):
    return next((n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name.startswith('run_')), None)


def copy(source, relative, old_prefix, receipts):
    """The ARIES reuse rule: prefix rewrite; a typed adapter only where the stock signature reader needs one."""
    target = PACKAGE / 'handwritten' / relative
    # Two import-prefix forms occur in the reviewed bodies: the import statement and, in the two shared helpers,
    # the schema module path built as a string literal for importlib. Both are rewritten; nothing else.
    forms = [('from ' + old_prefix + '.', 'from ' + NAME + '.'), ("'" + old_prefix + '.', "'" + NAME + '.')]
    content = source.read_text()
    for before, after in forms:
        content = content.replace(before, after)
    reverse = content
    for before, after in forms:
        reverse = reverse.replace(after, before)
    assert reverse == source.read_text(), relative
    original = first_run(ast.parse(content))
    expected = first_run(ast.parse(target.read_text())) if target.exists() else None
    adapted = False
    if original is not None and expected is not None:
        same_types = (ast.dump(original.args) == ast.dump(expected.args) and original.returns is not None
                      and expected.returns is not None and ast.dump(original.returns) == ast.dump(expected.returns))
        method_ref = any(isinstance(n, ast.Attribute) and isinstance(n.value, ast.Name) and n.value.id == 'inputs'
                         and n.attr == 'model_dump' for n in ast.walk(original))
        if not same_types or method_ref:
            reviewed_name = '_reviewed_' + original.name
            content = content.replace('def ' + original.name + '(', 'def ' + reviewed_name + '(', 1)
            module_path = relative.removesuffix('_impl.py').replace('/', '.')
            input_type = ast.unparse(expected.args.args[0].annotation)
            return_type = ast.unparse(expected.returns)
            content += ('\n\nfrom ' + NAME + '.modules.' + module_path + ' import ' + input_type + '\n\n\n'
                        + 'def ' + original.name + '(inputs: ' + input_type + ') -> ' + return_type + ':\n'
                        + '    """Typed native adapter; delegates unchanged reviewed calculation."""\n'
                        + '    return ' + reviewed_name + '(inputs)\n')
            adapted = True
            reviewed = next(n for n in ast.parse(content).body if isinstance(n, ast.FunctionDef) and n.name == reviewed_name)
            assert [ast.dump(n) for n in original.body] == [ast.dump(n) for n in reviewed.body]
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    receipts.append(dict(source=str(source.relative_to(ROOT)), target=str(target.relative_to(ROOT)), source_sha256=sha(source),
                         target_sha256=sha(target), prefix_only=not adapted, typed_adapter=adapted, reviewed_body_ast_unchanged=True))


def tree_hashes():
    return {str(p.relative_to(PACKAGE)): sha(p) for p in PACKAGE.rglob('*') if p.is_file() and '__pycache__' not in p.parts}


def build():
    EVIDENCE.mkdir(parents=True, exist_ok=True)
    staging = HERE / 'input_models'
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir()
    for source in SOURCES:
        shutil.copy2(source, staging / source.name)
    command = ['sysml-codegen', 'generate', '--models', str(staging), '--output', str(PACKAGE), '--package-name', NAME, '--overwrite']
    run(command, 'generation.log')
    receipts = []
    for root, relative, prefix in BODIES:
        copy(root / relative, relative, prefix, receipts)
    command += ['--smart-regen', '--preserve-handwritten']
    run(command, 'completion-generation.log')
    before = tree_hashes()
    run(command, 'fixed-point-generation.log')
    after = tree_hashes()
    assert before == after, sorted(k for k in set(before) | set(after) if before.get(k) != after.get(k))
    for receipt in receipts:
        assert sha(ROOT / receipt['target']) == receipt['target_sha256'], receipt['target']
    run(['sysml-codegen', 'snapshot', '--models', str(staging), '--output', str(HERE / 'combinations.snapshot.json')], 'snapshot.log')
    receipt = {'package': str(PACKAGE.relative_to(ROOT)), 'package_name': NAME,
               'sources': {str(p.relative_to(ROOT)): sha(p) for p in SOURCES},
               'staged': {str(p.relative_to(ROOT)): sha(staging / p.name) for p in SOURCES},
               'completions': receipts, 'fixed_point': True, 'package_tree': after,
               'snapshot_sha256': sha(HERE / 'combinations.snapshot.json')}
    assert receipt['sources'] == receipt['staged']
    (EVIDENCE / 'build-hashes.json').write_text(json.dumps(receipt, indent=2) + '\n')
    print(json.dumps({'package': receipt['package'], 'sources': len(SOURCES), 'bodies': len(receipts),
                      'adapted': sum(r['typed_adapter'] for r in receipts), 'fixed_point': True, 'snapshot_sha256': receipt['snapshot_sha256']}))


if __name__ == '__main__':
    build()
