"""Generate and seal the costed loop-Brayton package (goal design-study-parameters): the WI-093 C-1 assembly with the
ARIES purchase, fuel, ledger and lifecycle definitions instantiated on it, from existing definitions only.

Stage the library sources and the one design file, run the stock generator, copy the reviewed completion bodies from
the generated Stellaris and ARIES packages with only the import prefix rewritten (the WI-093 reuse rule, both forms),
regenerate with the handwritten bodies preserved, prove the fixed point, capture the snapshot, derive the entry-point
census and hash everything. No library file, completion body, live package or live assembly is changed.

Build: .codex-test/run python exploration/costed_loop_brayton/build.py
"""
import ast
import hashlib
import json
import shutil
import subprocess
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
PACKAGE = HERE / 'costed_loop_brayton_tea'
EVIDENCE = ROOT / 'work/active/WI-094_costed-loop-brayton/evidence'
LIBRARY = [
    'models/library/analyses/mfe_primary_loop.sysml', 'models/library/analyses/mfe_viability.sysml',
    'models/library/analyses/integrated_heat_electricity.sysml', 'models/library/analyses/ideal_gas_brayton_components.sysml',
    'models/library/analyses/integrated_equipment_costs.sysml', 'models/library/structure/integrated_equipment_parts.sysml',
    'models/library/foundation/costed_component.sysml', 'models/library/analyses/mfe_fuel_cycle.sysml',
    'models/library/analyses/mfe_account_costs.sysml', 'models/library/analyses/mfe_lcoe_dcf.sysml',
    'models/library/analyses/integrated_lifecycle_costs.sysml',
]
DESIGNS = ['models/designs/costed_loop_brayton/costed_loop_brayton.sysml']
SOURCES = [ROOT / p for p in LIBRARY + DESIGNS]
STELLARIS = ROOT / 'exploration/stellarator_e2e/generated/handwritten'
ARIES = ROOT / 'exploration/aries_integrated/aries_integrated/handwritten'
# Reviewed handwritten bodies to reuse (AUTO_IMPLEMENTED = False in their source packages): (root, relative path, import prefix).
# Auto-implemented definitions ('Fuel Cycle Flows', 'Indirect Cost', 'Contingency Cost', 'Annual OM Cost', 'DT Fuel Cost',
# 'Supplied Annual Energy', the constraints) are regenerated by the stock generator.
BODIES = [
    (STELLARIS, 'mfe_primary_loop/primary_coolant_loop_impl.py', 'stellarator_tea'),
    (STELLARIS, 'mfe_viability/offered_capacity_screen_impl.py', 'stellarator_tea'),
    (STELLARIS, 'mfe_account_costs/levelized_annual_cost_impl.py', 'stellarator_tea'),
    (STELLARIS, 'mfe_account_costs/supplied_purchase_cost_impl.py', 'stellarator_tea'),
    (STELLARIS, 'mfe_lcoe_dcf/lcoe_dcf_impl.py', 'stellarator_tea'),
    (ARIES, 'integrated_heat_electricity/common.py', 'aries_integrated'),
    (ARIES, 'integrated_heat_electricity/network_heat_driven_closure_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_heat_electricity/passive_recuperator_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_heat_electricity/plant_electrical_balance_impl.py', 'aries_integrated'),
    (ARIES, 'ideal_gas_brayton_components/ideal_gas_compressor_impl.py', 'aries_integrated'),
    (ARIES, 'ideal_gas_brayton_components/ideal_gas_expander_impl.py', 'aries_integrated'),
    (ARIES, 'ideal_gas_brayton_components/fixed_outlet_conditioning_impl.py', 'aries_integrated'),
    (ARIES, 'ideal_gas_brayton_components/fractional_pressure_loss_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_equipment_costs/common.py', 'aries_integrated'),
    (ARIES, 'integrated_equipment_costs/exchanger_area_conductance_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_equipment_costs/selected_inventory_purchase_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_equipment_costs/selected_stock_atoms_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_equipment_costs/annual_selected_fuel_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_equipment_costs/eight_amount_sum_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_equipment_costs/equipment_cost_ledger_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_equipment_costs/replacement_events_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_equipment_costs/scaled_amount_impl.py', 'aries_integrated'),
    (ARIES, 'integrated_lifecycle_costs/lifecycle_cashflow_accounts_impl.py', 'aries_integrated'),
]
NAME = 'costed_loop_brayton_tea'
sha = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()


def run(command, name):
    with (EVIDENCE / name).open('w') as log:
        subprocess.run([str(ROOT / '.codex-test/run')] + command, check=True, cwd=ROOT, stdout=log, stderr=subprocess.STDOUT)


def first_run(tree):
    return next((n for n in tree.body if isinstance(n, ast.FunctionDef) and n.name.startswith('run_')), None)


def copy(source, relative, old_prefix, receipts):
    """The WI-093 reuse rule: prefix rewrite in both forms (import statement and the string-literal module path the shared
    helpers build for importlib), asserted reversible; a typed adapter only where the stock signature reader needs one."""
    target = PACKAGE / 'handwritten' / relative
    forms = [('from ' + old_prefix + '.', 'from ' + NAME + '.'), ("'" + old_prefix + '.', "'" + NAME + '.')]
    content = source.read_text()
    for before, after in forms:
        content = content.replace(before, after)
    reverse = content
    for before, after in forms:
        reverse = reverse.replace(after, before)
    assert reverse == source.read_text(), relative
    original = first_run(ast.parse(content))
    expected = first_run(ast.parse(target.read_text())) if target.exists() else None
    adapted = False
    if original is not None and expected is not None:
        same_types = (ast.dump(original.args) == ast.dump(expected.args) and original.returns is not None
                      and expected.returns is not None and ast.dump(original.returns) == ast.dump(expected.returns))
        method_ref = any(isinstance(n, ast.Attribute) and isinstance(n.value, ast.Name) and n.value.id == 'inputs'
                         and n.attr == 'model_dump' for n in ast.walk(original))
        if not same_types or method_ref:
            reviewed_name = '_reviewed_' + original.name
            content = content.replace('def ' + original.name + '(', 'def ' + reviewed_name + '(', 1)
            module_path = relative.removesuffix('_impl.py').replace('/', '.')
            input_type = ast.unparse(expected.args.args[0].annotation)
            return_type = ast.unparse(expected.returns)
            content += ('\n\nfrom ' + NAME + '.modules.' + module_path + ' import ' + input_type + '\n\n\n'
                        + 'def ' + original.name + '(inputs: ' + input_type + ') -> ' + return_type + ':\n'
                        + '    """Typed native adapter; delegates unchanged reviewed calculation."""\n'
                        + '    return ' + reviewed_name + '(inputs)\n')
            adapted = True
            reviewed = next(n for n in ast.parse(content).body if isinstance(n, ast.FunctionDef) and n.name == reviewed_name)
            assert [ast.dump(n) for n in original.body] == [ast.dump(n) for n in reviewed.body]
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    receipts.append(dict(source=str(source.relative_to(ROOT)), target=str(target.relative_to(ROOT)), source_sha256=sha(source),
                         target_sha256=sha(target), prefix_only=not adapted, typed_adapter=adapted, reviewed_body_ast_unchanged=True))


def tree_hashes():
    return {str(p.relative_to(PACKAGE)): sha(p) for p in PACKAGE.rglob('*') if p.is_file() and '__pycache__' not in p.parts}


def write_census():
    """The entry-point census through the integration producer's own classification (the ARIES build's pattern)."""
    code = """
import json
import sys
from pathlib import Path
from scripts.integrate import rederived_census
from scripts.study.manifest import read_semantic_fingerprint
package, target = map(Path, sys.argv[1:])
census = rederived_census(package)
census['derived_against_semantic_fingerprint'] = read_semantic_fingerprint(package)
target.write_text(json.dumps(census, indent=2) + '\\n')
print(json.dumps({'entry_points': census['entry_points'], 'semantic_fingerprint': census['derived_against_semantic_fingerprint']}))
"""
    run(['python', '-c', code, str(PACKAGE), str(HERE / 'census.json')], 'census-generation.log')


def build():
    EVIDENCE.mkdir(parents=True, exist_ok=True)
    staging = HERE / 'input_models'
    if staging.exists():
        shutil.rmtree(staging)
    staging.mkdir()
    for source in SOURCES:
        shutil.copy2(source, staging / source.name)
    command = ['sysml-codegen', 'generate', '--models', str(staging), '--output', str(PACKAGE), '--package-name', NAME, '--overwrite']
    run(command, 'generation.log')
    receipts = []
    for root, relative, prefix in BODIES:
        copy(root / relative, relative, prefix, receipts)
    command += ['--smart-regen', '--preserve-handwritten']
    run(command, 'completion-generation.log')
    before = tree_hashes()
    run(command, 'fixed-point-generation.log')
    after = tree_hashes()
    assert before == after, sorted(k for k in set(before) | set(after) if before.get(k) != after.get(k))
    for receipt in receipts:
        assert sha(ROOT / receipt['target']) == receipt['target_sha256'], receipt['target']
    run(['sysml-codegen', 'snapshot', '--models', str(staging), '--output', str(HERE / 'costed_loop_brayton.snapshot.json')], 'snapshot.log')
    write_census()
    receipt = {'package': str(PACKAGE.relative_to(ROOT)), 'package_name': NAME,
               'sources': {str(p.relative_to(ROOT)): sha(p) for p in SOURCES},
               'staged': {str(p.relative_to(ROOT)): sha(staging / p.name) for p in SOURCES},
               'completions': receipts, 'fixed_point': True, 'package_tree': after,
               'snapshot_sha256': sha(HERE / 'costed_loop_brayton.snapshot.json'), 'census_sha256': sha(HERE / 'census.json')}
    assert receipt['sources'] == receipt['staged']
    (EVIDENCE / 'build-hashes.json').write_text(json.dumps(receipt, indent=2) + '\n')
    print(json.dumps({'package': receipt['package'], 'sources': len(SOURCES), 'bodies': len(receipts),
                      'adapted': sum(r['typed_adapter'] for r in receipts), 'fixed_point': True, 'snapshot_sha256': receipt['snapshot_sha256']}))


if __name__ == '__main__':
    build()
