"""Concise outcome report from retained source/case accounts only."""
import json
from pathlib import Path
H=Path(__file__).resolve().parents[1];read=lambda p:json.loads(p.read_text());a=read(H/'results/analysis.json');v=read(H/'results/oracle-all-points.json');con=read(H/'results/contrasts.json');source=read(H/'results/source-conditioned-divertor.json')
lines=['# Stellaris reference reconciliation study','',f"Eight native cases completed; {a['overall']['all20_passes']} pass all twenty raw predicates. These are conditional reconstructions and local sensitivity checks. Published-reference qualification remains unresolved.",'','| Case | LCOE $/MWh | Total capital $ | Raw failures |','|---|---|---|---|']
for r in a['cases']:
 q=r['quantities'];lines.append(f"| {r['proposal_id']} | {q['lcoe_calc__lcoe']:.6f} | {q['total_capital__total_capital']:.2f} | {', '.join(r['violated']) or 'none'} |")
lines+=['', '| Case | Fusion MW | Required auxiliary MW | On-axis T | Minimum fit margin m | Pump MW |','|---|---|---|---|---|---|']
for r in a['cases']:
 q=r['quantities'];lines.append('| '+r['proposal_id']+' | '+' | '.join(f'{q[k]:.6f}' for k in ['plasma__fusion__p_fus','plasma__sustain__p_aux_required','magnet__field_calc__B_axis','magnet__wp_fit__minimum_margin','heat_transport__primary_loop__p_elec'])+' |')
lines+=['','All costs use the retained model basis. Water cooling hardware and local cavity/conductor qualification remain unpriced; tape procurement price is assumed and account price years differ. `results/case-summary.csv` retains magnet procurement, heating, pumping/cycle and capital responses alongside every scalar.','', '| Contrast | LCOE change $/MWh | Raw predicate changes |','|---|---|---|']
for c in con:
 lines.append(f"| {c['from']} → {c['to']} | {c['delta_outputs']['stellarator_09__stellaris__lcoe_calc__lcoe']:.6f} | {'; '.join(x['source_local_identity']+': '+x['from']+' → '+x['to'] for x in c['predicate_changes']) or 'none'} |")
lines+=['','`results/contrasts.json` defines the allowable attribution for each contrast. The selected cases enable current-driven inventory sizing plus 1% inventory reserve. The legacy-to-selected cost change belongs to that joint intervention, not to the reserve alone. Reference-effective tapes rise from 112.708720 to 239.983701 and tape procurement cost rises from $731,571,428.57 to $1,557,689,763.85 at the control. These are not the exact historical selected-mode control at multiplier 1. Source radius, volume shape and current conditioning change together and cannot identify a radius-only effect. The two off-reference checks change one geometric attribute each.','',f"All {v['scalar_comparisons']} mapped scalar comparisons and {v['predicate_comparisons']} exact predicate comparisons pass. Sixteen native scalars remain outside the oracle map. Results verify implementation, not engineering qualification. Complete source applicability is in `results/case-predicate-applicability.json`; no filtered feasibility pass is calculated.",'','| Supplied source case | Deposited MW | Uncaptured MW | Peak-equivalent area m² |','|---|---|---|---|']
for r in source['cases']:
 d=r['derived'];lines.append(f"| {r['case']} | {d['deposited_power_MW']:.6f} | {d['uncaptured_power_MW']:.6f} | {d['peak_equivalent_area_m2']:.6f} |")
lines+=['','Both paired source cases supply 500 MW input and 90% radiation. Their capture/peak pairs are 0.99/9.5 MW/m² and 0.97/5 MW/m². Supplied peaks earn accounting consistency only; the derived area is not measured wetted geometry. `results/source-conditioned-divertor.json` preserves temperature and diffusion pairings.','', 'The exact historical selected-entry diagnostic is retained separately in preparation. Its current-boundary sign discrepancy is not corrected by tolerance or relabeled a pass. It is reused history, not a ninth native study case.']
(H/'report.md').write_text('\n'.join(lines)+'\n')
