"""Constraint report aggregator (Item 7 / D5/D11) — exact schema, one required field per
eligible assertion.

Exists even for zero eligible assertions (D11): a missing result is a schema failure, never a
silent gap.
"""

from pydantic import BaseModel
from simkit.config.schema import MultiOutput
from simkit.core.base import ModuleBase, ModuleResult

from whole_plant_conversion_tea.schemas.constraint_types import (
    ConstraintEvaluation,
    ConstraintReport,
    CoverageAccount,
)

EXPECTED_IDS = ('whole_plant_conversion_plant_steam_lp_flow_capacity_capacity_requirement_a3fe0741c9ecff1c', 'whole_plant_conversion_plant_salt_shaft_capacity_capacity_requirement_b2367d578fc2f1ec', 'whole_plant_conversion_plant_steam_condenser_capacity_capacity_requirement_21565c442e22d191', 'whole_plant_conversion_plant_turbine_capacity_capacity_ok_ee860596098e7f44', 'whole_plant_conversion_plant_steam_water_electric_capacity_capacity_requirement_e3f37a33f8f86544', 'whole_plant_conversion_plant_steam_conditions_supported_required_f55a3b19d079007e', 'whole_plant_conversion_plant_gas_boundary_exchanger_flow_margin_ok_396e8f7ff4b4cd78', 'whole_plant_conversion_plant_gas_boundary_pressure_margin_ok_57cdec1e34d967ce', 'whole_plant_conversion_plant_gas_boundary_controller_capacity_ok_ok_b340a8d5e92452b2', 'whole_plant_conversion_plant_gas_boundary_total_flow_margin_ok_b1cac73884dab807', 'whole_plant_conversion_plant_gas_boundary_bypass_fraction_margin_ok_c17576ed428ad624', 'whole_plant_conversion_plant_gas_boundary_bypass_flow_margin_ok_44eb1a31c631c4dc', 'whole_plant_conversion_plant_gas_boundary_temperature_margin_ok_c3287e1bc91fd77f', 'whole_plant_conversion_plant_gas_boundary_source_adequate_ok_665dcdd55c247bde', 'whole_plant_conversion_plant_gas_boundary_added_dp_margin_ok_cb2dbaa41d101ab2', 'whole_plant_conversion_plant_gas_overheads_domain_supported_ok_37ebb2bb65f0bc13', 'whole_plant_conversion_plant_water_pre_power_margin_ok_88cf3aa259145f02', 'whole_plant_conversion_plant_water_pre_duty_margin_ok_43a051525223b723', 'whole_plant_conversion_plant_water_pre_flow_margin_ok_e81a241fb624b075', 'whole_plant_conversion_plant_water_pre_evaluation_defined_ok_84c4b3b2eb329ee0', 'whole_plant_conversion_plant_steam_cycle_main_admission_ok_required_9e7307c18ac5420b', 'whole_plant_conversion_plant_steam_cycle_reheat_admission_ok_required_46e7006e3a4fafe2', 'whole_plant_conversion_plant_steam_cycle_reheat_ua_available_required_34a9b54f6c90ff27', 'whole_plant_conversion_plant_steam_cycle_main_ua_available_required_281cb99c36b65283', 'whole_plant_conversion_plant_source_checks_pressure_ok_e9cb76bbd569aa90', 'whole_plant_conversion_plant_source_checks_flow_ok_04e751f9ce97000b', 'whole_plant_conversion_plant_salt_flow_capacity_capacity_requirement_dd3ff75af1205c2a', 'whole_plant_conversion_plant_steam_actual_approach_hot_gap_ok_8e52cd2d280b334c', 'whole_plant_conversion_plant_steam_actual_approach_cold_gap_ok_f8487fc350489be6', 'whole_plant_conversion_plant_source_basis_heating_coupled_margin_ok_26addbd9a09afc2d', 'whole_plant_conversion_plant_source_basis_heating_wall_margin_ok_7038060d9c96b5f8', 'whole_plant_conversion_plant_source_basis_fusion_envelope_margin_ok_118a84d76a05a76c', 'whole_plant_conversion_plant_source_basis_domain_supported_ok_a7d99ff729662eb5', 'whole_plant_conversion_plant_source_basis_divertor_margin_ok_77e857f8e82a3790', 'whole_plant_conversion_plant_steam_condensate_electric_capacity_capacity_requirement_b4edc0272db0ccfd', 'whole_plant_conversion_plant_steam_whole_outage_margin_ok_90418a10014fb429', 'whole_plant_conversion_plant_steam_whole_domain_supported_ok_d85812a4b8cd9e3f', 'whole_plant_conversion_plant_steam_whole_economic_defined_ok_aec3d165702acb63', 'whole_plant_conversion_plant_steam_feed_electric_capacity_capacity_requirement_b9644c9b953bc0ac', 'whole_plant_conversion_plant_steam_hp_shaft_capacity_capacity_requirement_a3fe202eb6d52755', 'whole_plant_conversion_plant_gas_ledger_balance_d86d965fca008ca2', 'whole_plant_conversion_plant_gas_ledger_net_positive_41d28cae11b1dbd6', 'whole_plant_conversion_plant_steam_feed_pressure_capacity_capacity_requirement_5e891902fcc36704', 'whole_plant_conversion_plant_steam_condensate_flow_capacity_capacity_requirement_9f500cb802e73b3a', 'whole_plant_conversion_plant_generator_capacity_capacity_ok_13f54fade9ec1f3f', 'whole_plant_conversion_plant_steam_reheat_ua_capacity_capacity_requirement_14e2137308151f37', 'whole_plant_conversion_plant_gas_loss_electric_capacity_capacity_requirement_ba3fad80f3006552', 'whole_plant_conversion_plant_gas_whole_domain_supported_ok_bab43aa2eeeee822', 'whole_plant_conversion_plant_gas_whole_outage_margin_ok_25e59eb98c7fca29', 'whole_plant_conversion_plant_gas_whole_economic_defined_ok_5a084f6c1d99295a', 'whole_plant_conversion_plant_he_capacity_capacity_ok_86fcc614bddbfd3c', 'whole_plant_conversion_plant_supplied_core_field_margin_t_ok_4c34d4933dff04fb', 'whole_plant_conversion_plant_supplied_core_identity_supported_ok_121f94d9fa90b835', 'whole_plant_conversion_plant_supplied_core_stress_margin_pa_ok_edd9f45610c1547b', 'whole_plant_conversion_plant_supplied_core_current_margin_ok_c67cdc1d2fb0a885', 'whole_plant_conversion_plant_supplied_core_fit_margin_ok_d3fcebf466168c53', 'whole_plant_conversion_plant_supplied_core_strain_margin_ok_2d8a80d5407aa7bd', 'whole_plant_conversion_plant_water_ic1_flow_margin_ok_1dd1c3a1e5784553', 'whole_plant_conversion_plant_water_ic1_evaluation_defined_ok_1371e750cffff108', 'whole_plant_conversion_plant_water_ic1_duty_margin_ok_dfd546f8f5ee868f', 'whole_plant_conversion_plant_water_ic1_power_margin_ok_5b880ab5fc02b1dc', 'whole_plant_conversion_plant_steam_rejection_capacity_capacity_requirement_550b287c6e69de07', 'whole_plant_conversion_plant_gas_operating_auxiliary_margin_mw_ok_15f9aaa632609eef', 'whole_plant_conversion_plant_gas_operating_annual_net_grid_mwh_ok_1220a0098a3e5f94', 'whole_plant_conversion_plant_gas_operating_domain_supported_ok_e50b966764ec28c8', 'whole_plant_conversion_plant_gas_operating_net_export_mw_ok_58d3569ea9297329', 'whole_plant_conversion_plant_cryogenic_demand_intercept_margin_w_ok_c8cb8040676afc38', 'whole_plant_conversion_plant_cryogenic_demand_cold_margin_w_ok_7dcadae371ddbe6d', 'whole_plant_conversion_plant_cryogenic_demand_domain_supported_ok_e5d086f806f615c2', 'whole_plant_conversion_plant_steam_transport_ihx_capacity_ok_required_98f15d4abb4b4604', 'whole_plant_conversion_plant_steam_transport_motor_factor_ok_required_c7270c7cda57bab6', 'whole_plant_conversion_plant_steam_transport_design_motor_base_ok_required_f884c33dd8381ddf', 'whole_plant_conversion_plant_steam_transport_design_pump_type_ok_required_9883fd28033f69dd', 'whole_plant_conversion_plant_steam_transport_pump_type_ok_required_ddc3748fb76b74c1', 'whole_plant_conversion_plant_steam_transport_salt_head_ok_required_12b011d2b9b50c5e', 'whole_plant_conversion_plant_steam_transport_salt_flow_regime_ok_required_4214cdcb871abc4e', 'whole_plant_conversion_plant_steam_transport_motor_base_ok_required_b639a4539ef58c7f', 'whole_plant_conversion_plant_steam_transport_design_motor_factor_ok_required_388250a54e30378f', 'whole_plant_conversion_plant_steam_transport_design_pump_size_ok_required_0aad92e0e5d98e78', 'whole_plant_conversion_plant_steam_transport_pump_size_ok_required_b7783d5e6b21b1ec', 'whole_plant_conversion_plant_steam_water_cooling_approach_ok_required_8456fcd9f50ebe3a', 'whole_plant_conversion_plant_steam_overheads_domain_supported_ok_79a050b3100a6489', 'whole_plant_conversion_plant_steam_ledger_net_positive_02f91f11a35b318a', 'whole_plant_conversion_plant_steam_ledger_balance_e1489f8b74e321d3', 'whole_plant_conversion_plant_steam_lp_shaft_capacity_capacity_requirement_5eb83cc804af4b97', 'whole_plant_conversion_plant_steam_condensate_pressure_capacity_capacity_requirement_81d8ff0ab723193e', 'whole_plant_conversion_plant_steam_operating_auxiliary_margin_mw_ok_95e4e54a80aa3248', 'whole_plant_conversion_plant_steam_operating_net_export_mw_ok_f2f015c4f9fa63ae', 'whole_plant_conversion_plant_steam_operating_annual_net_grid_mwh_ok_e95e0d4ecf3512d0', 'whole_plant_conversion_plant_steam_operating_domain_supported_ok_8292960083cc99b1', 'whole_plant_conversion_plant_gas_loss_water_cooling_approach_ok_required_8223dadecc4964f5', 'whole_plant_conversion_plant_gas_loss_flow_capacity_capacity_requirement_111ef92c45f0ac07', 'whole_plant_conversion_plant_recuperator_duty_capacity_capacity_requirement_751eb0b036d86809', 'whole_plant_conversion_plant_gas_actual_approach_cold_gap_ok_7e84344c8ebe1f06', 'whole_plant_conversion_plant_gas_actual_approach_hot_gap_ok_5e9b6647fc4988da', 'whole_plant_conversion_plant_steam_gross_capacity_capacity_requirement_9cde1cfefe9e4edb', 'whole_plant_conversion_plant_steam_hp_flow_capacity_capacity_requirement_5cc6b8ef933d65f8', 'whole_plant_conversion_plant_steam_water_flow_capacity_capacity_requirement_682b9c0979ad7556', 'whole_plant_conversion_plant_rejection_capacity_capacity_requirement_af7714dda178b8f0', 'whole_plant_conversion_plant_primary_offer_pressure_margin_pa_ok_76becfa8174fdcbd', 'whole_plant_conversion_plant_primary_offer_inventory_supported_ok_ef44640d09918a5a', 'whole_plant_conversion_plant_primary_offer_electric_margin_mw_ok_fbb614dc306d8b9a', 'whole_plant_conversion_plant_primary_offer_flow_margin_kg_s_ok_8bc805379860ec62', 'whole_plant_conversion_plant_steam_feed_flow_capacity_capacity_requirement_5d9d76d0749190a1', 'whole_plant_conversion_plant_gas_loss_duty_capacity_capacity_requirement_d56ff09d5df0acbc', 'whole_plant_conversion_plant_compressor_capacity_capacity_ok_add1463eda59a898', 'whole_plant_conversion_plant_water_ic2_evaluation_defined_ok_b931519f56a159d1', 'whole_plant_conversion_plant_water_ic2_power_margin_ok_4251efdd4ccb0c52', 'whole_plant_conversion_plant_water_ic2_flow_margin_ok_6696de4f3ee21d56', 'whole_plant_conversion_plant_water_ic2_duty_margin_ok_143f9ca6200e6779', 'whole_plant_conversion_plant_salt_electric_capacity_capacity_requirement_98e5361921299b30', 'whole_plant_conversion_plant_steam_boundary_source_adequate_ok_d29edbaf0da24311', 'whole_plant_conversion_plant_steam_boundary_total_flow_margin_ok_d3ffa1c793b06886', 'whole_plant_conversion_plant_steam_boundary_bypass_fraction_margin_ok_e91d0e0192e4dffd', 'whole_plant_conversion_plant_steam_boundary_temperature_margin_ok_5fbec511bdeb34e1', 'whole_plant_conversion_plant_steam_boundary_pressure_margin_ok_a08fe8a322365c4f', 'whole_plant_conversion_plant_steam_boundary_exchanger_flow_margin_ok_6737739807166519', 'whole_plant_conversion_plant_steam_boundary_controller_capacity_ok_ok_f143197b782aea8e', 'whole_plant_conversion_plant_steam_boundary_added_dp_margin_ok_36cb21eac5ff1b89', 'whole_plant_conversion_plant_steam_boundary_bypass_flow_margin_ok_d79c6541885ab47e', 'whole_plant_conversion_plant_fuel_accounts_stock_margin_ok_84c447972f804892', 'whole_plant_conversion_plant_fuel_accounts_domain_supported_ok_94a59fec46208105', 'whole_plant_conversion_plant_fuel_accounts_processing_margin_ok_860e81215fb2b47f', 'whole_plant_conversion_plant_salt_fill_capacity_capacity_requirement_5ccc7cbd0819713b', 'whole_plant_conversion_plant_steam_main_ua_capacity_capacity_requirement_7df245597c1c6a96')

#: The coverage account, derived at generation from the sealed catalog by
#: `generation/coverage.py::coverage_account` and baked here exactly the way
#: CATALOG_FINGERPRINT and EXPECTED_IDS are. Which gates are applicable and which were
#: assessed depends on the model, never on this candidate's input values, so recomputing it
#: per evaluation would recompute a constant.
COVERAGE = {'authored_usage_total': 125, 'applicable_gate_total': 125, 'assessed_gate_count': 125, 'unassessed_gate_count': 0, 'inapplicable_gate_count': 0, 'unassessed_reasons': {}, 'coverage_state': 'complete'}


class ConstraintReportAggregatorInput(BaseModel):
    model_config = {"extra": "forbid"}

    whole_plant_conversion_plant_steam_lp_flow_capacity_capacity_requirement_a3fe0741c9ecff1c: ConstraintEvaluation
    whole_plant_conversion_plant_salt_shaft_capacity_capacity_requirement_b2367d578fc2f1ec: ConstraintEvaluation
    whole_plant_conversion_plant_steam_condenser_capacity_capacity_requirement_21565c442e22d191: ConstraintEvaluation
    whole_plant_conversion_plant_turbine_capacity_capacity_ok_ee860596098e7f44: ConstraintEvaluation
    whole_plant_conversion_plant_steam_water_electric_capacity_capacity_requirement_e3f37a33f8f86544: ConstraintEvaluation
    whole_plant_conversion_plant_steam_conditions_supported_required_f55a3b19d079007e: ConstraintEvaluation
    whole_plant_conversion_plant_gas_boundary_exchanger_flow_margin_ok_396e8f7ff4b4cd78: ConstraintEvaluation
    whole_plant_conversion_plant_gas_boundary_pressure_margin_ok_57cdec1e34d967ce: ConstraintEvaluation
    whole_plant_conversion_plant_gas_boundary_controller_capacity_ok_ok_b340a8d5e92452b2: ConstraintEvaluation
    whole_plant_conversion_plant_gas_boundary_total_flow_margin_ok_b1cac73884dab807: ConstraintEvaluation
    whole_plant_conversion_plant_gas_boundary_bypass_fraction_margin_ok_c17576ed428ad624: ConstraintEvaluation
    whole_plant_conversion_plant_gas_boundary_bypass_flow_margin_ok_44eb1a31c631c4dc: ConstraintEvaluation
    whole_plant_conversion_plant_gas_boundary_temperature_margin_ok_c3287e1bc91fd77f: ConstraintEvaluation
    whole_plant_conversion_plant_gas_boundary_source_adequate_ok_665dcdd55c247bde: ConstraintEvaluation
    whole_plant_conversion_plant_gas_boundary_added_dp_margin_ok_cb2dbaa41d101ab2: ConstraintEvaluation
    whole_plant_conversion_plant_gas_overheads_domain_supported_ok_37ebb2bb65f0bc13: ConstraintEvaluation
    whole_plant_conversion_plant_water_pre_power_margin_ok_88cf3aa259145f02: ConstraintEvaluation
    whole_plant_conversion_plant_water_pre_duty_margin_ok_43a051525223b723: ConstraintEvaluation
    whole_plant_conversion_plant_water_pre_flow_margin_ok_e81a241fb624b075: ConstraintEvaluation
    whole_plant_conversion_plant_water_pre_evaluation_defined_ok_84c4b3b2eb329ee0: ConstraintEvaluation
    whole_plant_conversion_plant_steam_cycle_main_admission_ok_required_9e7307c18ac5420b: ConstraintEvaluation
    whole_plant_conversion_plant_steam_cycle_reheat_admission_ok_required_46e7006e3a4fafe2: ConstraintEvaluation
    whole_plant_conversion_plant_steam_cycle_reheat_ua_available_required_34a9b54f6c90ff27: ConstraintEvaluation
    whole_plant_conversion_plant_steam_cycle_main_ua_available_required_281cb99c36b65283: ConstraintEvaluation
    whole_plant_conversion_plant_source_checks_pressure_ok_e9cb76bbd569aa90: ConstraintEvaluation
    whole_plant_conversion_plant_source_checks_flow_ok_04e751f9ce97000b: ConstraintEvaluation
    whole_plant_conversion_plant_salt_flow_capacity_capacity_requirement_dd3ff75af1205c2a: ConstraintEvaluation
    whole_plant_conversion_plant_steam_actual_approach_hot_gap_ok_8e52cd2d280b334c: ConstraintEvaluation
    whole_plant_conversion_plant_steam_actual_approach_cold_gap_ok_f8487fc350489be6: ConstraintEvaluation
    whole_plant_conversion_plant_source_basis_heating_coupled_margin_ok_26addbd9a09afc2d: ConstraintEvaluation
    whole_plant_conversion_plant_source_basis_heating_wall_margin_ok_7038060d9c96b5f8: ConstraintEvaluation
    whole_plant_conversion_plant_source_basis_fusion_envelope_margin_ok_118a84d76a05a76c: ConstraintEvaluation
    whole_plant_conversion_plant_source_basis_domain_supported_ok_a7d99ff729662eb5: ConstraintEvaluation
    whole_plant_conversion_plant_source_basis_divertor_margin_ok_77e857f8e82a3790: ConstraintEvaluation
    whole_plant_conversion_plant_steam_condensate_electric_capacity_capacity_requirement_b4edc0272db0ccfd: ConstraintEvaluation
    whole_plant_conversion_plant_steam_whole_outage_margin_ok_90418a10014fb429: ConstraintEvaluation
    whole_plant_conversion_plant_steam_whole_domain_supported_ok_d85812a4b8cd9e3f: ConstraintEvaluation
    whole_plant_conversion_plant_steam_whole_economic_defined_ok_aec3d165702acb63: ConstraintEvaluation
    whole_plant_conversion_plant_steam_feed_electric_capacity_capacity_requirement_b9644c9b953bc0ac: ConstraintEvaluation
    whole_plant_conversion_plant_steam_hp_shaft_capacity_capacity_requirement_a3fe202eb6d52755: ConstraintEvaluation
    whole_plant_conversion_plant_gas_ledger_balance_d86d965fca008ca2: ConstraintEvaluation
    whole_plant_conversion_plant_gas_ledger_net_positive_41d28cae11b1dbd6: ConstraintEvaluation
    whole_plant_conversion_plant_steam_feed_pressure_capacity_capacity_requirement_5e891902fcc36704: ConstraintEvaluation
    whole_plant_conversion_plant_steam_condensate_flow_capacity_capacity_requirement_9f500cb802e73b3a: ConstraintEvaluation
    whole_plant_conversion_plant_generator_capacity_capacity_ok_13f54fade9ec1f3f: ConstraintEvaluation
    whole_plant_conversion_plant_steam_reheat_ua_capacity_capacity_requirement_14e2137308151f37: ConstraintEvaluation
    whole_plant_conversion_plant_gas_loss_electric_capacity_capacity_requirement_ba3fad80f3006552: ConstraintEvaluation
    whole_plant_conversion_plant_gas_whole_domain_supported_ok_bab43aa2eeeee822: ConstraintEvaluation
    whole_plant_conversion_plant_gas_whole_outage_margin_ok_25e59eb98c7fca29: ConstraintEvaluation
    whole_plant_conversion_plant_gas_whole_economic_defined_ok_5a084f6c1d99295a: ConstraintEvaluation
    whole_plant_conversion_plant_he_capacity_capacity_ok_86fcc614bddbfd3c: ConstraintEvaluation
    whole_plant_conversion_plant_supplied_core_field_margin_t_ok_4c34d4933dff04fb: ConstraintEvaluation
    whole_plant_conversion_plant_supplied_core_identity_supported_ok_121f94d9fa90b835: ConstraintEvaluation
    whole_plant_conversion_plant_supplied_core_stress_margin_pa_ok_edd9f45610c1547b: ConstraintEvaluation
    whole_plant_conversion_plant_supplied_core_current_margin_ok_c67cdc1d2fb0a885: ConstraintEvaluation
    whole_plant_conversion_plant_supplied_core_fit_margin_ok_d3fcebf466168c53: ConstraintEvaluation
    whole_plant_conversion_plant_supplied_core_strain_margin_ok_2d8a80d5407aa7bd: ConstraintEvaluation
    whole_plant_conversion_plant_water_ic1_flow_margin_ok_1dd1c3a1e5784553: ConstraintEvaluation
    whole_plant_conversion_plant_water_ic1_evaluation_defined_ok_1371e750cffff108: ConstraintEvaluation
    whole_plant_conversion_plant_water_ic1_duty_margin_ok_dfd546f8f5ee868f: ConstraintEvaluation
    whole_plant_conversion_plant_water_ic1_power_margin_ok_5b880ab5fc02b1dc: ConstraintEvaluation
    whole_plant_conversion_plant_steam_rejection_capacity_capacity_requirement_550b287c6e69de07: ConstraintEvaluation
    whole_plant_conversion_plant_gas_operating_auxiliary_margin_mw_ok_15f9aaa632609eef: ConstraintEvaluation
    whole_plant_conversion_plant_gas_operating_annual_net_grid_mwh_ok_1220a0098a3e5f94: ConstraintEvaluation
    whole_plant_conversion_plant_gas_operating_domain_supported_ok_e50b966764ec28c8: ConstraintEvaluation
    whole_plant_conversion_plant_gas_operating_net_export_mw_ok_58d3569ea9297329: ConstraintEvaluation
    whole_plant_conversion_plant_cryogenic_demand_intercept_margin_w_ok_c8cb8040676afc38: ConstraintEvaluation
    whole_plant_conversion_plant_cryogenic_demand_cold_margin_w_ok_7dcadae371ddbe6d: ConstraintEvaluation
    whole_plant_conversion_plant_cryogenic_demand_domain_supported_ok_e5d086f806f615c2: ConstraintEvaluation
    whole_plant_conversion_plant_steam_transport_ihx_capacity_ok_required_98f15d4abb4b4604: ConstraintEvaluation
    whole_plant_conversion_plant_steam_transport_motor_factor_ok_required_c7270c7cda57bab6: ConstraintEvaluation
    whole_plant_conversion_plant_steam_transport_design_motor_base_ok_required_f884c33dd8381ddf: ConstraintEvaluation
    whole_plant_conversion_plant_steam_transport_design_pump_type_ok_required_9883fd28033f69dd: ConstraintEvaluation
    whole_plant_conversion_plant_steam_transport_pump_type_ok_required_ddc3748fb76b74c1: ConstraintEvaluation
    whole_plant_conversion_plant_steam_transport_salt_head_ok_required_12b011d2b9b50c5e: ConstraintEvaluation
    whole_plant_conversion_plant_steam_transport_salt_flow_regime_ok_required_4214cdcb871abc4e: ConstraintEvaluation
    whole_plant_conversion_plant_steam_transport_motor_base_ok_required_b639a4539ef58c7f: ConstraintEvaluation
    whole_plant_conversion_plant_steam_transport_design_motor_factor_ok_required_388250a54e30378f: ConstraintEvaluation
    whole_plant_conversion_plant_steam_transport_design_pump_size_ok_required_0aad92e0e5d98e78: ConstraintEvaluation
    whole_plant_conversion_plant_steam_transport_pump_size_ok_required_b7783d5e6b21b1ec: ConstraintEvaluation
    whole_plant_conversion_plant_steam_water_cooling_approach_ok_required_8456fcd9f50ebe3a: ConstraintEvaluation
    whole_plant_conversion_plant_steam_overheads_domain_supported_ok_79a050b3100a6489: ConstraintEvaluation
    whole_plant_conversion_plant_steam_ledger_net_positive_02f91f11a35b318a: ConstraintEvaluation
    whole_plant_conversion_plant_steam_ledger_balance_e1489f8b74e321d3: ConstraintEvaluation
    whole_plant_conversion_plant_steam_lp_shaft_capacity_capacity_requirement_5eb83cc804af4b97: ConstraintEvaluation
    whole_plant_conversion_plant_steam_condensate_pressure_capacity_capacity_requirement_81d8ff0ab723193e: ConstraintEvaluation
    whole_plant_conversion_plant_steam_operating_auxiliary_margin_mw_ok_95e4e54a80aa3248: ConstraintEvaluation
    whole_plant_conversion_plant_steam_operating_net_export_mw_ok_f2f015c4f9fa63ae: ConstraintEvaluation
    whole_plant_conversion_plant_steam_operating_annual_net_grid_mwh_ok_e95e0d4ecf3512d0: ConstraintEvaluation
    whole_plant_conversion_plant_steam_operating_domain_supported_ok_8292960083cc99b1: ConstraintEvaluation
    whole_plant_conversion_plant_gas_loss_water_cooling_approach_ok_required_8223dadecc4964f5: ConstraintEvaluation
    whole_plant_conversion_plant_gas_loss_flow_capacity_capacity_requirement_111ef92c45f0ac07: ConstraintEvaluation
    whole_plant_conversion_plant_recuperator_duty_capacity_capacity_requirement_751eb0b036d86809: ConstraintEvaluation
    whole_plant_conversion_plant_gas_actual_approach_cold_gap_ok_7e84344c8ebe1f06: ConstraintEvaluation
    whole_plant_conversion_plant_gas_actual_approach_hot_gap_ok_5e9b6647fc4988da: ConstraintEvaluation
    whole_plant_conversion_plant_steam_gross_capacity_capacity_requirement_9cde1cfefe9e4edb: ConstraintEvaluation
    whole_plant_conversion_plant_steam_hp_flow_capacity_capacity_requirement_5cc6b8ef933d65f8: ConstraintEvaluation
    whole_plant_conversion_plant_steam_water_flow_capacity_capacity_requirement_682b9c0979ad7556: ConstraintEvaluation
    whole_plant_conversion_plant_rejection_capacity_capacity_requirement_af7714dda178b8f0: ConstraintEvaluation
    whole_plant_conversion_plant_primary_offer_pressure_margin_pa_ok_76becfa8174fdcbd: ConstraintEvaluation
    whole_plant_conversion_plant_primary_offer_inventory_supported_ok_ef44640d09918a5a: ConstraintEvaluation
    whole_plant_conversion_plant_primary_offer_electric_margin_mw_ok_fbb614dc306d8b9a: ConstraintEvaluation
    whole_plant_conversion_plant_primary_offer_flow_margin_kg_s_ok_8bc805379860ec62: ConstraintEvaluation
    whole_plant_conversion_plant_steam_feed_flow_capacity_capacity_requirement_5d9d76d0749190a1: ConstraintEvaluation
    whole_plant_conversion_plant_gas_loss_duty_capacity_capacity_requirement_d56ff09d5df0acbc: ConstraintEvaluation
    whole_plant_conversion_plant_compressor_capacity_capacity_ok_add1463eda59a898: ConstraintEvaluation
    whole_plant_conversion_plant_water_ic2_evaluation_defined_ok_b931519f56a159d1: ConstraintEvaluation
    whole_plant_conversion_plant_water_ic2_power_margin_ok_4251efdd4ccb0c52: ConstraintEvaluation
    whole_plant_conversion_plant_water_ic2_flow_margin_ok_6696de4f3ee21d56: ConstraintEvaluation
    whole_plant_conversion_plant_water_ic2_duty_margin_ok_143f9ca6200e6779: ConstraintEvaluation
    whole_plant_conversion_plant_salt_electric_capacity_capacity_requirement_98e5361921299b30: ConstraintEvaluation
    whole_plant_conversion_plant_steam_boundary_source_adequate_ok_d29edbaf0da24311: ConstraintEvaluation
    whole_plant_conversion_plant_steam_boundary_total_flow_margin_ok_d3ffa1c793b06886: ConstraintEvaluation
    whole_plant_conversion_plant_steam_boundary_bypass_fraction_margin_ok_e91d0e0192e4dffd: ConstraintEvaluation
    whole_plant_conversion_plant_steam_boundary_temperature_margin_ok_5fbec511bdeb34e1: ConstraintEvaluation
    whole_plant_conversion_plant_steam_boundary_pressure_margin_ok_a08fe8a322365c4f: ConstraintEvaluation
    whole_plant_conversion_plant_steam_boundary_exchanger_flow_margin_ok_6737739807166519: ConstraintEvaluation
    whole_plant_conversion_plant_steam_boundary_controller_capacity_ok_ok_f143197b782aea8e: ConstraintEvaluation
    whole_plant_conversion_plant_steam_boundary_added_dp_margin_ok_36cb21eac5ff1b89: ConstraintEvaluation
    whole_plant_conversion_plant_steam_boundary_bypass_flow_margin_ok_d79c6541885ab47e: ConstraintEvaluation
    whole_plant_conversion_plant_fuel_accounts_stock_margin_ok_84c447972f804892: ConstraintEvaluation
    whole_plant_conversion_plant_fuel_accounts_domain_supported_ok_94a59fec46208105: ConstraintEvaluation
    whole_plant_conversion_plant_fuel_accounts_processing_margin_ok_860e81215fb2b47f: ConstraintEvaluation
    whole_plant_conversion_plant_salt_fill_capacity_capacity_requirement_5ccc7cbd0819713b: ConstraintEvaluation
    whole_plant_conversion_plant_steam_main_ua_capacity_capacity_requirement_7df245597c1c6a96: ConstraintEvaluation


class ConstraintReportAggregatorOutput(MultiOutput):
    constraint_report: ConstraintReport


class ConstraintReportAggregatorModule(
    ModuleBase[ConstraintReportAggregatorInput, ConstraintReportAggregatorOutput]
):
    name: str = "constraint_report_aggregator"
    version: str = "v0.1"

    CATALOG_FINGERPRINT = "865627e597900292db102f4a1dda4fd26e1628d4f7a165f765102326f66a4ae4"

    def run(self, **evaluations) -> ModuleResult[ConstraintReportAggregatorOutput]:
        validated = ConstraintReportAggregatorInput(**evaluations)
        results = [getattr(validated, cid) for cid in EXPECTED_IDS]
        statuses = [r.status for r in results]
        coverage = CoverageAccount(**COVERAGE)

        # Statuses decide the top two arms; the account decides the rest. The status set
        # contains only occurrences of applicable assessed gates by construction, so the
        # `violation` arm cannot fire from a gate outside the denominator: an inapplicable
        # gate is either unassessed (no entries, no results) or refused at generation.
        #
        # Result-list non-emptiness stops deciding anything. That was the whole defect —
        # `all_satisfied` meant "nothing that arrived failed", whatever fraction arrived.
        if "violated" in statuses:
            headline = "violation"
        elif "indeterminate" in statuses:
            headline = "indeterminate"
        elif coverage.unassessed_gate_count == 0 and coverage.assessed_gate_count > 0:
            headline = "full_satisfaction"
        elif coverage.applicable_gate_total > 0:
            headline = "partial_coverage"
        else:
            headline = "not_assessed"
        return ModuleResult(
            data=ConstraintReportAggregatorOutput(
                constraint_report=ConstraintReport(
                    catalog_fingerprint=self.CATALOG_FINGERPRINT,
                    assessed_entry_count=len(results),
                    headline=headline,
                    coverage=coverage,
                    results=results,
                )
            )
        )
