"""Write executor interpretation from this record's stored native evidence only."""
import json
from pathlib import Path

R=Path(__file__).resolve().parent
read=lambda p:json.loads((R/p).read_text())
a=read('results/analysis.json'); axes=read('axis-plan.json')['axes']; groups=read('axes.json')['groups']
cases={x['case']:x for x in a['cases']}; raw={x['case']:x for x in read('results/cases.json')['cases']}
constraints=read('results/constraint_catalog.json'); preflight=read('results/integration/preflight_results.json')
P='aries_integrated_plant__'
short=lambda cid:cid.removeprefix(P).split('__')[0]+'.'+constraints[cid]['source_local_identity']
f=lambda value:f'{value:,.6f}'
base=a['baseline']
lines=[]
def para(text):lines.extend([text,''])
def heading(n,name):para(f'## {n}. {name}')
def table(header,rows):
 para('| '+' | '.join(header)+' |\n| '+' | '.join('---' for _ in header)+' |\n'+'\n'.join('| '+' | '.join(map(str,row))+' |' for row in rows))

heading(1,'Study header')
para('Study id: `20260922-aries-integrated-equipment-costs`. Package: `aries_integrated`. Date executed: 2026-09-22. Executor: equipment_study agent, T-006. Mode: execute. Single arm: `arm-declared-sensitivity`, containing canonical, thermal, demand and selected-equipment point families. All 64 exact proposals executed once and completed at commit `e8f9cc1d59a0583fb1b2b2ca4eaa51d87b891c2f`. Exact commands and execution authority are in `results/execution-context.json`. The coordinator owns final snapshot/archive creation and commitment.')
heading(2,'Intake')
para('[OWNER-VERBATIM: supplemental owner message captured in the goal]\n\n> Before ranking equipment or economic alternatives, test sensitivity to the principal thermal assumptions and connect each varied equipment capability to its selected inventory, purchase cost and applicable operating demand. Preserve the source-case failures and label the 423.1 MW case as the assumed integrated baseline.')
para('[OWNER-VERBATIM: retained owner brief]\n\n> For this prompt, I authorize explicitly labeled diagnostic/sensitivity-only sweeps of declared assumptions even when no modeled constraint resists them. Record the missing constraint response and development finding before execution. This does not authorize optimizing an unresisted parameter or calling its endpoint an engineering optimum. Do not invent physical pushback.')
para('[AGENT] One dependency question joins the point families: how do thermal assumptions and explicitly purchased choices alter operating demands, adequacy and cost while preserving independent inventory? The coordinator approved four canonical cases, 50 endpoints across 25 thermal axes, four recuperator/PbLi-temperature interactions, two density-demand perturbations and four purchased-capability probes. Price uncertainty belongs to the next round. Initial wider endpoint suggestions were narrowed to the accepted design where applicable; the declared engineered windows and units are in `axis-plan.json`.')
heading(3,'Objective and result')
para('LCOE objective/result: not applicable; this package produces thermal, inventory and cost inputs for a later financial analysis. The thermal headline is `aries_integrated_plant__plant_ledger__evaluate__net_electric`, MW. The assumed integrated baseline remains 423.106794 MW net with zero unmet heat and all 14 represented checks satisfied. Scientific qualification flags remain unsupported. Across the 64 points, 53 satisfy every represented check and 11 retain violations; no runtime point refused. `results/cases.json` preserves every native output and verdict; `results/analysis.json` joins them to named cases.')
para('Thermal sensitivity was interpreted before equipment or cost comparisons. Cycle-flow changes have the largest net effect over the declared windows, but both endpoints fail a represented check: 1,000 kg/s reports 596.773 MW with 138.638 MW unremoved heat; 1,800 kg/s reports 149.663 MW while exceeding compressor capacity. Those numbers describe constraint-failing operating cases, not usable generation alternatives. Neutron multiplication, recuperator effectiveness and He operating flow also materially change net output. The net-flat U, bulk-limit, partition and PbLi-cp tests all retain zero unmet heat at these selected points; this identifies spare modeled capability near this nominal, not general irrelevance.')
para('All 56 thermal/demand points retain every upfront purchase account and the 4.350208470 billion USD2004 overnight total exactly. Density changes alter fuel throughput/annual cost at fixed purchases. Selected He HX area and pump rating change their purchase accounts and meaningful adequacy outcomes. They demonstrate dependencies, not an economic optimum. `thermal-results.md` and `results/analysis.json` contain the full thermal reading; `report.md` presents the conditional cost boundary after that reading.')
heading(4,'Constraint outcomes')
para('Every executing constraint is listed by exact identity below. Status counts cover all 64 points; the complete case memberships are in `results/analysis.json` under constraint_outcomes. A satisfied scalar screen is not evidence of scientific qualification. The canonical source cases remain constraint-failing.')
table(['constraint_id','source_local_identity','Satisfied','Violated','Violation cases'],[(cid,constraints[cid]['source_local_identity'],len(states.get('satisfied',[])),len(states.get('violated',[])),', '.join(states.get('violated',[])) or 'none') for cid,states in sorted(a['constraint_outcomes'].items())])
heading(5,'Framing')
para('As proposed: all 28 axes are sensitivity, including the two purchased-capability probes and fixed-hardware density demand. As judged: sensitivity remains appropriate for every axis; no framing changed. Finite endpoints show responses or observed failures, not a feasible-region boundary or optimum. Ranking the size of net changes across different engineered windows is not a probability-weighted uncertainty ranking or an intrinsic parameter-importance ranking.')
heading(6,'Per-axis account')
for axis in axes:
 name=axis['axis']; lo=cases[name+'-low']; hi=cases[name+'-high']
 para(f'#### {name} — feasible structure (search framing)\n\n**Applies:** not applicable; sensitivity-framed.')
 failures='; '.join(x['case']+': '+', '.join(short(c) for c in x['violated_constraints']) for x in (lo,hi) if x['violated_constraints']) or 'Neither endpoint violates a represented check.'
 para(f"#### {name} — observed response (sensitivity framing)\n\n**Applies:** yes. Low/high inputs {axis['values'][0]:g}/{axis['values'][1]:g} {axis['units']} give net {lo['metrics']['net_MW']:.6f}/{hi['metrics']['net_MW']:.6f} MW and unmet heat {lo['metrics']['unmet_MW']:.6f}/{hi['metrics']['unmet_MW']:.6f} MW. {failures} Failed-case net is not a usable power alternative. No boundary claim is made. Missing response: {axis['missing_response']}. Exact case outputs are in `results/cases.json`.")
para('The four interaction cases combine recuperator effectiveness 0.60/0.95 with PbLi hot limit 961.15/1061.15 K. They all satisfy the represented checks; net remains approximately 310.052702 MW at 0.60 and 557.114222 MW at 0.95, without a meaningful PbLi-limit interaction in this window. This does not establish behavior outside the tested corners.')
heading(7,'Axis groups')
para('Every case carries all 411 generated entry fields. The 28 axes cover 32 declared keys. Only the common sink and common compressor-efficiency groups use ties, declared by the executor as common operating/assumption choices. Different coolant owners and plasma/deposition fractions remain independent. The complete maps in proposed-points.json equal the stored inputs exactly.')
table(['Axis','Entry key','Provenance','Tie authority'],[(g['axis'],k['key'],k['provenance'],'Executor-declared common assumption' if k['provenance']=='tie' else 'Single source owner; native internal fan-out') for g in groups for k in g['keys']])
para('Area and assumed U replace the old free UA keys. Pump flow/efficiency or explicit literal fixed-power mode replace independent nominal pump electrical inputs. Selected tritium kg is the shared stock authority; the old dormant-atoms input retires. No dependent demand chooses installed area, rating or stock. Historical records remain unchanged; prior preparation receipts are preserved separately in goal evidence.')
heading(8,'Indicators and rulings')
para('All 28 groups report constraints_reachable in `indicators.json`; none reports no_constraint_response. This is a possible module path, not measured physical pushback. The top-level indicator warning list is empty; the native suffix scan separately emits nine advisory sibling warnings, disposed in §9. The owner’s quoted sensitivity-only authorization covers unresisted assumptions; known missing physical responses were recorded before execution as findings #1–#3 and in axis-plan.json.')
para('Not derivable from indicators: monotonicity of a channel in an axis; identity of the same physical quantity across different names; intra-module operand dependency. Unresisted is the executor’s judgment, not a tool output. Fixed-budget recuperator quality, qualified materials/transport, machine maps, hydraulic/MHD detail, auxiliary subsystem physics and demand-derived replacement life remain absent despite reachable aggregate predicates.')
heading(9,'Preflight results')
para('Native integration CANDIDATE passed all ten gates before release. Its six mechanical study preflight gates are retained in `results/integration/preflight_results.json`; identity and baseline documents are `results/package_identity.json` and `results/baseline_result.json`. The baseline gate pins two unique local predicates; the repeated capacity local name is certified separately through all exact stored IDs and all-point numerical rederivation.')
table(['Gate','Outcome','Detail'],[(g['gate'],g['status'],g['detail']) for g in preflight['gates']])
para('The nine suffix advisories do not identify missing ties. Plasma helium fraction and deposited-heat helium fraction represent different physics. Compressor efficiency is not the same assumption as either other primary-pump efficiency. The three pumps and exchangers have independently selected efficiency, area and flow-capacity owners. The He-only hardware probes hold the other branches fixed deliberately. The warnings are preserved, not suppressed or converted into invented equalities.')
heading(10,'Execution route and why')
para('Route: study-local direct API using the delivered strict package loader, PreparedEvaluator, PreparedListStrategy, StudyRunner and SQLite store lifecycle. Complete coordinated points and explicit ties motivated the prepared-list route. The candidate reproduced the pinned baseline and the single stored invocation completed all 64 proposals. Glue ledger: none; no runtime physical adapter or caller-side plant arithmetic supplied an output. The record-local analysis reads native outputs and computes only comparisons/counts. Exact execution, all-point verification and analysis commands are in results/execution-context.json.')
heading(11,'Study definition and window provenance')
para('Windows are engineered from the accepted thermal/equipment design, not sourced applicability envelopes. The corrected package’s independent oracle evaluated all 64 proposed maps with no domain refusal before native execution; oracle-window-scan.json retains the scan. He HX area endpoints bracket heat removal and He pump capacity endpoints bracket a scalar flow margin; these were used to retain useful diagnostic points, not to claim a boundary. The low-area price is explicitly extrapolated. After a citation-only executable reseal, exact canonical inputs/outputs were preserved and preparation was repeated under the final identity; prior receipts remain preserved outside this unfinished record.')
heading(12,'Cross-fingerprint correlation and what it means')
para('Single fingerprint across every stored case; no cross-arm correlation is needed. The prior frozen WI-089 study and earlier preparation checkpoints are historical evidence, not additional stored arms. The source-conditioned configurations retain their own full maps and failed thermal outcomes. The new selected 10 kg stock intentionally changes required-breeding and fuel-cost diagnostics without changing inherited thermal results; breeding support stays unsupported.')
heading(13,'Verification')
para('PASS: all 64 stored rows were independently checked, covering all seven observed verdict-combination strata. Each row compares 278 numeric channels and rederives all 14 exact predicate statuses: 17,792 scalar and 896 predicate comparisons, zero mismatches. The standard relative tolerance is 1e-9, with only the inherited residual-magnitude channel allowed 1e-7 MW absolute error. No monetary tolerance was relaxed. The reported large worst relative deviation is a near-zero residual comparison covered by that dimensional tolerance, not a failed physical result. `results/verification_summary.json` retains sampling, channel identities, predicates and the actual outcome.')
para('The oracle independently integrates plasma profiles, solves thermal closure with Brent’s method, calculates selected-area/pump/stock/account/schedule arithmetic, and reconstructs source comparisons. It imports no generated physical arithmetic. Numerical agreement checks implementation and wiring under shared equation authority; it does not independently validate the source tables or qualify the scientific approximations. Copied supplied amounts/year/support flags are transport checks, not independent science. Broad published outputs outside the 278-channel catalog remain unverified numerically. The checker-local variable-shadowing failure from preparation is retained, followed by passing correction; it changed no package or stored result.')
heading(14,'Review outcomes')
para('The coordinator released T-006 only after accepted source/design/implementation review and native CANDIDATE at execution commit e8f9cc1d. The coordinator freeze will copy source-review.md, design-review.md and implementation-review.md under results/sources/ with their original paths and hashes. These reviews cover model semantics and preservation; the executor does not label its own numerical interpretation an independent review. The completed record remains ready for the coordinator’s final record check/freeze. No new source interpretation or model equation was introduced during execution.')
heading(15,'Findings')
findings=[
('1','model','Recuperator effectiveness and material/transport/machine assumptions lack qualified geometry or scientific response despite graph reachability.','Sensitivity only under owner authorization; no endpoint optimum or qualified-performance claim.','work/active/WI-090_aries-integrated-equipment-and-costs/design.md'),
('2','model','Primary flow uses a cubic pump proxy; hydraulic/MHD qualification, machine maps and demand-derived replacement life remain absent.','Preserve independent installed ratings and selected replacement schedules; carry proxy limits.','work/active/WI-090_aries-integrated-equipment-and-costs/design.md'),
('3','model','Low He HX area is0.1 times reference, outside the0.5–1.5 local linear purchase comparison range although E2 permits the capability diagnostic.','Retain extrapolated flag and adverse heat-removal outcome; no qualified low-price alternative claim.','work/active/WI-090_aries-integrated-equipment-and-costs/design.md'),
('4','model','Cycle flow produces the largest net change over declared thermal endpoints; low flow fails heat removal and high flow fails compressor capacity.','Report constraint-failing net separately; do not select an operating optimum from this finite sweep.','record.md §6; results/analysis.json'),
('5','model','Nominal U/hot-limit/partition/PbLi-cp sweeps and the four tested recuperator/PbLi-limit corners retain enough modeled heat-transfer capability.','Retain local nonresponse; do not generalize beyond the engineered windows or confuse it with missing graph connections.','thermal-results.md'),
('6','model','All56 thermal/demand cases preserve every upfront purchase account and overnight total; density changes fuel throughput and annual costs.','Accept bounded MR-7 evidence; preserve declared operating-versus-purchase roles.','results/analysis.json'),
('7','model','Selected He area changes cost/capability, and selected pump capacity changes purchase cost/margin at fixed operating demand.','Accept explicit inadequate/adequate purchase probes; no hidden sizing or economic optimum.','report.md; results/cases.json'),
('8','model','All three source-conditioned canonical cases retain heat-removal failures; literal Raffray also fails the energy-balance screen.','Carry adverse source outcomes forward unchanged; no usable published-plant power claim.','results/cases.json'),
('9','model','The no-recovery-credit baseline prices104.667707kg/y external T and makes assumed tritium supply dominate annual cost.','Pursue the separately authorized cost-uncertainty/supply scenarios next round; this is not a breeding prediction.','work/orchestration/goals/aries-integrated-equipment-costs/goal.md'),
('10','model','Native source-account, known-mass, LiPb-rate and replacement comparisons retain nonzero mismatches and VF mass unavailability.','Preserve disjoint source/provisional boundaries; do not normalize mismatches or infer missing mass as zero.','report.md; results/cases.json')]
table(['Id','Kind','Finding','Disposition','Home'],[(R.name+'#'+i,kind,claim,disposition,home) for i,kind,claim,disposition,home in findings])
heading(16,'Snapshot')
para('Coordinator-owned finalization pending: snapshot.json and sealed-package.tar.gz have not been created by the executor. Resolve the snapshot SHA256 here after the coordinator captures the exact package, tools, complete manifest, stores and artifact hashes. No record commitment occurred during T-006.')
heading(17,'What this record does not contain')
para('No full price-uncertainty range, assumed-recovery100kg/year scenario, LCOE, financial cashflow treatment, global optimum or scientific qualification is present. No negative-export study point occurred, so its tariff branch is not exercised by this study. The record provides a conditional operating/equipment dependency result and a declared baseline cost boundary. Final independent record acceptance and coordinator snapshot/archive remain pending at this handoff.')
(R/'record.md').write_text('\n'.join(lines))

thermal=['# Thermal sensitivity reading','','[AGENT] Executor interpretation from stored native results. Read this before the equipment/cost discussion. Every number below is a named low/high case in results/cases.json; results/analysis.json retains the full mapping. Net output from a case with a violated engineering check is a diagnostic value, not a usable plant alternative.','',
'| Axis | Low/high input | Units | Low/high net MW | Low/high unmet MW | Violations |','|---|---|---|---|---|---|']
for x in a['thermal_finite_perturbation_order']:
 violations='; '.join(name+': '+', '.join(short(c) for c in ids) for name,ids in x['violations'].items() if ids) or 'none'
 thermal.append(f"| {x['axis']} | {x['values'][0]:g} / {x['values'][1]:g} | {next(z['units'] for z in axes if z['axis']==x['axis'])} | {x['low']['net_MW']:.3f} / {x['high']['net_MW']:.3f} | {x['low']['unmet_MW']:.3f} / {x['high']['unmet_MW']:.3f} | {violations} |")
thermal+=['','[AGENT] Rows are ordered by maximum absolute net change from the assumed423.106794MW baseline over these engineered endpoints. The windows differ in physical meaning and width, so this is a finite-perturbation comparison, not a probability-based uncertainty ranking. Cycle flow, neutron multiplier, recuperation and helium circulation deserve attention within this approximation. Heat removal and installed capacities must be considered together with net output.','',
'[AGENT] Net-flat thermal axes are not all disconnected. U changes calculated UA while inventory remains fixed; branch flow/cp and bulk bounds enter the finite exchanger calculation. In these particular nominal windows, all available source heat is still accepted. Partition changes redistribute branch duty but leave the total accepted heat unchanged. These results cannot establish global nonresponse. Four recuperator/PbLi-hot-limit corners likewise show no additional hot-limit effect within their sampled window.','',
'[AGENT] All54 thermal points preserve the complete upfront purchase-account set and overnight total exactly. Pump electrical demand responds to operating flow/efficiency through the disclosed proxy. Recuperator/material/machine-quality and auxiliary assumptions lack the corresponding qualified performance/purchase coupling. No endpoint is promoted to an optimized design.','']
(R/'thermal-results.md').write_text('\n'.join(thermal))

report=f'''# Integrated equipment study result

[AGENT] Executor reading. The64-point native study reproduces the assumed423.106794MW baseline, exposes thermal/capacity failures and preserves independent purchased inventory. Verification covers every stored point:17,792 numeric comparisons and896 exact predicates pass. Eleven cases fail represented engineering checks and remain in the record. These are conditional model results, not scientific qualification.

## Thermal assumptions first

The largest declared thermal response comes from cycle flow, with both endpoints constraint-failing. Neutron multiplier, recuperator effectiveness and He circulation also materially affect net power. The lower-flow cycle's higher reported export accompanies138.638MW unremoved heat; it is not usable generation. The higher-flow case exceeds the purchased compressor rating. U, bulk hot limits, heat partition and PbLi cp show no meaningful net response in the chosen nominal windows because represented heat removal remains sufficient. The four recuperator/PbLi-limit corners add no measured interaction beyond recuperation. See thermal-results.md for all25 axes and record.md for exact predicates. This finite scan establishes no optimum or general boundary.

## Fixed hardware and selected purchases

Both density points retain identical initial purchase accounts and the4.350208470billion USD2004 overnight total. Net output changes from140.230696 to735.759323MW while fuel exhaust and annual supply cost respond; both points satisfy represented checks. The56 thermal/demand cases all preserve upfront purchase accounts. Replacement life/schedule remains a chosen assumption, so demand does not silently resize or replace hardware.

The He exchanger area probe buys5,000 or75,000m² at fixed U=1,000W/(m²K). The low choice yields47.118607MW unmet heat and fails heat removal; its linear price is explicitly extrapolated. The high choice clears heat removal and leaves nominal net output unchanged. The He pump probe buys1,630.5 or4,891.5kg/s flow capacity at fixed3,261kg/s operating flow. Margins change from−1,630.5 to+1,630.5kg/s while operating pump draw/net output stay fixed. These tests connect purchased inventory, cost and applicable demand; they do not rank economic alternatives.

## Conditional baseline cost boundary

Every amount here is USD2004. Native direct capital is2,919,603,000; overnight capital is4,350,208,470 including declared indirect, contingency and owner/commissioning allowances. The separate source direct budget is2,619,572,000; the300,031,000 difference comprises the added300,000,000 initial tritium stock and retained31,000 core mismatch. The source-inclusive multiplier remains a separate comparison and is not relabeled overnight capital.

Native annual operating cost is3,215,100,712.857. It is dominated by3,140,031,210.697 for104.667707kg/year assumed external tritium under zero supplied recovery credit and30million USD2004/kg. This is a deliberately assumed supply boundary, not a prediction of zero breeding or a qualified price. Initial10kg stock is capital and calendar-time decay/operating fuel is annual; they are separate. A later price/supply uncertainty study is required before stronger economic conclusions.

Scheduled replacement has six events of72,231,350 at5.882353-year intervals, first at5.882353 and last at35.294118 years:433,388,100 undiscounted lifetime total. The12,279,329.5/year reserve is a separate planning channel, not a second cash expense to add to those events. Selected availability, component life, makeup fraction and scope remain assumptions; no demand-to-damage model is claimed.

## Reconciliation remains explicit

Native source comparisons retain reactor parent-minus-children28,396,000, core children-minus-parent31,000, coil children-minus-parent5,287,000 and fuel parent-minus-children1,000. Known selected dry inventory is15,021,700kg,1,333,700kg above the source13,688,000kg boundary; it includes the stated cryostat scope and lacks a known VF-coil mass, so the difference is not a closed matching-boundary error. LiPb's selected8,830,000kg at17.1/kg gives150,993,000, which is334,000 below the151,327,000 source account. The source replacement comparison retains975,000,000 from75,000,000×13 versus966,000,000 printed, and10,946,000kg from842,000kg×13. None is silently normalized or counted twice.

The nominal-source, literal-Lyon and literal-Raffray cases retain158.725848,398.908524 and502.134202MW unmet heat respectively. Literal Raffray also retains the inherited energy mismatch. Their reported electrical outputs are constraint-failing diagnostics, not deliverable source-plant generation. Missing field/conductor/breeding, hydraulics, materials and machine-map qualification remains visible.

## Evidence and next use

All figures trace to results/cases.json and results/analysis.json. All-point verification is results/verification_summary.json; full proposals and exact input roles remain in this record. Execution used commit e8f9cc1d59a0583fb1b2b2ca4eaa51d87b891c2f and the sealed identity in results/package_identity.json, with the native TEAx environment and commands in results/execution-context.json. No package changed during this study. The result supports the integrated dependency question and supplies a conditional cost baseline; the goal's broader assumption-ranked economic range remains for the next round.
'''
# Source paragraphs remain one line; add spaces around common number/unit prose joins.
for old,new in {'The64':'The 64','assumed423':'assumed 423','point:17':'point: 17','and896':'and 896','accompanies138':'accompanies 138','all25':'all 25','the4.':'the 4.','from140':'from 140','to735':'to 735','The56':'The 56','buys5':'buys 5','or75':'or 75','fixed U=1,000W':'fixed U=1,000 W','yields47':'yields 47','buys1,630':'buys 1,630','or4,891':'or 4,891','fixed3,261':'fixed 3,261','from−1':'from −1','to+1':'to +1','capital is2':'capital is 2','capital is4':'capital is 4','budget is2':'budget is 2','the300':'the 300','added300':'added 300','retained31':'retained 31','cost is3':'cost is 3','by3,140':'by 3,140','for104':'for 104','and30million':'and 30 million','Initial10':'Initial 10','of72':'of 72','at5':'at 5','at35':'at 35','years:433':'years: 433','The12':'The 12','children28':'children 28','parent31':'parent 31','parent5':'parent 5','children1,000':'children 1,000','is15':'is 15','kg,1,333':'kg, 1,333','source13':'source 13','selected8':'selected 8','at17':'at 17','gives150':'gives 150','is334':'is 334','the151':'the 151','retains975':'retains 975','from75':'from 75','versus966':'versus 966','and10,946':'and 10,946','from842':'from 842','retain158':'retain 158',',398':', 398','and502':'and 502'}.items():report=report.replace(old,new)
(R/'report.md').write_text(report)
# Append only first sightings. Existing #1-3 rows are preserved byte-for-byte.
log=R.parent/'DISCOVERY_LOG.md';text=log.read_text()
for i,kind,claim,disposition,home in findings:
 identity=R.name+'#'+i
 if identity not in text:text+=f'| 2026-09-22 | {kind} | {identity} | {claim} | {disposition} | {home} |\n'
log.write_text(text)
print(json.dumps({'record_sections':17,'findings':len(findings),'case_count':len(cases),'report':'report.md'}))
