"""Design-search proof of life: (R, a) grid + availability sweep through the
stock teax study layer, on the committed Stellaris generated package.

What this is: the first real design-search study on the stellarator demo model
(epic Item 5, first cut). Two studies run through teax's delivered study
machinery (PreparedListStrategy -> StudyRunner -> StudyStore -> StudyQuery, no
hand-rolled sweep loops):

  A. 2D grid over the two causal geometry levers — major radius R, minor
     radius a — LCOE + all 5 viability verdicts recorded per point.
  B. 1D sweep over availability (operations lever), same recording.

Axis rule compliance (modeling_project/STUDY_POLICY.md §2):
axes are causal design levers, declared at the SysML-attribute level and
expanded to their complete entry-key set. `magnet__R0` rides with R as a
DECLARED PHYSICAL-IDENTITY TIE [AGENT]: the magnet-cost Ampere's-law current
runs on the major radius (total_kAm = G*B*R0*r_coil/mu0) — same physical
quantity, separately authored attribute, so it is recorded as a tie, not as
mechanical fan-out of one attribute.

The route itself — stock strict loader, axis expansions, tie, windows, validity
mask, exported columns, baseline executor — is the package-owned
`studies/study_route.py`; this file is the command-line front for the two
proof-of-life studies. Since the stellarator model migration (2026-08-21) the
package is sealed at runtime contract 2.0.0 and runs on stock teax with no glue:
the values the July harness injected (BOP repoint, CAS28, n_mod, per-point CAS27,
schema fillers) are authored in the model and generated by codegen.

Teax comes from `STOP_PARSER_TEAX_ROOT` (a teax checkout; `packages/teax-simkit`
goes on sys.path), the sealed-runner contract the study tests also use.

Outputs go under `study/_work/` (gitignored): the study stores plus the exported
CSVs. The committed `design_search_R_a.csv` / `availability_sweep.csv` beside this
file are the July proof-of-life's evidence (`studies/BEFORE_MIGRATION_RECORD.md`)
and are never overwritten by this script.

Verification is the generic tool: `scripts/study/verify.py` samples the stores
against the package's oracle seam (`studies/oracle_entry.py`).

Run (from the repository root, with STOP_PARSER_TEAX_ROOT exported):
    uv run python exploration/stellarator_e2e/study/run_design_search.py run
    uv run python exploration/stellarator_e2e/study/run_design_search.py export
"""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
E2E = HERE.parent
WORK = HERE / "_work"

TEAX_ROOT_ENV = "STOP_PARSER_TEAX_ROOT"


def _put_teax_on_path() -> None:
    root = os.environ.get(TEAX_ROOT_ENV)
    if not root:
        raise SystemExit(f"{TEAX_ROOT_ENV} is not set; point it at a teax checkout")
    simkit = Path(root) / "packages" / "teax-simkit"
    if not simkit.is_dir():
        raise SystemExit(f"{TEAX_ROOT_ENV}={root} has no packages/teax-simkit")
    sys.path.insert(0, str(simkit))


_put_teax_on_path()
sys.path.insert(0, str(E2E / "studies"))

import study_route as route  # noqa: E402  (package-owned; the route proper)


def _pinned_headline() -> tuple[str, float]:
    manifest = json.loads(route.MANIFEST_PATH.read_text())
    headline = manifest["baseline"]["headline"]
    return headline["channel"], float(headline["value"])


def _baseline_gate(cases) -> None:
    """The grid's baseline point must reproduce the manifest's pinned headline."""
    baseline = [
        c for c in cases
        if c.inputs[route.AXES["R"][0]] == route.BASELINE["R"]
        and c.inputs[route.AXES["a"][0]] == route.BASELINE["a"]
    ]
    if not baseline:
        raise SystemExit("baseline point missing from study A")
    channel, pinned = _pinned_headline()
    lcoe = baseline[0].outputs[channel]
    if abs(lcoe - pinned) / pinned >= 1e-9:
        raise SystemExit(f"baseline LCOE {lcoe!r} is off the pinned {pinned!r}")
    if not all(status == "satisfied" for status in baseline[0].verdicts.values()):
        raise SystemExit(f"baseline verdicts: {route.short_verdicts(baseline[0])}")
    print(f"[gate] baseline reproduces pinned headline: LCOE {lcoe:.9f}, "
          f"{len(baseline[0].verdicts)}/{len(baseline[0].verdicts)} satisfied")


def assert_package_untouched() -> None:
    out = subprocess.run(
        ["git", "status", "--porcelain", str(route.PACKAGE_DIR)],
        capture_output=True, text=True, cwd=E2E,
    ).stdout.strip()
    if out:
        raise SystemExit(f"committed package was MUTATED:\n{out}")
    print("[gate] committed package byte-untouched (git clean)")


def cmd_run() -> None:
    WORK.mkdir(exist_ok=True)
    grid = route.design_search_proposals()
    excluded = len(route.R_VALUES) * len(route.A_VALUES) - (len(grid) - 1)
    print(f"[study A] {len(grid)} proposals ({excluded} geometrically invalid "
          f"points excluded by R > a + {route.BUILD_STACK_M}); baseline appended")
    cases_a, _ = route.run_points("stellarator-design-search-ra-v1", grid, WORK)
    completed_a = route._completed(cases_a, "design search")
    print(f"[study A] {len(completed_a)}/{len(cases_a)} cases completed")

    sweep = route.availability_sweep_proposals()
    cases_b, _ = route.run_points("stellarator-availability-sweep-v1", sweep, WORK)
    completed_b = route._completed(cases_b, "availability sweep")
    print(f"[study B] {len(completed_b)}/{len(cases_b)} cases completed")

    _baseline_gate(cases_a)
    assert_package_untouched()
    radius_rows = route.csv_rows(completed_a, ["R", "a"])
    availability_rows = route.csv_rows(completed_b, ["availability"])
    route.write_csv(radius_rows, WORK / "design_search_R_a.csv")
    route.write_csv(availability_rows, WORK / "availability_sweep.csv")


def cmd_export() -> None:
    """Re-export CSVs from existing study stores (no re-run), with gates."""
    from simkit.study.query import StudyQuery
    from simkit.study.store import StudyStore

    exports = []
    radius_cases = None
    for study_id, axes, csv_name in [
        ("stellarator-design-search-ra-v1", ["R", "a"], "design_search_R_a.csv"),
        ("stellarator-availability-sweep-v1", ["availability"], "availability_sweep.csv"),
    ]:
        db = WORK / f"{study_id}.db"
        cases = StudyQuery(StudyStore(db), route.PACKAGE_DIR.resolve()).cases()
        completed = route._completed(cases, study_id)
        print(f"[export] {db.name}: {len(completed)}/{len(cases)} completed")
        if "R" in axes:
            radius_cases = completed
        exports.append((route.csv_rows(completed, axes), WORK / csv_name))
    _baseline_gate(radius_cases)
    assert_package_untouched()
    for rows, path in exports:
        route.write_csv(rows, path)


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("command", choices=["run", "export"])
    args = ap.parse_args()
    {"run": cmd_run, "export": cmd_export}[args.command]()
