import json
from pathlib import Path
H=Path('exploration/stellarator_e2e/studies/20260916-bounded-feasibility-transfer');G=Path('work/orchestration/goals/bounded-feasibility-transfer');P='stellarator_09__stellaris__';rows=json.loads((H/'results/oracle-scan.json').read_text())['rows'];native=json.loads((H/'results/native-cases.json').read_text());outside=[];inside=[]
for r in rows:
 I=r['point'][P+'magnet__coil__I_coil']
 (outside if I<12e6 or I>16.2e6 else inside).append(r)
unique=lambda rr:{json.dumps(r['point'],sort_keys=True) for r in rr}
assert len(outside)==9 and all(r['outcome']=='evaluated' and not r['full_satisfied'] for r in outside)
assert not unique(outside)&{json.dumps(r['inputs'],sort_keys=True) for r in native}
receipt={'frozen_commit':'a16e7256','finding':'Nine below-bound oracle-only points were not authorized by the declared search envelope.','declared_current_MAturn':[12,16.2],'actual_full_scan_current_MAturn':[min(r['point'][P+'magnet__coil__I_coil'] for r in rows)/1e6,max(r['point'][P+'magnet__coil__I_coil'] for r in rows)/1e6],'all_calls':len(rows),'all_unique':len(unique(rows)),'planned_and_control_calls':len(inside),'planned_and_control_unique':len(unique(inside)),'planned_and_control_unique_evaluated':len(unique([r for r in inside if r['outcome']=='evaluated'])),'planned_and_control_refused':len([r for r in inside if r['outcome']=='refused']),'native_cases_unchanged':len(native),'out_of_protocol':[{'id':r['id'],'current_MAturn':r['point'][P+'magnet__coil__I_coil']/1e6,'a_m':r['point'][P+'plasma__a'],'outcome':r['outcome'],'violated':r['violated'],'native_selected':False} for r in outside]}
(H/'coverage-erratum.json').write_text(json.dumps(receipt,indent=2)+'\n')
err='''# Post-freeze coverage erratum — 2026-09-16

[AGENT] Independent Round 1 review found nine oracle-only first-refinement coordinates below the declared 12 MA-turn minimum. The refinement script applied −6%, −4% and −2% to the lhs-22 anchor without checking the resulting bounds. Actual currents are 11.37253125, 11.6145 and 11.85646875 MA-turns, each at three minor-radius offsets. This was an execution protocol deviation. It was not a declared bound extension and is not retroactively authorized.

[AGENT] The frozen raw points, outputs, verdicts, snapshots and scripts at a16e7256 remain unchanged. The nine points are retained as out-of-protocol oracle diagnostics and excluded from the declared-window result. Exact IDs and outcomes are in coverage-erratum.json. None passed and none was selected for native execution.

| Coverage category | Calls | Unique coordinates | Unique evaluated | Refused |
|---|---:|---:|---:|---:|
| Declared window and explicit historical controls | 192 | 191 | 185 | 6 |
| Out-of-protocol oracle-only diagnostics | 9 | 9 | 9 | 0 |
| Entire retained scan | 201 | 200 | 194 | 6 |

[AGENT] All 71 native cases, their 16,046 scalar/1,420 predicate verification comparisons, transfer checks and zero combined-pass result are unchanged. The planned/control cohort also has zero combined passes. The full raw scan's actual current range is 11.37253125–16.2 MA-turns; the authorized main-search range remains 12.0–16.2 MA-turns. Historical allocation controls were already explicitly excepted from the main allocation bounds.

[AGENT] This erratum corrects frozen record §11, reviews/refine1-selection.md and reviews/window-selection.md wherever they say all coordinates remain inside bounds or imply all 200 coordinates belong to declared coverage. Those original documents remain evidence of what was claimed when execution happened. Read their range and coverage statements with this correction. Other frozen numerical results are unchanged. Synthesis, goal answer and readiness now use the corrected scope. The search remains finite and negative; it supplies no global infeasibility proof.
''';(H/'coverage-erratum.md').write_text(err)
with (H/'record.md').open('a') as f:f.write('\n## Post-freeze coverage correction — 2026-09-16\n\n[AGENT] Independent review found nine oracle-only first-refinement points below the declared current minimum. The unchanged raw scan contains 201 calls/200 unique points, but only 191 unique planned/control coordinates (185 evaluated, six refused); nine evaluated diagnostics are outside protocol. All 71 native cases and their verification remain unchanged. [Coverage erratum](coverage-erratum.md) and [exact classification](coverage-erratum.json) supersede the bound-compliance statements in §11 and the frozen window/refinement prose. No bound was retroactively expanded.\n')
p=H/'synthesis.md';s=p.read_text();s=s.replace('The 201 oracle calls cover 200 unique coordinates; 194 unique points evaluate and six are refused by the conductor-field domain.','The 201 retained oracle calls cover 200 unique coordinates. Declared-window/control coverage is 191 unique coordinates: 185 evaluate and six are refused by the conductor-field domain. Nine evaluated oracle-only coordinates fall below the declared current minimum and are retained separately as out-of-protocol diagnostics (coverage-erratum.md).');p.write_text(s)
p=G/'answer.md';s=p.read_text();s=s.replace('The staged search evaluated 200 unique oracle coordinates: 194 returned model quantities and six were refused by the conductor-field domain.','The declared-window/control search contains 191 unique oracle coordinates: 185 returned model quantities and six were refused by the conductor-field domain. Nine additional evaluated oracle-only points fell below the declared current bound and are retained separately as out-of-protocol diagnostics.');s=s.replace('One reference alias repeats a coordinate: 201 calls, 200 unique points.','One reference alias repeats a coordinate: 201 calls, 200 unique points in the entire retained scan. Independent review found nine below-bound first-refinement points caused by unchecked current perturbations. The corrected authorized-window/control count is 192 calls at 191 unique coordinates; none of the nine exceptions entered the native sample. The [post-freeze erratum](../../../../exploration/stellarator_e2e/studies/20260916-bounded-feasibility-transfer/coverage-erratum.md) preserves the error and exact exceptions without retroactive bound expansion.');p.write_text(s)
p=G/'readiness.md';s=p.read_text().replace('201 oracle calls at 200 unique points, with zero combined passes.','201 retained oracle calls at 200 unique points, with zero combined passes. Independent review separated nine below-bound oracle-only protocol deviations; declared-window/control coverage is 191 unique coordinates (185 evaluated, six refused). All native cases and transfer checks are unchanged.');p.write_text(s)
p=G/'transfer-contract.md';s=p.read_text();s+='\n[AGENT] A post-freeze [coverage correction](../../../../exploration/stellarator_e2e/studies/20260916-bounded-feasibility-transfer/coverage-erratum.md) excludes nine below-bound oracle-only diagnostics from declared search coverage. The three native transfer anchors and all isolated/native accommodation checks are unaffected.\n';p.write_text(s)
p=G/'evidence/finding-dispositions.md';s=p.read_text().replace('Proposed for final independent review.','Round 1 substantive routing accepted subject to the Round 2 coverage correction.');s+='\n[AGENT] Current finding #1 retains the raw total of 194 evaluated unique coordinates as its first sighting; the corrected declared-window/control interpretation is 185 evaluated plus six refusals, with nine additional out-of-protocol diagnostics. The concrete correction is the native coverage erratum. All other new dispositions and earlier accepted repairs remain unchanged.\n';p.write_text(s)
print(receipt['planned_and_control_unique'],receipt['planned_and_control_unique_evaluated'],receipt['planned_and_control_refused'])
