"""Write concise seventeen-section argument and first-sighting findings."""
import hashlib,json
from pathlib import Path
H=Path(__file__).resolve().parents[1];R=H/'results';P='stellarator_09__stellaris__';read=lambda p:json.loads(p.read_text())
a=read(R/'analysis.json');rows=a['cases'];axes=read(H/'axes.json')['groups'];cat=read(R/'predicate-catalog.json');sid=H.name
findings=[('The informative entering case needs 16 representative loops to meet the adopted reference-flow screen; fifteen remain insufficient.','Conditional capacity requirement only; representative average loops are not a qualified replication of heterogeneous source circuits.'),('Adding representative loops reduces per-loop flow/loss and total pumping demand, while all magnet and divertor heat-account outputs and predicates remain exactly fixed. No sampled case passes all twenty predicates.','Preserve independent subsystem and combined verdicts; no plant-feasibility or global-infeasibility claim.'),('Native coolant and capital account changes contain no added-equipment price. Annualized break-even headroom quantifies only the additional equivalent annual cost that removes the inherited-account benefit.','Supplier/equipment quote remains required; the new admitted BoP paper names an internal budget report and omitted large-pipe scope without a transferable installed price.'),('Routing, real IB/OB flow allocation, IHX/compressor qualification, drive losses and area enlargement remain unrepresented or unsupported in this diagnostic.','Retain calibrated pressure-loss/unit caveats and nominal-duty comparisons; do not promote averaged-flow allowance to hardware capacity or add a study-local geometry law.')]
home='work/orchestration/goals/primary-loop-sizing';fr=[{'id':f'{sid}#{n}','kind':'model','finding':f,'disposition':d,'home':home} for n,(f,d) in enumerate(findings,1)];(H/'preparation/findings.json').write_text(json.dumps(fr,indent=2)+'\n')
log=H.parent/'DISCOVERY_LOG.md';existing=log.read_text()
with log.open('a') as f:
 for x in fr:
  if x['id'] not in existing:f.write(f"| 2026-09-16 | model | {x['id']} | {x['finding']} | {x['disposition']} | {home} |\n")
out=[]
def p(s=''):out.append(s)
def h(n,s):p(f'## {n}. {s}');p()
def table(head,body):
 p('| '+' | '.join(head)+' |');p('| '+' | '.join('---' for _ in head)+' |')
 for r in body:p('| '+' | '.join(str(x).replace('|','/') for x in r)+' |')
 p()
h(1,'Study header');p(f'**Study id:** {sid}. **Package:** stellarator_tea. **Date executed:** 2026-09-16. **Executor:** Codex delegated /root/sizing_study. **Mode:** execute. **Arm:** arm-native, one unchanged package and native store.');p()
h(2,'Intake')
for q in ['Make primary-loop capacity follow an explicitly sized cooling system, with consistent heat removal, flow, pressure drop, pumping power and cost.','Revisit the reference and the informative case that requires 245.27 kg/s per loop against 225.08 kg/s allowed.','Preserve the divertor limit and all magnet constraints. A loop-capacity pass must remain separate from combined feasibility.','The goal is to explain and price the required cooling-system accommodation, not simply raise the flow limit. Keep the existing coolant choice; changing coolant technology would be a separate goal. If evidence cannot support a sizing option, a quantified capacity requirement and explicit evidence gap are valid results.']:p('[OWNER-VERBATIM] “'+q+'”');p()
p('[AGENT] Twenty conditional count-only comparisons use five captured entering contexts. The existing native count input supports a reduced hydraulic diagnostic. Installed equipment cost and engineering qualification remain evidence gaps. The bounded delegated scope is retained in preparation/study-brief.md; protocol.md records the proposed procedure.');p()
h(3,'Objective and result');p(f'Objective channel: `{P}lcoe_calc__lcoe` in dollars/MWh. All 20 native cases completed. Numeric LCOE spans {min(r["quantities"]["LCOE_dollars_MWh"] for r in rows):.9g}–{max(r["quantities"]["LCOE_dollars_MWh"] for r in rows):.9g}; this is inherited accounting with physical additions unpriced. It is not a priced equipment benefit or a feasible optimum. Complete quantities: results/case-summary.csv and results/analysis.json.');p()
table(['Context','Loops','Flow/loop kg/s','Loss kPa','Pump electric MW','IHX/loop MW','LCOE $/MWh','Loop pass'],[(r['family'],r['quantities']['loops'],f"{r['quantities']['flow_per_loop_kg_s']:.6f}",f"{r['quantities']['dp_loop_Pa']/1000:.6f}",f"{r['quantities']['electrical_work_MW']:.6f}",f"{r['quantities']['IHX_per_loop_MW']:.6f}",f"{r['quantities']['LCOE_dollars_MWh']:.6f}",r['loop_screen_satisfied']) for r in rows])
p('Total flow is fixed by source heat = mdot × cp × deltaT. IHX heat includes fluid work; pump electricity is fluid work divided by drive efficiency. More parallel representative loops reduce their per-loop flow and pressure loss. At held source heat this lowers fluid work and IHX duty; the gross/net and inherited cost responses remain native outputs. All residuals and full flow/capacity/temperature/work/equipment quantities are in results/analysis.json.');p()
p('The inherited divertor capital correlation also changes with thermal power: this is indirect accounting, not physical target redesign or a realized cost saving. Divertor heat-account outputs and predicates remain fixed; its cost is retained separately in results/case-summary.csv.');p()
p('Annualized break-even headroom equals (LCOE_14 − LCOE_N) × 8760 × net_MWN × availability_N. This is the additional equivalent annual cost that removes the inherited-account benefit. It is dollars/year, not capital cost or an installation quote. preparation/source-evidence/mfe_lcoe_dcf.sysml retains the energy denominator; preparation/cost-review.md independently checks the algebra. Fixed finance/calendar conventions carry through this calculation.');p()
h(4,'Constraint outcomes');p(f"The loop screen passes {a['overall']['loop_screen_passes']} of 20; combined passes: {a['overall']['all20_passes']}. Qualified IDs and every individual verdict are retained in results/native-cases.json and the native evidence store. Failed cases are not removed.");p()
table(['constraint_id','source_local_identity','Statuses'],[(cid,e['source_local_identity'],str(a['predicate_outcomes'][cid]['counts'])) for cid,e in cat.items()])
h(5,'Framing');p('Proposed and judged framing are sensitivity for all eight groups; none changed. The count intervention is isolated within each context. Other groups vary only between inherited contexts, so they have no independently identified causal effect. No optimum or engineering boundary is claimed.');p()
table(['Axis','Proposed','Judged','Changed'],[(g['axis'],'sensitivity','sensitivity','no') for g in axes])
h(6,'Per-axis account')
for g in axes:
 p(f"#### {g['axis']} — feasible structure (search framing)");p();p('Not applicable: sensitivity-framed.');p();p(f"#### {g['axis']} — observed response (sensitivity framing)");p()
 p('Count increases reduce per-loop flow, pressure loss and pumping work at held source heat, with conditional LCOE/account consequences and retained other failures. The exact sampled flow-screen crossing is reported without a hardware-capacity boundary claim.' if g['axis']=='heat_transport__n_loops' else 'This is inherited context, co-varying with other context inputs. Its independent effect is not isolated. Every selected combination and failure is retained in preparation/proposals.json and results/case-summary.csv; no boundary claim is made.');p()
h(7,'Axis groups');p('Each public attribute maps to one complete native entry-key group. All eight groups carry fan_out provenance in axes.json. The native radius already feeds its dependents; no distinct magnet radius or undeclared tie is injected. Fixed controls remain in each point exactly as captured in preparation/entering/native-cases.json. Source-derived conditional equipment quantities are postprocessing and do not become native outputs.');p()
table(['Axis','Entry key','Provenance'],[(g['axis'],k['key'],k['provenance']) for g in axes for k in g['keys']])
h(8,'Indicators and rulings');p('All eight full, non-subset groups have constraints_reachable; none has no_constraint_response. The owner-reserved missing-pushback ruling is therefore inapplicable. Coordinator release is preparation/execution-release.json and reviews/preexecution-check.md. Conservative paths do not prove response. Monotonicity, physical identity across key names and intra-module operand dependency are not derivable from indicators.');p()
p('Area enlargement was declined at scope formation: no supported native area/routing/IHX input and insufficient source evidence. No invented key can be traced by indicators; finding #4 records the missing representation. All existing acceptance limits remain fixed.');p()
h(9,'Preflight results');p('Exact manifest baseline and all mechanical preflight gates pass. Identity, baseline, full gate outcomes and warning-only suffix siblings are captured in results/package_identity.json, baseline_result.json and preflight_results.json. Package cleanliness passes before/after execution. preparation/runtime-command.md records invocation and inherited serialization warnings.');p()
h(10,'Execution route and why');p('Stock study_route.run_points uses the native PreparedListStrategy lifecycle. A prepared list preserves the five inherited joint contexts while varying only count within each family. study.py defines the invocation; results/entry-models.json captures the complete actual entry-model map. Glue ledger: none; no adapter or harness-supplied physical law. The SQLite store, content-addressed evidence, qualified predicates and exported numeric outputs are retained; results/native-store-check.json checks every join.');p()
h(11,'Study definition and window provenance');p('The independent oracle scanned integer counts 12 through 18 at each of five contexts. reviews/window-selection.md records the post-scan choice of 14, 15, 16 and 18 loops before native execution. This engineered window retains entering 14, the informative near-miss 15, its minimum count 16 and comparison 18. It is not a source-qualified feasible region. All 35 oracle evaluations are retained in results/oracle-scan.json. The 20 unique native study cases and required baseline are distinct execution obligations. No refinement native cases or validity mask were needed.');p()
h(12,'Cross-fingerprint correlation and what it means');p('Single unchanged package fingerprint: no cross-arm fingerprint correlation needed. Five 14-loop outputs and predicates compare exactly to the captured entering native controls in preparation/entering/native-cases.json; results/comparison-entering.json records the checks. Within each family all native magnet and divertor heat-account outputs and their named predicates are exactly fixed, as checked in results/held-subsystems.json. This does not infer hardware validity.');p()
h(13,'Verification');p('All 4,520 mapped scalar comparisons and 400 independently rederived exact predicates pass. Generic verification separately samples by observed verdict combination and passes; its exact sample, coverage and command are in results/verification_summary.json. All 242 native numeric channels are retained; the 16 outside the independent oracle map are listed in results/oracle-all-points.json. Held quantities identical by construction and energy-account residuals are consistency evidence, not equipment qualification. The oracle shares source assumptions and does not prove those assumptions.');p()
h(14,'Review outcomes');table(['Lens','Verdict','Disposition'],[('Original source/math','Independent scoped PASS after correction','preparation/source-review.md; representative-loop qualification/cost limits retained'),('Cost/algebra','Independent PASS','preparation/cost-review.md; annualized headroom only'),('Native integration','CANDIDATE; all 10 pass','preparation/integration-return.json; unchanged package'),('Protocol/window','Coordinator release; executor post-scan selection','reviews/preexecution-check.md and window-selection.md'),('Arithmetic/custody','Executor checks pass','Results retained; not independent self-certification'),('Final integrated study','Pending parent-arranged independent review','No goal closure or final certification asserted')])
h(15,'Findings');table(['Id','Kind','Finding','Disposition','Home'],[(x['id'],x['kind'],x['finding'],x['disposition'],x['home']) for x in fr]);p('First-sighting rows join the discovery log using these exact IDs. Parent owns later dispositions.');p()
h(16,'Snapshot');snap=H/'snapshot.json';p('**File:** snapshot.json. **Schema version:** 1. **sha256:** '+(hashlib.sha256(snap.read_bytes()).hexdigest() if snap.exists() else 'Pending freeze.'));p()
h(17,'What this record does not contain');p('No installed hardware quote or qualified circulator/IHX/large-pipe selection; no heterogeneous IB/OB circuit design; no spatial routing or channel/area enlargement model; no validated off-design transfer or drive-loss model; no global optimum or combined feasible plant. The nominal source IHX average is a comparison, not installed capacity. Source pressure-table inconsistency and calibration remain disclosed in preparation/source-review.md. Final independent review and executor synthesis follow parent commit/review; they are not self-certified here.');p()
(H/'record.md').write_text('\n'.join(out))
# A short report is generated entirely from the retained numeric account.
report=['# Conditional primary-loop sizing','', 'The informative case meets the adopted flow screen at 16 representative loops. Added equipment remains unpriced, and none of the 20 sampled cases passes all twenty plant predicates.','', '| Context | Minimum representative count | Flow total kg/s | 14-loop pump MW | 16-loop pump MW | 16-loop annual headroom $/yr |','|---|---|---|---|---|---|']
for family in dict.fromkeys(r['family'] for r in rows):
 b=next(r['quantities'] for r in rows if r['family']==family and r['quantities']['loops']==14);n=next(r['quantities'] for r in rows if r['family']==family and r['quantities']['loops']==16)
 report.append(f"| {family} | {b['minimum_representative_integer_count']} | {b['flow_total_kg_s']:.6f} | {b['electrical_work_MW']:.6f} | {n['electrical_work_MW']:.6f} | {n['annualized_break_even_headroom_dollars']:.2f} |")
report+=['','Headroom is an equivalent annual cost budget, not a capital estimate. Native coolant/CAS/LCOE and divertor-cost changes are inherited accounting and omit added equipment pricing. The changing divertor cost follows thermal power, not target redesign or a realized saving. Conditional equipment quantities are 2N circulators and N IHXs; real circuit allocation, routing, exchanger/compressor performance and supplier quotes remain required.','', 'Sources: results/analysis.json and results/case-summary.csv; full constraints, verification and evidence limits: record.md.']
(R/'report.md').write_text('\n'.join(report)+'\n')
print('Wrote record, report and four first-sighting findings.')
