"""Write executor study account; preserve coordinator-owned findings section."""
import hashlib,json,re
from pathlib import Path
H=Path(__file__).resolve().parents[1];R=H/'results';read=lambda p:json.loads(p.read_text());a=read(R/'analysis.json');v=read(R/'oracle-all-points.json');e=read(R/'execution-summary.json');axes=read(H/'axes.json')['groups'];old=(H/'record.md').read_text();out=[]
def sec(n,title,text):out.extend([f'## {n}. {title}','',text,''])
sec(1,'Study header',f'**Study id:** {H.name}. **Package:** stellarator_tea. **Date executed:** 2026-09-16. **Executor:** Codex delegated native-study executor. **Mode:** execute. **Arm:** arm-native. One unchanged WI-065 package.')
intake=(H/'preparation/owner-intake.md').read_text() if (H/'preparation/owner-intake.md').exists() else '[OWNER, captured paraphrase] Establish a bounded feasible region under defensible fixed assumptions and distinguish model-side design-point transfer from blind-comparison readiness.'
sec(2,'Intake',intake+'\n\n[AGENT] The bounded prepared list implements the staged protocol in protocol.md. Engineered ranges, selection and stopping rules are agent choices. Hardware qualification, predictive accuracy and economic optimization are separate questions.')
sec(3,'Objective and result',f"The study seeks combined physical-screen passes. The retained native objective channel is `stellarator_09__stellaris__lcoe_calc__lcoe`, dollars/MWh, reported only as conditional inherited accounting. {a['overall']['cases']} prepared-list cases completed in {e['elapsed_seconds']:.3f} seconds, in addition to the required pinned baseline. {a['overall']['all20_passes']} pass all twenty authored predicates; {a['overall']['valid_account_combined_passes']} also have a valid divertor power account. Complete quantities and signed margins: results/case-summary.csv and results/analysis.json. No LCOE-based optimum is inferred.")
table='| Qualified constraint | Local identity | Outcomes |\n|---|---|---|\n'+'\n'.join(f"| {cid} | {x['source_local_identity']} | {x['counts']} |" for cid,x in a['predicate_outcomes'].items())
sec(4,'Constraint outcomes',table+'\n\nAll verdicts, rejected coordinates and invalid power accounts remain in native-cases.json and the store. Positive signed margins in case-summary.csv mean the authored comparison is satisfied away from equality; exact verdicts govern equality and strict operators.')
sec(5,'Framing','Proposed and judged: bounded search for radius, minor radius, current, radial allocation, transverse cavity and loop count. Sizing mode and inventory reserve are fixed main-search assumptions with separately identified legacy controls. No framing changed. Costs are diagnostic outputs with omitted accommodation prices, not the search ranking.')
sec(6,'Per-axis account','The sampled region and rejection structure are reported by exact coordinates and family in results/case-summary.csv. Radius/minor-radius/current perturbations test coupled field, confinement, heat and flow responses. Radial allocation changes field and winding-pack fit; transverse allocation changes fit without complete mass/structural/cost response. Loop count tests the adopted representative flow allowance with unpriced added equipment. The finite local samples establish no continuous feasible box, qualified hardware boundary or global infeasibility. Fixed sizing mode/reserve do not receive independent sensitivity claims. Exact one-input contrasts and combined perturbations are identified in preparation/proposals.json.')
sec(7,'Axis groups','All complete public entry-key groups and provenance are in axes.json. Inputs resolve against preparation/resolved-defaults.json; each native row retains exact overrides. Native dependency propagation uses the stock package. No additional physical tie or harness equation is injected.')
sec(8,'Indicators and rulings','All declared groups were traced without subset selection. Each has constraints_reachable, a possible dependency path rather than evidence of response. No group has no_constraint_response. Monotonicity, physical identity across differently named keys and intra-module operand dependency are not derivable from indicators. Fixed performance assumptions and inherited screening limits remain as recorded in protocol.md.')
sec(9,'Preflight results','Pinned baseline, package identity and all mechanical preflight gates passed; complete gate results and warnings are in results/preflight_results.json. Package cleanliness is retained before and after execution. Baseline runtime and native runtime are separate result artifacts; preparation/runtime-command.md records reproduction.')
sec(10,'Execution route and why','The stock StudyRunner + PreparedListStrategy lifecycle preserves the coordinated candidate list. Glue ledger: none; no adapter. study.py and execution/execute.py retain the route. Native SQLite stores, content-addressed evidence, the complete entry-model map, 242 numeric outputs and twenty qualified predicates are retained. Executor store checks verify evidence digests and export joins without rerunning models.')
sec(11,'Study definition and window provenance','protocol.md records the engineered bounds and staged budget before execution. Exact finite scan lists precede their corresponding oracle results. reviews/window-selection.md records the coordinator’s final native selection after scanning. All scans and their refusals are retained. The native list preserves informative rejections, transfer controls and local perturbations. Selection never enlarges the stated ranges or relaxes performance assumptions. Engineering applicability remains unqualified.')
sec(12,'Cross-fingerprint correlation and what it means','Single unchanged package fingerprint; no cross-arm correlation is needed. Package candidate, semantic and executable identities are captured in preparation/integration-return.json and results/package_identity.json. Prior studies contribute reviewed interpretation and equations; the current selected coordinates receive fresh native/oracle checks.')
sec(13,'Verification',f"All {v['scalar_comparisons']} mapped scalar comparisons at relative/absolute 1e-9 and {v['predicate_comparisons']} exact oracle-derived predicate comparisons pass. Generic verdict-stratified verification is retained in results/verification_summary.json. The sixteen native channels outside the oracle map are listed in results/oracle-all-points.json. Shared source assumptions, held inputs and static L2/L6/read-set limitations remain; arithmetic agreement does not establish empirical accuracy or hardware qualification.")
sec(14,'Review outcomes','Prior source/math coverage is reused as named in protocol.md. Current preexecution/window checks are coordinator checks, not independent verdicts. Native custody, all-point arithmetic and generic verification are executor checks. Any final scoped independent review is retained under reviews/ with its authorship and exact scope; this record does not self-certify independent coverage.')
m=re.search(r'## 15\. Findings\n(.*?)\n## 16\.',old,re.S)
findings=m.group(1).strip() if m and '<' not in m.group(1) else 'Coordinator-owned findings register is pending. Proposed rows are in results/findings-proposed.json.'
sec(15,'Findings',findings)
snap=H/'snapshot.json';sec(16,'Snapshot','**File:** snapshot.json. **Schema version:** 1. **sha256:** '+(hashlib.sha256(snap.read_bytes()).hexdigest() if snap.exists() else 'Pending coordinator-authorized freeze.'))
sec(17,'What this record does not contain','No validated off-design confinement or material-performance transfer; no installed price for added cooling equipment or complete cavity-accommodation cost; no qualified IHX/circulator/pipe design; no global optimum, entire continuous feasible region or empirical accuracy claim. Divertor profile, transport/calibration anchors, technology performance and acceptance limits remain held. The blind holdout stays sealed. A failed authored predicate remains a prediction to compare, not permission to tune the target.')
(H/'record.md').write_text('\n'.join(out))
print('Executor record written; coordinator-owned findings preserved.')
# Compact numeric reading; all values below come from retained native analysis.
rows=a['cases'];best=next(r for r in rows if r['proposal_id']=='fine-R-0.1-I-0.03')
report=['# Bounded physical-screen result','',f"All {len(rows)} selected native cases completed. None passes all twenty predicates. {a['overall']['invalid_power_accounts']} cases have invalid divertor power accounts and remain in the evidence.",'','The coordinator-selected closest sampled rejection is shown below. Selection uses normalized authored margins, not physical distance to feasibility. This point is a local tradeoff, not an optimum.','', '| Quantity | Native value |','|---|---|']
for k in ['R_m','a_m','current_MAturn','radial_exterior_m','transverse_cavity_m','loops','LCOE_dollars_MWh','total_capital_dollars']:report.append(f"| {k} | {best['quantities'][k]:.12g} |")
for k in ['burn_hold_ok','sustainment_ok','peak_field_ok','wp_fit_ok','divertor_heat_ok','loop_capacity_ok','wall_load_ok']:report.append(f"| Signed {k} margin | {best['signed_margins'][k]:.12g} |")
report+=['','Signed margins use the authored operands and units. Negative field/divertor/wall margins are simultaneous deficits; passing burn, sustainment, fit and loop margins do not erase them.','', '| Transfer anchor | R m | a m | MA-turn | Failed predicates |','|---|---|---|---|---|']
for r in rows:
 if r['family']=='transfer-coupled' or r['proposal_id']=='control-allocated-current-sized-reference':
  q=r['quantities'];report.append(f"| {r['proposal_id']} | {q['R_m']:.6g} | {q['a_m']:.6g} | {q['current_MAturn']:.6g} | {', '.join(r['violated'])} |")
report+=['','Single-input transfer contrasts, every individual predicate, all equipment duties/counts and conditional costs are in case-summary.csv. Full native outputs are in native-cases.json. The sixteen oracle-unmapped channels are enumerated in oracle-all-points.json.','',f"All {v['scalar_comparisons']} mapped scalar and {v['predicate_comparisons']} predicate comparisons pass. Generic verification additionally samples all observed verdict combinations.",'','Six exact matched-loop pairs are recorded in analysis.json under matched_loop_headroom. Their headroom is an annual omitted-cost budget, not installed capital or a net saving. Conditional 2N circulators/N IHXs carry duties but no qualification or added-equipment quote.','', 'The engineered finite search establishes neither global infeasibility nor predictive accuracy. No feasible neighborhood was found. Held transport/material/source-profile assumptions and unsupported geometry/cost dependencies remain in record.md and protocol.md.']
(R/'report.md').write_text('\n'.join(report)+'\n')
