"""Write all seventeen study sections from retained evidence, before coordinator commit."""
import json
from pathlib import Path
H=Path(__file__).resolve().parents[1];R=H/'results';read=lambda p:json.loads(p.read_text())
rows=read(R/'interpreted-cases.json');cat=read(R/'predicate-catalog.json');summary=read(R/'summary.json');n=len(rows);b=summary['reference'];props=read(H/'preparation/proposals.json');groups=read(H/'axes.json')['groups'];ind=read(H/'indicators.json');pre=read(R/'preflight_results.json')
old=(H/'record.md').read_text();intake=old.split('## 2. Intake\n\n')[1].split('## 3. Objective and result')[0].strip();S={}
S['1. Study header']=f'- **Study id:** {H.name}\n- **Package:** stellarator_tea\n- **Date executed:** 2026-09-19\n- **Executor:** Codex fuel_sources; source researcher, independent-oracle implementer and study executor. No independent final certification claimed.\n- **Mode:** execute\n- **Arms:** arm-native'
S['2. Intake']=intake
S['3. Objective and result']=f'- **LCOE objective channel:** `stellarator_09__stellaris__lcoe_calc__lcoe`.\n- **Reference LCOE:** ${b["LCOE_dollars_MWh"]:.6f}/MWh.\n\nLCOE spans ${summary["ranges"]["LCOE_dollars_MWh"]["min"]:.6f}–{summary["ranges"]["LCOE_dollars_MWh"]["max"]:.6f}/MWh over the selected cases. Fuel inventory/startup is the scientific question; LCOE is reported as the native objective, not optimized. The model exposes {b["total_kg"]:.6f}kg reference represented tritium and {b["startup_conservative_kg"]:.6f}kg conservative initial supply. [Report](report.md) explains the distinction and source limits; [native points](results/points.csv) contain the actual values.'
a=['| `constraint_id` | `source_local_identity` | Status | Note |','|---|---|---|---|']
for cid,e in cat.items():
 counts=summary['predicate_counts'][cid];failed=[r['proposal_id'] for r in rows if r[cid]!='satisfied'];status='satisfied' if not failed else ('violated' if len(failed)==n else 'satisfied / violated by case')
 detail=f'{counts["satisfied"]} satisfied; {counts["violated"]} violated; {counts["indeterminate"]} indeterminate.'
 if failed:detail+=' Violated at '+(', '.join(failed) if len(failed)<n else 'all cases')+'.'
 a.append(f'| `{cid}` | `{e["source_local_identity"]}` | {status} | {detail} |')
S['4. Constraint outcomes']=f'All25 authored predicates are retained at all{n} cases; {summary["wholeplant_satisfied"]} cases satisfy every predicate. Complete qualified per-point verdicts are in [native cases](results/native-cases.json).\n\n'+'\n'.join(a)
a=['**As proposed at intake.**','','| Axis | Framing proposed | Why |','|---|---|---|']
for g in groups:a.append(f'| {g["axis"]} | sensitivity | Explicit source/performance/policy or diagnostic response; no optimization. |')
a+=['','**As judged after the run.**','','| Axis | Framing judged | Changed? | Why |','|---|---|---|---|']
for g in groups:a.append(f'| {g["axis"]} | sensitivity | no | All selected cases retained; source/performance and policy dependencies remain conditional. |')
S['5. Framing']='\n'.join(a)
a=[]
for g in groups:
 axis=g['axis'];keys={x['key'] for x in g['keys']};ids=[p['id'] for p in props if keys.intersection(p['point'])];selected=[r for r in rows if r['proposal_id'] in ids]
 failed=sorted({s for r in selected for s in r['violated'].split(';') if s})
 a += [f'#### {axis} — feasible structure (search framing)','', '**Applies:** Not applicable; this axis is sensitivity-framed.','',f'#### {axis} — observed response (sensitivity framing)','', '**Applies:** Yes.', '',f'Cases: {", ".join(ids)}. Represented stock spans {min(r["total_kg"] for r in selected):.6g}–{max(r["total_kg"] for r in selected):.6g}kg T and conservative startup supply {min(r["startup_conservative_kg"] for r in selected):.6g}–{max(r["startup_conservative_kg"] for r in selected):.6g}kg T. Values and input changes are in `results/points.csv` and `preparation/proposals.json`. Joint cases change several inputs and are not single-axis effect estimates. No boundary claim is made. Violated predicates within these selected cases: {", ".join(failed) or "none"}; exact locations are recorded in §4 and the per-point qualified verdict columns.', '']
S['6. Per-axis account']='\n'.join(a).strip()
a=['| Axis | Entry key | Provenance | Note |','|---|---|---|---|']
for g in groups:
 for k in g['keys']:a.append(f'| {g["axis"]} | `{k["key"]}` | {k["provenance"]} | Complete authored public input key. |')
S['7. Axis groups']='\n'.join(a)+'\n\n[All-axis declaration](axes.json). No ties, retired computed-inventory input or computed power/breeding sweep.'
a=['| Axis | Indicator | Ruling | Note |','|---|---|---|---|']
for g in ind['groups']:a.append(f'| {g["axis"]} | '+('no_constraint_response' if g['no_constraint_response'] else 'constraints_reachable')+' | Coordinator sensitivity release under explicit owner delegation | Swept; graph reachability is conservative and does not prove response. |')
a+=['','[Proposed framing](reviews/proposed-framing.md), [coordinator disposition](reviews/axis-rulings.json), [window release](reviews/window-release.json). All15 groups traced; no subset or suffix warnings.','', '**Not derivable:** monotonicity of a channel in an axis, physical identity across different key names and intra-module operand dependency. None is claimed by the indicators. `constraints_reachable` means a possible path; `unresisted` would be an executor judgment, not a tool result.','', f'No axis was mechanically no_constraint_response. Nonetheless finding `{H.name}#1` retains the missing equipment/reliability/supply relationships that would constrain the physical choice of residence, recovery, reserve and buffer. Shutdown and extension durations are diagnostic observation windows. Their conservative graph path to TBR is not an assertion that these durations change steady required breeding.']
S['8. Indicators and rulings']='\n'.join(a)
a=['| Gate | Outcome | Detail |','|---|---|---|']
for g in pre['gates']:
 a.append(f'| {g.get("gate",g.get("name","recorded gate"))} | {g.get("outcome",g.get("status"))} | See original gate result in `results/preflight_results.json`. |')
S['9. Preflight results']='\n'.join(a)+'\n\nThe identity and baseline gates read `results/package_identity.json` and `results/baseline_result.json`. [Preflight](results/preflight_results.json) and before/after cleanliness receipts retain every mechanical result. No study preflight gate was skipped. Integration returned all10 gates passing; its manifest-gate read-set coverage was not run, as retained in `preparation/integration-return.json`. Passing integration does not discharge that limitation.'
S['10. Execution route and why']='- **Route:** study-local direct API using stock `StudyRunner` and `PreparedListStrategy` through `study_route.run_points`.\n- **Why:** a finite coordinated list preserves one-factor cases, a paired extension case and joint scenarios without a Cartesian product. The route loaded the released package, reproduced the pinned baseline and passed preflight before scanning/execution.\n\nGlue ledger: none. The caller declares inputs, requests channel coverage and records outputs; it contains no physical model computation or solver. Runtime import setup only exposes the pinned teax package. [Environment](results/execution-environment.json) records the revision; the complete generated producer package and route/tool sources are copied for cold reproduction.'
S['11. Study definition and window provenance']=f'The finite engineered window was chosen from released source scenarios and explicit policy/diagnostic choices. The independent oracle evaluated all{n} candidates after baseline/preflight; every case remained in the supported model domain with defined breeding. The coordinator accepted the complete list in `reviews/window-release.json`; no case was removed to improve feasibility. `results/oracle-scan.json` retains all mapped values and independent verdicts. This is not a restated feasible-neighborhood window, continuous boundary scan or optimization. Source residence scenarios are not physical bounds for helium/PbLi; the joint fast/slow cases are not uncertainty quantiles.'
S['12. Cross-fingerprint correlation and what it means']='Single fingerprint; no cross-arm correlation is needed. Historical studies remain attached to their recorded revisions. This record does not substitute its results for the frozen comparison archive.'
v=read(R/'oracle-all-points.json')
S['13. Verification']=f'All{v["scalar_comparisons"]} mapped scalar comparisons and{v["predicate_comparisons"]} independently derived predicate comparisons pass across all{n} cases. The generic verifier also passes. All914 numeric native channels are exported; 22 outside the906-scalar oracle map remain native evidence only. [All-point comparison](results/oracle-all-points.json) and [generic receipt](results/verification_summary.json) state exact coverage and tolerances.\n\nThe independent oracle implements startup draw through event-interval integration. Upstream independent tests check integrated storage trajectories, plasma particle integration, decay protection and half-life behavior. Shared nuclear transport data, source choices and accepted accounting premises are not independent physical verification. The oracle author is also this study executor; final certification requires the separate reviewer.'
S['14. Review outcomes']='| Lens | Verdict | Disposition |\n|---|---|---|\n| Independent original-source/design accounting | PASS for conditional implementation | Copied `preparation/references/source-design-review.md`; unchanged scope and equations. |\n| Independent implementation release | PASS for inspected executable | Copied `preparation/references/audit.md` and `audit-review.md`; exact executable matches integration. |\n| Native integration | CANDIDATE; all10 gates pass | `preparation/integration-return.json` and coordinator candidate release; read-set coverage remains not run. |\n| Framing/window | Coordinator release under owner delegation | `reviews/axis-rulings.json` and `window-release.json`; all26 finite sensitivities retained. |\n| Executor verification/readability | Completed, author check | Native scalar/predicate receipts and explicit inventory/startup explanation. |\n| Final independent study/goal grade | Pending after coordinator commit | No independent final approval asserted by executor. |'
findings=[('1','model','Residence/recovery/buffer/reserve scenarios lack equipment, reliability and external-supply couplings despite conservative graph paths to breeding.','Retain conditional scenario scope; no physical optimization or confidence bounds.','work/orchestration/goals/fuel-inventory-and-startup/learnings.md'),('2','model','Initial external supply differs from maintained stock because of prefilled stages, delayed returns and internally produced breeder inventory; longer deficient commissioning needs more supply.','Retain separate startup, working stock and recurring makeup channels.','work/orchestration/goals/fuel-inventory-and-startup/learnings.md'),('3','model','Running processor capacity stays separate from annual/calendar demand; maintained-stock decay persists through downtime.','Provide isotope-specific running capacities and calendar totals to downstream cost work.','work/orchestration/goals/fuel-inventory-and-startup/learnings.md'),('4','model','Every sampled case retains failed whole-plant screens; represented fuel inventory and startup verification do not establish full self-sufficiency or feasible plant operation.','Keep failures and source-transfer/omitted-stream limitations visible.','work/orchestration/goals/fuel-inventory-and-startup/learnings.md')]
S['15. Findings']='| Id | Kind | Finding | Disposition | Home |\n|---|---|---|---|---|\n'+'\n'.join(f'| `{H.name}#{i}` | {kind} | {f} | {d} | `{home}` |' for i,kind,f,d,home in findings)
S['16. Snapshot']='Pending final evidence freeze; written once after the record and tool copies are complete.'
S['17. What this record does not contain']='This record has no final independent grade or coordinator study commit yet; those are subsequent steps. It includes a frozen generated runtime package and required producer/helper/tool sources, but not the installed Python environment, syside license, full external teax/codegen checkouts or large upstream neutron-transport binaries. The native integration receipt identifies those external runtime dependencies. Reproduction needs a compatible installed runtime and the recorded revision. There is no new blanket transport calculation, vendor process performance, procurement-supply survey, measured startup transient or fuel-processing price design in this record.'
(H/'record.md').write_text('\n\n'.join('## '+heading+'\n\n'+text for heading,text in S.items())+'\n')
log=H.parent/'DISCOVERY_LOG.md';content=log.read_text()
with log.open('a') as f:
 for i,kind,finding,disposition,home in findings:
  identity=H.name+'#'+i
  if identity not in content:f.write(f'| 2026-09-19 | {kind} | `{identity}` | {finding} | {disposition} | `{home}` |\n')
print('17-section record and four first-sighting findings written')
